export const REQUISITION_FORM_SECTIONS = [
  { id: 1, title: "Requisition Identity" },
  { id: 2, title: "Requesting Party" },
  { id: 3, title: "Position Classification" },
  { id: 4, title: "Position Details" },
  { id: 5, title: "CDL & Regulatory Requirements" },
  { id: 6, title: "Compensation & Benefits" },
  { id: 7, title: "Job Description & Requirements" },
  { id: 8, title: "Recruiting Instructions" },
  { id: 9, title: "Budget & Headcount" },
  { id: 10, title: "BOF Pipeline Connection" },
  { id: 11, title: "Approvals" },
] as const;

export const REQUISITION_UPDATABLE_STRING_FIELDS = [
  "requestingCarrierName",
  "usdot",
  "mcNumber",
  "terminalDomicile",
  "statesOfOperation",
  "requestingManagerName",
  "department",
  "supervisor",
  "positionClassification",
  "employmentClassification",
  "flsaClassification",
  "urgency",
  "positionTitle",
  "reportingStructure",
  "workLocation",
  "homeTimePattern",
  "routeLane",
  "typicalNightsAway",
  "equipmentType",
  "soloTeamOperation",
  "cdlClass",
  "endorsements",
  "experienceRequirements",
  "mvrSafetyRequirements",
  "compensationStructure",
  "payRange",
  "accessorialPay",
  "signOnBonus",
  "performanceBonus",
  "benefits",
  "positionSummary",
  "essentialFunctions",
  "physicalRequirements",
  "schedule",
  "hosCycle",
  "recruitingInstructions",
  "sourcingChannels",
  "screeningRequirements",
  "applicationRouting",
  "targetFillMetrics",
  "budgetStatus",
  "headcount",
  "financialJustification",
  "estimatedRecruitingCost",
  "exceptions",
  "bofHrUse",
] as const;

export const REQUISITION_UPDATABLE_BOOLEAN_FIELDS = [
  "borderCrossings",
  "pspRequired",
  "clearinghouseRequired",
  "medicalRequired",
  "drugTestingRequired",
  "backgroundCheckRequired",
  "tsaRequired",
] as const;

export type RequisitionStringField = (typeof REQUISITION_UPDATABLE_STRING_FIELDS)[number];
export type RequisitionBooleanField = (typeof REQUISITION_UPDATABLE_BOOLEAN_FIELDS)[number];

export const REQUISITION_FIELD_LABELS: Record<string, { section: number; label: string }> = {
  publicNumber: { section: 1, label: "Requisition identity" },
  dateSubmitted: { section: 1, label: "Date submitted" },
  targetStartDate: { section: 1, label: "Target start date" },
  numberOfPositions: { section: 1, label: "Number of positions" },
  requestingCarrierName: { section: 1, label: "Requesting fleet/carrier" },
  fleetId: { section: 1, label: "Fleet ID" },
  usdot: { section: 1, label: "USDOT" },
  mcNumber: { section: 1, label: "MC number" },
  terminalDomicile: { section: 1, label: "Terminal/domicile" },
  statesOfOperation: { section: 1, label: "States of operation" },
  requestingManagerName: { section: 2, label: "Requesting manager" },
  department: { section: 2, label: "Department" },
  supervisor: { section: 2, label: "Supervisor" },
  positionClassification: { section: 3, label: "Position classification" },
  employmentClassification: { section: 3, label: "Employment classification" },
  flsaClassification: { section: 3, label: "FLSA classification" },
  urgency: { section: 3, label: "Urgency" },
  positionTitle: { section: 3, label: "Position title" },
  reportingStructure: { section: 3, label: "Reporting structure" },
  workLocation: { section: 4, label: "Work location" },
  homeTimePattern: { section: 4, label: "Home-time pattern" },
  routeLane: { section: 4, label: "Route/lane" },
  borderCrossings: { section: 4, label: "Border crossings" },
  typicalNightsAway: { section: 4, label: "Typical nights away" },
  equipmentType: { section: 4, label: "Equipment type" },
  soloTeamOperation: { section: 4, label: "Solo/team operation" },
  cdlClass: { section: 5, label: "CDL class" },
  endorsements: { section: 5, label: "Endorsements" },
  experienceRequirements: { section: 5, label: "Experience requirements" },
  minimumAge: { section: 5, label: "Minimum age" },
  mvrSafetyRequirements: { section: 5, label: "MVR/safety requirements" },
  pspRequired: { section: 5, label: "PSP requirement" },
  clearinghouseRequired: { section: 5, label: "Clearinghouse requirement" },
  medicalRequired: { section: 5, label: "Medical requirement" },
  drugTestingRequired: { section: 5, label: "Drug-testing requirement" },
  backgroundCheckRequired: { section: 5, label: "Background-check requirement" },
  tsaRequired: { section: 5, label: "TSA requirement" },
  compensationStructure: { section: 6, label: "Compensation structure" },
  payRange: { section: 6, label: "Pay range" },
  accessorialPay: { section: 6, label: "Accessorial pay" },
  signOnBonus: { section: 6, label: "Sign-on bonus" },
  performanceBonus: { section: 6, label: "Performance bonus" },
  benefits: { section: 6, label: "Benefits" },
  positionSummary: { section: 7, label: "Position summary" },
  essentialFunctions: { section: 7, label: "Essential functions" },
  physicalRequirements: { section: 7, label: "Physical requirements" },
  schedule: { section: 7, label: "Schedule" },
  hosCycle: { section: 7, label: "HOS cycle" },
  recruitingInstructions: { section: 8, label: "Recruiting instructions" },
  sourcingChannels: { section: 8, label: "Sourcing channels" },
  screeningRequirements: { section: 8, label: "Screening requirements" },
  applicationRouting: { section: 8, label: "Application routing" },
  targetFillMetrics: { section: 8, label: "Target fill metrics" },
  budgetStatus: { section: 9, label: "Budget status" },
  headcount: { section: 9, label: "Headcount" },
  financialJustification: { section: 9, label: "Financial justification" },
  estimatedRecruitingCost: { section: 9, label: "Estimated recruiting cost" },
  exceptions: { section: 9, label: "Exceptions" },
  recruitingPipelineState: { section: 10, label: "BOF recruiting pipeline state" },
  bofHrUse: { section: 11, label: "BOF HR use" },
};
