import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Operations & Compliance | BackOfficeFleet", description: "Connected operations, compliance, safety, maintenance, settlement, and exception administration for growing trucking fleets." };

const responsibilities = [
  ["Driver Qualification", "Maintain DQF inputs, qualification evidence, review status, and assignment consequences rather than leaving the file in a folder that someone must remember to reopen.", "BOF records qualification evidence, missing items, review state, responsible owner, and readiness impact."],
  ["Credentials", "Track CDL, medical card, MVR, insurance, permits, and other expiration-sensitive records across drivers, carriers, and equipment. Manual calendars and email reminders become visible work with a defined follow-up.", "BOF maintains credential dates, source documents, expiration status, requests, and escalation history."],
  ["Safety", "Coordinate incidents, coaching, inspections, corrective actions, and safety evidence across the driver and equipment record. BOF supports administration and follow-through without replacing responsible safety judgment.", "BOF maintains event evidence, review notes, action owner, due date, verification, and resolution status."],
  ["Compliance", "Organize policy requirements, audit requests, renewals, document gaps, and compliance follow-up so the fleet does not reconstruct its posture during a review.", "BOF maintains requirement, evidence, review state, exception, deadline, owner, and resolution record."],
  ["Maintenance Administration", "Keep inspection, repair, service, equipment condition, and out-of-service follow-up connected to the asset that dispatch may need to assign. The administrative record stays current without claiming to perform repairs.", "BOF maintains asset status, inspection and repair documentation, open condition, assigned action, and readiness consequence."],
  ["Settlements", "Connect delivered work, proof, deductions, holds, and driver settlement inputs before payment coordination. BOF keeps the administrative closeout visible across the load and driver records.", "BOF maintains proof status, deduction context, hold reason, approval, settlement state, and next action."],
  ["Exception Management", "Identify the issue, assign responsibility, make the consequence visible, and keep the item open until resolution is verified. This is the connective work that isolated departments usually lose.", "BOF maintains exception type, severity, linked record, owner, deadline, evidence, action history, and resolution."],
] as const;

export default function OperationsCompliancePage() {
  return <main className="bof-service-page"><div className="bof-mkt-container">
    <header className="bof-service-page__hero"><p className="bof-home-eyebrow">What BOF Takes Over</p><h1>OPERATIONS &amp; COMPLIANCE</h1><p>BOF can take responsibility for the monitoring, documentation, expiration tracking, follow-up, and exception administration that keeps readiness connected to dispatch, delivery, proof, and settlement.</p></header>
    <section className="bof-service-page__section"><h2>What a 20–30 truck fleet has to build internally</h2><p>A growing fleet may need compliance, safety, settlement, maintenance, and administrative staff to keep records current and chase every open item. The work is not only checking a document; it is understanding what the record affects, who owns the next action, and whether the problem was resolved. BOF can take over that operating coordination while the fleet keeps dispatch in-house.</p></section>
    <section className="bof-service-page__section"><h2>Connected responsibilities</h2><div className="bof-service-page__items">{responsibilities.map(([title, work, records]) => <article key={title}><h3>{title}</h3><p>{work}</p><p><strong>{records}</strong></p></article>)}</div></section>
    <section className="bof-service-page__section bof-service-page__section--dark"><h2>The operating record is the connection</h2><p>A credential is not merely a document: it affects readiness. A readiness issue can affect dispatch. A dispatch event produces delivery and proof records. Proof affects settlement. An exception can affect payment, compliance, safety, or customer service. Maintenance information can affect equipment readiness and dispatch.</p><p>BOF keeps these relationships together, identifies missing or overdue work, assigns the next action, and tracks resolution so the fleet does not add separate administrative handoffs for every department as it grows.</p></section>
    <section className="bof-service-page__section"><h2>Operational outcome</h2><p>The fleet gets a maintained readiness and exception record across drivers, equipment, loads, proof, and settlement. BOF reduces the need to add internal compliance, safety, settlement, and administrative staffing for every new layer of work while keeping qualified people in control of regulated decisions.</p><div className="bof-service-page__actions"><Link href="/dashboard" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">SEE BOF IN ACTION</Link><Link href="/book-assessment?source=operations-compliance" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-secondary">FLEET ASSESSMENT</Link></div></section>
  </div></main>;
}
