import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Procurement & Savings | BackOfficeFleet", description: "Procurement coordination, vendor programs, fuel purchasing, and cost administration for growing trucking fleets." };

const responsibilities = [
  ["Fuel Discounts", "Identify fuel purchasing needs, organize participating locations and programs, and keep fuel records visible against the fleet and operating activity. BOF does not promise a particular discount or savings result.", "BOF maintains program details, eligibility context, purchasing records, supporting documents, and follow-up status."],
  ["Supply Chain", "Coordinate recurring needs for equipment, parts, supplies, and services that otherwise arrive through separate calls, emails, vendor files, and owner memory.", "BOF maintains item need, vendor, timing, approval, order status, receipt, and operating connection."],
  ["Discount Pricing", "Make available pricing information easier to compare and review so a smaller fleet can see the terms, requirements, and decision context behind a purchase.", "BOF maintains quoted pricing, effective dates, terms, source, comparison notes, and approval history."],
  ["Vendor Programs", "Organize vendor relationships, program requirements, service contacts, renewals, and performance follow-up without requiring the owner to hold every relationship personally.", "BOF maintains vendor profile, program status, contact, agreement, renewal date, issue, and next action."],
  ["Purchasing", "Turn requests from operations, maintenance, and the fleet office into a reviewable purchasing process with an owner, approval path, and record of what was ordered.", "BOF maintains request, specification, vendor, approval, purchase status, delivery, invoice, and linked asset or operation."],
  ["Cost Management", "Connect purchasing information to equipment, fuel, maintenance, and operating activity so cost review is based on records rather than an end-of-month reconstruction.", "BOF maintains cost category, source, operating reference, exception, review status, and accountable owner."],
] as const;

export default function ProcurementSavingsPage() {
  return <main className="bof-service-page"><div className="bof-mkt-container">
    <header className="bof-service-page__hero"><p className="bof-home-eyebrow">What BOF Takes Over</p><h1>PROCUREMENT &amp; SAVINGS</h1><p>BOF can organize the procurement infrastructure behind a growing fleet: fuel, supplies, vendors, purchasing requests, pricing information, and cost follow-through.</p></header>
    <section className="bof-service-page__section"><h2>What a 20–30 truck fleet has to build internally</h2><p>A fleet of this size may not have the purchasing volume, staff, or negotiating infrastructure of a larger enterprise. The owner or operations team often carries vendor calls, fuel decisions, part requests, price comparisons, receipts, and follow-up alongside dispatch and daily exceptions. BOF can take responsibility for organizing that work and may provide access to vendor programs or purchasing leverage where available, without promising a specific saving.</p></section>
    <section className="bof-service-page__section"><h2>Procurement responsibilities</h2><div className="bof-service-page__items">{responsibilities.map(([title, work, records]) => <article key={title}><h3>{title}</h3><p>{work}</p><p><strong>{records}</strong></p></article>)}</div></section>
    <section className="bof-service-page__section bof-service-page__section--dark"><h2>How purchasing connects to fleet operations</h2><p>Purchasing needs come from the operation: fuel, equipment, maintenance, supplies, and vendor services. BOF connects the vendor and pricing record to the asset, request, cost category, approval, delivery, invoice, and exception that explains what happened.</p><p>Missing approvals, expired programs, unreceived supplies, price changes, and unresolved vendor issues become visible next actions instead of scattered follow-up.</p></section>
    <section className="bof-service-page__section"><h2>Operational outcome</h2><p>The fleet gets a repeatable procurement process and a clearer record of vendor, purchasing, fuel, and cost activity. BOF can reduce the administrative burden that would otherwise push a 20–30 truck fleet toward a dedicated procurement function, while actual purchasing decisions and vendor terms remain subject to fleet approval.</p><div className="bof-service-page__actions"><Link href="/dashboard" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">SEE BOF IN ACTION</Link><Link href="/book-assessment?source=procurement-savings" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-secondary">FLEET ASSESSMENT</Link></div></section>
  </div></main>;
}
