import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { MarketingSection, MarketingSectionHeader } from "@/components/marketing";

export const metadata: Metadata = {
  title: "Fleet & Equipment | Municipal Services | BackOfficeFleet",
  description: "Administrative continuity for shared municipal assets across assignment, inspection, maintenance, readiness, exceptions, and history.",
};

const burdenDrivers = [
  ["Volume", "Every asset can generate assignment, inspection, condition, maintenance, service, incident, and completion records repeatedly."],
  ["Fragmentation", "Department files can separate evidence from the asset, leaving the next crew without the condition or action history."],
  ["Recurrence", "Preventive work, seasonal readiness, and recurring assignments create administrative work even when operations are routine."],
  ["Handoffs", "Responsibility moves among departments, supervisors, crews, and providers; an issue can be recorded without a visible owner."],
  ["Limited visibility", "Leadership must reconstruct which assets are affected, what is aging, and what action remains from scattered follow-up."],
] as const;

const administrativeModels = [
  ["Burden", "The operational volume, recurring work, and handoff pattern create the background administrative load around shared municipal assets."],
  ["Continuity", "The asset record must travel with the work so assignment, inspection, condition, maintenance, and resolution remain connected over time."],
  ["Accountability", "Every open condition needs an owner, a follow-up path, and a record of the decision or action that came next."],
  ["Visibility", "Leadership needs to see affected assets, conditions, owners, evidence, and aging work without reconstructing it manually."],
  ["Consequence", "Unresolved conditions create readiness, service, and management implications that demand follow-through and historical context."],
] as const;

const lifecycle = [
  ["Assignment", "Record the department, person, crew, service context, and responsibility for shared use."],
  ["Inspection", "Connect recurring or seasonal inspection evidence to the asset and the activity that produced it."],
  ["Condition", "Make complete, incomplete, affected, or unresolved status understandable to the next responsible team."],
  ["Maintenance", "Relate a condition to maintenance activity, supporting evidence, ownership, and follow-up."],
  ["Readiness", "Surface readiness limitations as administrative context without making the city's operational decision."],
  ["Documentation", "Preserve assignment, service, inspection, maintenance, and completion records around the asset."],
  ["Exception", "Identify missing evidence, failed inspection, unresolved condition, or unclear handoff."],
  ["Ownership", "Route the next action to the responsible department, supervisor, administrator, or designated owner."],
  ["Resolution", "Record what happened after follow-up so closure is distinguishable from an aging condition."],
  ["History", "Keep the asset's administrative story available as it moves between people, departments, and work."],
] as const;

const workflows = [
  { title: "Shared asset reassignment", trigger: "A department requests a shared vehicle, attachment, tool, or specialty unit for planned service work.", record: "The assignment connects the asset to the responsible person, crew, department, service context, and supporting condition or readiness evidence.", risk: "A handoff can become incomplete when prior condition, inspection evidence, or ownership does not move with the asset.", consequence: "The next owner sees the action path and management can understand how shared use affected later service and readiness." },
  { title: "Inspection reveals a condition", trigger: "An equipment, facility, seasonal, or service inspection identifies a failed, incomplete, or uncertain condition.", record: "The finding is connected to the affected asset, inspection activity, department, evidence, and maintenance relationship.", risk: "The condition may limit later readiness or assignment if follow-up is not owned and the supporting record is fragmented.", consequence: "The responsible team can follow up, while management sees the affected asset, open action, and eventual history." },
  { title: "Maintenance remains unresolved", trigger: "A preventive, corrective, or emergency maintenance requirement creates work that is not yet complete.", record: "The requirement, activity, completion evidence, unresolved condition, owner, and aging status remain related to the asset.", risk: "An incomplete record can make a unit appear administratively ready while the maintenance condition still requires attention.", consequence: "Management can coordinate ownership and follow-up without BOF performing repairs or deciding operational disposition." },
] as const;

const relatedDomains = [
  ["Workforce Administration", "The person or crew using the asset brings qualification, assignment history, recurring requirements, and incident context."],
  ["Maintenance & Inspection", "Conditions become administrative work when inspection evidence, maintenance activity, ownership, and resolution must stay connected."],
  ["Service Documentation", "Route-based and project work create service records that explain what the asset supported and what remains incomplete."],
  ["Safety / Incidents / Exceptions", "An incident, failed inspection, or missing record can affect people, assignments, assets, and service continuity."],
  ["Management Visibility", "Leadership needs the affected asset, responsible department, aging condition, evidence, and action history."],
] as const;

const levelThreeSubjects = [
  ["Assignment Documentation", "The record of who, which department, and what work context carried responsibility for the asset."],
  ["Inspection Documentation", "The evidence and condition trail created when recurring, facility, equipment, or seasonal inspections occur."],
  ["Maintenance Work Orders", "The administrative relationship between a maintenance requirement, activity, completion evidence, and unresolved condition."],
  ["Readiness Documentation", "The context management needs when an asset's administrative condition affects a future assignment or service plan."],
  ["Asset History", "The connected history of assignments, conditions, actions, resolutions, and use across operating boundaries."],
] as const;

export default function FleetEquipmentPage() {
  return (
    <main className="bof-mkt-root">
      <section className="relative isolate overflow-hidden bg-slate-950 text-white">
        <Image src="/assets/images/hero-government-fleets.png" alt="Municipal fleet vehicles supporting public service operations" width={1920} height={960} priority className="absolute inset-0 -z-20 h-full w-full object-cover object-center" />
        <div className="absolute inset-0 -z-10 bg-slate-950/80" />
        <div className="bof-mkt-container relative flex min-h-[25rem] items-end py-14 md:min-h-[31rem] md:py-20"><div className="max-w-4xl"><p className="text-sm font-black uppercase tracking-[0.22em] text-teal-300">Municipal Services / Level 2 domain</p><h1 className="mt-4 text-5xl font-black leading-[1.02] tracking-tight text-white md:text-7xl">Fleet &amp; Equipment</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-slate-100 md:text-2xl">The administrative record for shared municipal assets as they move through assignment, inspection, maintenance, readiness, exceptions, and history.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="/assessment/government-fleets" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">Take the municipal assessment</Link><Link href="/government/municipal-services" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-secondary">Back to Municipal Services</Link></div></div></div>
      </section>

      <MarketingSection variant="white" ariaLabelledBy="fleet-equipment-reality-heading"><div className="bof-mkt-container grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><MarketingSectionHeader titleId="fleet-equipment-reality-heading" title="A shared asset carries a shared administrative responsibility" lead="Fleet &amp; Equipment is the domain where municipal assets meet people, departments, service assignments, inspections, maintenance activity, readiness context, and historical continuity." /><div className="space-y-5 text-lg leading-8 text-slate-700"><p>Vehicles, tools, specialty equipment, seasonal attachments, and facilities equipment can move between public works, sanitation, utilities, parks, facilities, and fleet services. The physical movement is expected; the administrative ambiguity that follows it is the problem.</p><p>The next crew needs to know what the asset supported, what condition was found, what evidence exists, who owns the open action, and whether a prior issue was resolved. BOF organizes that context while the city retains field responsibility and operational command.</p></div></div></MarketingSection>

      <MarketingSection variant="light" ariaLabelledBy="fleet-equipment-burden-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-burden-heading" title="Why asset administration becomes difficult" lead="The burden is created by the pattern of municipal work, not by a lack of operational intent." /><div className="mt-10 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{burdenDrivers.map(([title, body], index) => <article key={title} className="bg-white p-5"><p className="text-sm font-black tracking-[0.18em] text-teal-700">0{index + 1}</p><h3 className="mt-3 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-700">{body}</p></article>)}</div></div></MarketingSection>

      <MarketingSection variant="white" ariaLabelledBy="fleet-equipment-models-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-models-heading" title="BOF administrative models for shared fleet work" lead="The BOF operating model is not a slogan. It is the administrative structure that keeps municipal asset work accountable and visible across handoffs." /><div className="mt-10 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{administrativeModels.map(([title, body], index) => <article key={title} className="bg-white p-5"><p className="text-sm font-black tracking-[0.18em] text-teal-700">0{index + 1}</p><h3 className="mt-3 text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-700">{body}</p></article>)}</div><div className="mt-10 rounded-2xl border border-slate-200 bg-slate-50 p-6"><p className="text-xs font-black uppercase tracking-[0.2em] text-slate-500">Relationship chain</p><div className="mt-5 flex flex-wrap gap-3 text-sm font-black text-slate-900"><span className="rounded-full border border-slate-200 bg-white px-3 py-2">People</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Assets</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Work</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Records</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Exceptions</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Accountability</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Continuity</span><span className="text-slate-400">→</span><span className="rounded-full border border-slate-200 bg-white px-3 py-2">Visibility</span></div><p className="mt-4 text-base leading-7 text-slate-700">This is the administrative progression a shared municipal asset creates: the people who use it, the asset itself, the work being performed, the records created, the exceptions that appear, the accountability that follows, the continuity that preserves the history, and the visibility leadership needs to govern the work.</p></div></div></MarketingSection>

      <MarketingSection variant="white" ariaLabelledBy="fleet-equipment-lifecycle-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-lifecycle-heading" title="The asset administrative lifecycle" lead="Each stage answers a different question. Taken together, they show the full movement from trigger to record to condition to owner to follow-up to resolution to historical continuity." /><div className="mt-10 grid gap-px overflow-hidden border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{lifecycle.map(([stage, description], index) => <article key={stage} className="bg-white p-5"><p className="text-sm font-black tracking-[0.18em] text-teal-700">0{index + 1}</p><h3 className="mt-3 text-xl font-black text-slate-950">{stage}</h3><p className="mt-3 text-base leading-7 text-slate-700">{description}</p></article>)}</div><p className="mt-8 max-w-4xl text-lg leading-8 text-slate-700">The operational logic is simple but required: trigger → record → condition → owner → follow-up → resolution → history. BOF preserves that chain without collapsing the asset into a single record or losing the context of the work.</p></div></MarketingSection>

      <MarketingSection variant="light" ariaLabelledBy="fleet-equipment-workflows-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-workflows-heading" title="Three workflows where the record is tested" lead="The domain becomes valuable when a shared asset changes hands, a condition appears, or an action remains unresolved." /><div className="mt-10 space-y-7">{workflows.map((workflow, index) => <article key={workflow.title} className="grid gap-6 border-t-2 border-slate-300 pt-6 lg:grid-cols-[18rem_1fr] lg:gap-12"><div><p className="text-sm font-black uppercase tracking-[0.18em] text-teal-700">Workflow 0{index + 1}</p><h3 className="mt-3 text-3xl font-black text-slate-950">{workflow.title}</h3></div><div className="grid gap-5 text-lg leading-8 text-slate-700 md:grid-cols-2"><p><strong className="text-slate-950">Trigger:</strong> {workflow.trigger}</p><p><strong className="text-slate-950">Administrative record:</strong> {workflow.record}</p><p><strong className="text-slate-950">Condition and handoff:</strong> {workflow.risk}</p><p><strong className="text-slate-950">Ownership and consequence:</strong> {workflow.consequence} The owner can follow up and document resolution for historical continuity.</p></div></article>)}</div></div></MarketingSection>

      <MarketingSection variant="ink" ariaLabelledBy="fleet-equipment-consequence-heading"><div className="bof-mkt-container grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><div><p className="text-sm font-black uppercase tracking-[0.22em] text-teal-300">Exceptions, accountability, and consequence</p><h2 id="fleet-equipment-consequence-heading" className="mt-4 text-4xl font-black leading-tight text-white md:text-5xl">An unresolved asset condition is more than a missing record</h2><p className="mt-5 text-lg leading-8 text-slate-300">A failed inspection, incomplete maintenance record, or unclear assignment can affect the next service plan, readiness context, ownership, and cross-department continuity. BOF identifies and routes the administrative work; it does not perform repairs or decide operational disposition.</p></div><div className="space-y-5 border-l-2 border-amber-400 pl-6 text-lg font-bold leading-8 text-white"><p>Administrative condition: incomplete inspection record.</p><p>Operational consequence: readiness uncertainty for a future assignment.</p><p>Management action: see the affected asset, owner, evidence, aging, and required follow-up.</p><p className="border-t border-white/15 pt-5 text-base font-normal leading-7 text-slate-300">Accountability means ownership, routing, follow-up, aging, resolution, and historical visibility, not merely recording that a condition once existed.</p></div></div></MarketingSection>

      <MarketingSection variant="white" ariaLabelledBy="fleet-equipment-layer-heading"><div className="bof-mkt-container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><MarketingSectionHeader titleId="fleet-equipment-layer-heading" title="BOF connects the asset record to the rest of the operation" lead="People → assets → work → records → exceptions → accountability → continuity → management visibility." /><div className="space-y-5 text-lg leading-8 text-slate-700"><p>The asset is not an isolated module. Workforce administration explains who is responsible. Maintenance and inspection explain the condition. Service documentation explains the work. Safety, incidents, and exceptions explain what needs attention. Management visibility explains the broader effect and next action.</p><p>That is the BOF operating-layer view for Fleet &amp; Equipment: one administrative story around shared municipal work, without claiming to replace specialized fleet, maintenance, HR, accounting, or ERP systems.</p></div></div></MarketingSection>

      <MarketingSection variant="light" ariaLabelledBy="fleet-equipment-related-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-related-heading" title="Where Fleet &amp; Equipment connects" lead="These relationships show how the domain intersects with the other Municipal Services subjects. Dedicated pages for those domains have not been created." /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{relatedDomains.map(([title, body]) => <article key={title} className="border border-slate-200 bg-white p-6"><h3 className="text-xl font-black text-slate-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-700">{body}</p><p className="mt-4 text-sm font-black uppercase tracking-[0.16em] text-slate-500">Level 2 relationship</p></article>)}</div></div></MarketingSection>

      <MarketingSection variant="white" ariaLabelledBy="fleet-equipment-subjects-heading"><div className="bof-mkt-container"><MarketingSectionHeader titleId="fleet-equipment-subjects-heading" title="Fleet &amp; Equipment — Deeper Administrative Subjects" lead="These Level 3 gateways show where the domain will go next. They are architectural subjects only; no Level 3 routes are created yet." /><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{levelThreeSubjects.map(([title, description], index) => <article key={title} className="border-l-4 border-amber-400 bg-slate-50 p-6"><p className="text-sm font-black tracking-[0.18em] text-teal-700">0{index + 1}</p><h3 className="mt-3 text-2xl font-black text-slate-950">{title}</h3><p className="mt-3 text-base leading-7 text-slate-700">{description}</p><p className="mt-4 text-sm leading-6 text-slate-600"><strong className="text-slate-900">Relationship:</strong> This subject deepens the Fleet &amp; Equipment administrative record and leads to the operational workflow logic the city must resolve next.</p></article>)}</div><p className="mt-8 max-w-4xl text-lg leading-8 text-slate-700">A Level 3 page would not flatten this domain into a summary. It would fully traverse the operational workflow lifecycle: trigger → record → condition → owner → follow-up → resolution → history, with each exception and handoff preserving accountability and continuity.</p></div></MarketingSection>

      <MarketingSection variant="ink" ariaLabelledBy="fleet-equipment-cta-heading"><div className="bof-mkt-container flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-3xl"><p className="text-sm font-black uppercase tracking-[0.22em] text-teal-300">Next step</p><h2 id="fleet-equipment-cta-heading" className="mt-4 text-4xl font-black leading-tight text-white md:text-5xl">See where shared assets create administrative work in your city.</h2><p className="mt-5 text-lg leading-8 text-slate-300">Take the existing Municipal Assessment to examine assignments, inspection evidence, maintenance follow-up, readiness context, exceptions, ownership, and history.</p></div><Link href="/assessment/government-fleets" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">Take the municipal assessment</Link></div></MarketingSection>
    </main>
  );
}