import type { IntakeWizardState } from "@/lib/load-requirements-intake-types";

export const WIZARD_SHIP_DRAFT_ID = "SHIP-INTAKE-DRAFT";
export const WIZARD_FAC_DRAFT_ID = "FAC-INTAKE-DRAFT";
export const WIZARD_LR_DRAFT_ID = "LR-INTAKE-DRAFT";
export const WIZARD_REQ_DRAFT_ID = "CR-INTAKE-DRAFT";

/** Blank wizard state used by load intake and intake-engine prefill. */
export function createLoadIntakeWizardState(): IntakeWizardState {
  return {
    lastDraftSavedAt: null,
    shipper: {
      shipper_id: WIZARD_SHIP_DRAFT_ID,
      shipper_name: "",
      primary_contact_name: "",
      primary_contact_email: "",
      primary_contact_phone: "",
    },
    facility: {
      facility_id: WIZARD_FAC_DRAFT_ID,
      shipper_id: WIZARD_SHIP_DRAFT_ID,
      facility_name: "",
      address: "",
      city: "",
      state: "",
      zip: "",
      facility_rules: "",
      appointment_required: false,
    },
    loadRequirement: {
      load_requirement_id: WIZARD_LR_DRAFT_ID,
      shipper_id: WIZARD_SHIP_DRAFT_ID,
      facility_id: WIZARD_FAC_DRAFT_ID,
      load_id_input: "",
      pickup_at: "",
      delivery_at: "",
      commodity: "",
      weight: 0,
      pallet_count: 0,
      piece_count: 0,
      rate_linehaul: 0,
      assigned_driver_id: "",
      truck_id: "",
      trailer_id: "",
      intake_status: "scheduled",
      bol_number: "",
      invoice_number: "",
      seal_number: "",
      rfid_proof_required: false,
      insurance_requirements_summary: "",
      pod_bol_instructions: "",
      backhaul_pay: 0,
      claim_damage_flag: false,
      equipment_type: "",
      special_handling: "",
      destination_facility_name: "",
      destination_address: "",
      destination_city: "",
      destination_state: "",
      destination_zip: "",
      route_memory_key: "",
      temperature_required: false,
      temperature_min: undefined,
      temperature_max: undefined,
    },
    compliance: {
      requirement_id: WIZARD_REQ_DRAFT_ID,
      load_requirement_id: WIZARD_LR_DRAFT_ID,
      seal_required: false,
      seal_number_required: false,
      pickup_photos_required: false,
      delivery_photos_required: false,
      cargo_photos_required: false,
      insuranceRequirementType: "Standard COI",
      cargoCoverageLevel: "$250k",
      certificateRequired: true,
      additionalInsuredRequired: false,
      facilityEndorsementRequired: false,
      bolRequirementType: "Standard shipper BOL",
      signedBolRequired: true,
      palletCountRequired: true,
      pieceCountRequired: true,
      sealNotationRequired: false,
      bolSpecialInstructions: "",
      podRequirementType: "POD + photo evidence",
      signedPodRequired: true,
      receiverPrintedNameRequired: true,
      deliveryPhotoRequired: true,
      emptyTrailerPhotoRequired: false,
      sealVerificationRequired: false,
      gpsTimestampRequired: true,
      podSpecialInstructions: "",
      insurance_requirements: "",
      appointment_window_start: "",
      appointment_window_end: "",
      bol_instructions: "",
      pod_requirements: "",
      accessorial_rules: "",
      lumper_expected: false,
    },
    loadPacket: null,
  };
}
