import type { IntakeRecord } from "@/lib/intake-engine-types";

const MOCK_PREVIEW = "/mocks/mock_bol.pdf";

export const INTAKE_ENGINE_SEED: IntakeRecord[] = [
  {
    intake_id: "IN-001",
    source_type: "email",
    source_sender: "tenders@acme-distribution.example",
    subject_line: "RE: PRO-512 / Cleveland → Memphis — signed rate confirmation",
    received_at: "2026-04-22T14:05:00.000Z",
    intake_kind: "single_trip",
    status: "ready_for_approval",
    match_confidence: "high",
    needs_review: false,
    missing_items: [],
    extraction_confidence: "high",
    flagged_fields: [],
    linked_driver_id: null,
    linked_load_id: "L008",
    review_notes: "",
    pricing_summary: "Linehaul $2,450 · Fuel surcharge included",
    insurance_requirements: "Standard COI · $1M auto liability",
    bol_requirements: "Shipper BOL template · seal notation",
    pod_requirements: "Signed POD · delivery photos if OS&D",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-001-1",
        file_name: "Rate_Confirmation_PRO-512.pdf",
        doc_classification: "rate_confirmation",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
      {
        attachment_id: "ATT-001-2",
        file_name: "Acme_lane_rules.pdf",
        doc_classification: "unknown_mixed",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "Acme Distribution",
      load_number: "PRO-512",
      pickup_facility: "Acme Distribution",
      pickup_city: "Cleveland",
      pickup_state: "OH",
      delivery_facility: "Cleveland Receiver",
      delivery_city: "Memphis",
      delivery_state: "TN",
      pickup_date: "2026-04-24",
      delivery_date: "2026-04-26",
      rate_linehaul: 2450,
      equipment: "Dry van",
      doc_type_label: "Rate confirmation packet",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-002",
    source_type: "email",
    source_sender: "routing@metro-fulfillment.example",
    subject_line: "FW: Weekly dedicated — 3 turns (Chicago ↔ Dallas)",
    received_at: "2026-04-22T09:40:00.000Z",
    intake_kind: "multi_trip",
    status: "needs_review",
    match_confidence: "medium",
    needs_review: true,
    missing_items: ["Trip 2 — receiver appointment not confirmed"],
    extraction_confidence: "medium",
    flagged_fields: ["proposed_trips[1].delivery"],
    review_reason: "Second consignee window conflicts with prior tender version.",
    linked_driver_id: null,
    linked_load_id: null,
    review_notes: "Planner to confirm Dallas window before finalize.",
    pricing_summary: "3 × linehaul (see trip rows)",
    insurance_requirements: "Enhanced COI · additional insured",
    bol_requirements: "Multi-stop BOL · piece count per stop",
    pod_requirements: "Per-stop POD bundle",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-002-1",
        file_name: "Metro_batch_routing.pdf",
        doc_classification: "rate_confirmation",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "Metro Fulfillment",
      load_number: "MF-BATCH-04-22",
      doc_type_label: "Multi-trip routing package",
      notes: "Dedicated fleet — three paid turns.",
    },
    proposed_trips: [
      {
        trip_id: "TRP-002-1",
        row_number: 1,
        pickup: "Metro Fulfillment - Chicago, IL",
        delivery: "NorthStar Paper - Dallas, TX",
        rate: 3100,
        missing_items: [],
        trip_status: "approved",
      },
      {
        trip_id: "TRP-002-2",
        row_number: 2,
        pickup: "NorthStar Paper - Dallas, TX",
        delivery: "Lakeside Grocery - Dallas, TX",
        rate: 890,
        missing_items: ["Receiver appointment not confirmed"],
        trip_status: "pending",
      },
      {
        trip_id: "TRP-002-3",
        row_number: 3,
        pickup: "Lakeside Grocery - Dallas, TX",
        delivery: "Metro Fulfillment - Chicago, IL",
        rate: 2750,
        missing_items: [],
        trip_status: "pending",
      },
    ],
  },
  {
    intake_id: "IN-003",
    source_type: "upload",
    source_sender: "portal.upload@bof.local",
    subject_line: "Upload: BOL + POD — L006 delivery",
    received_at: "2026-04-21T18:22:00.000Z",
    intake_kind: "load_document",
    status: "needs_review",
    match_confidence: "high",
    needs_review: true,
    missing_items: ["Lumper receipt not attached (shipper rule)"],
    extraction_confidence: "high",
    flagged_fields: [],
    linked_driver_id: null,
    linked_load_id: "L006",
    review_notes: "",
    pricing_summary: "—",
    insurance_requirements: "Per load file L006",
    bol_requirements: "Signed BOL on file",
    pod_requirements: "POD with seal photo",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-003-1",
        file_name: "BOL_L006_signed.pdf",
        doc_classification: "bill_of_lading",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
      {
        attachment_id: "ATT-003-2",
        file_name: "POD_L006_scan.pdf",
        doc_classification: "proof_of_delivery",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "Rapid Parts",
      load_number: "L006",
      doc_type_label: "BOL / POD packet",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-004",
    source_type: "email",
    source_sender: "compliance@bof-carrier.example",
    subject_line: "Medical card renewal — John Carter (DRV-001)",
    received_at: "2026-04-22T11:00:00.000Z",
    intake_kind: "driver_document",
    status: "ready_for_approval",
    match_confidence: "high",
    needs_review: false,
    missing_items: [],
    extraction_confidence: "high",
    flagged_fields: [],
    linked_driver_id: "DRV-001",
    linked_load_id: null,
    review_notes: "",
    pricing_summary: "—",
    readiness_impact: "clears_block",
    insurance_requirements: "—",
    bol_requirements: "—",
    pod_requirements: "—",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-004-1",
        file_name: "MCSA_med_card_Carter.pdf",
        doc_classification: "medical_card",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "BOF Carrier Ops",
      doc_type_label: "Medical examiner certificate",
      credential_type: "DOT medical card",
      expiration_detected: "2028-03-14",
      notes: "Matched to John Carter via DL# tail and name.",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-005",
    source_type: "email",
    source_sender: "dock.supervisor@union-crossdock.example",
    subject_line: "Fwd: handwritten gate note — seal change",
    received_at: "2026-04-20T16:48:00.000Z",
    intake_kind: "load_document",
    status: "needs_review",
    match_confidence: "low",
    needs_review: true,
    missing_items: ["Receiver note partially legible — review required"],
    extraction_confidence: "low",
    flagged_fields: ["extracted.notes", "extracted.pickup_date"],
    review_reason:
      "Handwritten appointment note detected — low confidence. Receiver note partially legible — review required.",
    linked_driver_id: null,
    linked_load_id: "L004",
    review_notes: "",
    pricing_summary: "—",
    insurance_requirements: "Standard",
    bol_requirements: "Seal change callout per gate log",
    pod_requirements: "Timestamped photos at receiver",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-005-1",
        file_name: "Gate_note_scan.jpg",
        doc_classification: "unknown_mixed",
        attachment_status: "needs_review",
        preview_url: "/mocks/mock_equipment.jpg",
      },
    ],
    extracted: {
      customer_or_broker: "Union Crossdock",
      load_number: "L004 (?)",
      pickup_date: "2026-04-21 (uncertain)",
      notes:
        "Handwritten text: 'Reseal bay 4 — call receiver before 06:00' — OCR confidence 42%.",
      doc_type_label: "Scanned facility / incident note",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-006",
    source_type: "internal",
    source_sender: "claims@bof.local",
    subject_line: "Claim support packet — seal variance L001",
    received_at: "2026-04-19T10:15:00.000Z",
    intake_kind: "claim_document",
    status: "new",
    match_confidence: "high",
    needs_review: false,
    missing_items: [],
    extraction_confidence: "high",
    flagged_fields: [],
    linked_driver_id: "DRV-001",
    linked_load_id: "L001",
    review_notes: "",
    pricing_summary: "Claim reserve TBD",
    insurance_requirements: "Carrier GL + cargo filings",
    bol_requirements: "Executed BOL copies",
    pod_requirements: "Photo evidence bundle",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-006-1",
        file_name: "Claim_photo_bundle.zip",
        doc_classification: "claim_support",
        attachment_status: "received",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "Prime Consumer",
      load_number: "L001",
      doc_type_label: "Claim support",
      notes: "Correlate seal IDs with RFID dock readouts.",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-007",
    source_type: "email",
    source_sender: "ap@blueline-retail.example",
    subject_line: "INV-88442 + accessorial schedule",
    received_at: "2026-04-22T08:00:00.000Z",
    intake_kind: "billing_document",
    status: "ready_for_approval",
    match_confidence: "high",
    needs_review: false,
    missing_items: [],
    extraction_confidence: "high",
    flagged_fields: [],
    linked_driver_id: null,
    linked_load_id: "L003",
    review_notes: "",
    pricing_summary: "Invoice total $3,180 · detention line flagged for review",
    insurance_requirements: "—",
    bol_requirements: "—",
    pod_requirements: "—",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-007-1",
        file_name: "INV-88442.pdf",
        doc_classification: "invoice",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "BlueLine Retail",
      load_number: "L003",
      rate_linehaul: 3180,
      doc_type_label: "Invoice / billing packet",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-008",
    source_type: "email",
    source_sender: "ops@midwest-foods.example",
    subject_line: "New lane tender — single pickup Nashville",
    received_at: "2026-04-23T07:12:00.000Z",
    intake_kind: "single_trip",
    status: "new",
    match_confidence: "medium",
    needs_review: false,
    missing_items: ["Temperature range not specified on tender"],
    extraction_confidence: "medium",
    flagged_fields: [],
    linked_driver_id: null,
    linked_load_id: null,
    review_notes: "",
    pricing_summary: "Linehaul $1,980 (reefer assumed)",
    insurance_requirements: "Reefer cargo · temp log required",
    bol_requirements: "Shipper BOL",
    pod_requirements: "Reefer download",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-008-1",
        file_name: "Tender_MW-NASH-0423.pdf",
        doc_classification: "rate_confirmation",
        attachment_status: "parsed",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "Midwest Foods",
      load_number: "MW-NASH-0423",
      pickup_facility: "Midwest Foods",
      pickup_city: "Nashville",
      pickup_state: "TN",
      delivery_facility: "Delta Retail DC",
      delivery_city: "Atlanta",
      delivery_state: "GA",
      pickup_date: "2026-04-28",
      delivery_date: "2026-04-29",
      rate_linehaul: 1980,
      equipment: "Reefer",
      doc_type_label: "Lane tender",
    },
    proposed_trips: [],
  },
  {
    intake_id: "IN-009",
    source_type: "upload",
    source_sender: "hr.upload@bof-carrier.example",
    subject_line: "MVR pull — Maria Lopez (renewal window)",
    received_at: "2026-04-21T13:10:00.000Z",
    intake_kind: "driver_document",
    status: "needs_review",
    match_confidence: "medium",
    needs_review: true,
    missing_items: ["State pull watermark faint on page 2"],
    extraction_confidence: "medium",
    flagged_fields: ["attachments[0].file_name"],
    review_reason: "Scanned state MVR — verify pull date against carrier policy.",
    linked_driver_id: "DRV-002",
    linked_load_id: null,
    review_notes: "",
    pricing_summary: "—",
    readiness_impact: "expiring_soon",
    insurance_requirements: "—",
    bol_requirements: "—",
    pod_requirements: "—",
    finalized_at: null,
    derived_load_ids: [],
    attachments: [
      {
        attachment_id: "ATT-009-1",
        file_name: "MVR_Lopez_state_pull.pdf",
        doc_classification: "mvr",
        attachment_status: "needs_review",
        preview_url: MOCK_PREVIEW,
      },
    ],
    extracted: {
      customer_or_broker: "BOF Safety / HR",
      doc_type_label: "Motor vehicle record",
      credential_type: "MVR",
      expiration_detected: "2026-06-01 (estimated)",
      notes: "Driver Maria Lopez · home terminal Nashville area.",
    },
    proposed_trips: [],
  },
];
