import type { Driver, SafetyEvent } from "@/types/safety";

/** Mock drivers — diverse compliance, terminals, ack/qual states. */
export function createSafetySeedDrivers(): Driver[] {
  return [
    {
      driver_id: "DRV-S01",
      name: "Jordan Blake",
      status: "Active",
      home_terminal: "Cleveland, OH",
      compliance_status: "VALID",
      cdl_expiration_date: "2028-04-12",
      med_card_expiration_date: "2027-11-01",
      mvr_expiration_date: "2026-12-15",
      qual_file_status: "Complete",
      safety_ack_status: "Signed",
    },
    {
      driver_id: "DRV-S02",
      name: "Maria Santos",
      status: "Active",
      home_terminal: "Chicago, IL",
      compliance_status: "EXPIRED",
      cdl_expiration_date: "2024-02-01",
      med_card_expiration_date: "2027-06-10",
      mvr_expiration_date: "2026-09-30",
      qual_file_status: "Complete",
      safety_ack_status: "Signed",
    },
    {
      driver_id: "DRV-S03",
      name: "Alex Nguyen",
      status: "Active",
      home_terminal: "Columbus, OH",
      compliance_status: "EXPIRING_SOON",
      cdl_expiration_date: "2027-03-20",
      med_card_expiration_date: "2026-05-10",
      mvr_expiration_date: "2027-01-22",
      qual_file_status: "Incomplete",
      safety_ack_status: "Pending",
    },
    {
      driver_id: "DRV-S04",
      name: "Priya Shah",
      status: "Active",
      home_terminal: "Dallas, TX",
      compliance_status: "VALID",
      cdl_expiration_date: "2027-09-01",
      med_card_expiration_date: "2027-08-15",
      mvr_expiration_date: "2024-11-30",
      qual_file_status: "Complete",
      safety_ack_status: "Signed",
    },
    {
      driver_id: "DRV-S05",
      name: "Kenji Okada",
      status: "Inactive",
      home_terminal: "Atlanta, GA",
      compliance_status: "VALID",
      cdl_expiration_date: "2028-01-10",
      med_card_expiration_date: "2027-04-20",
      mvr_expiration_date: "2026-11-05",
      qual_file_status: "Incomplete",
      safety_ack_status: "Pending",
    },
  ];
}

export function createSafetySeedEvents(): SafetyEvent[] {
  return [
    {
      event_id: "EVT-S01",
      driver_id: "DRV-S01",
      driver_name: "Jordan Blake",
      event_type: "Hard braking — customer complaint",
      severity: "High",
      event_date: "2026-04-12T14:30:00",
      status: "Open",
      notes: "Broker flagged harsh event near receiver; video requested.",
      linked_load_id: "L002",
      evidence_image_url: "/mocks/mock_equipment.jpg",
      insurance_claim_needed: false,
      estimated_claim_exposure: 0,
    },
    {
      event_id: "EVT-S02",
      driver_id: "DRV-S02",
      driver_name: "Maria Santos",
      event_type: "Dock strike — trailer damage",
      severity: "Critical",
      event_date: "2026-04-10T09:15:00",
      status: "Open",
      notes: "Seal intact; receiver claims impact during blind-side back.",
      linked_load_id: "L001",
      evidence_image_url: "/mocks/mock_cargo.jpg",
      insurance_claim_needed: true,
      estimated_claim_exposure: 42500,
    },
    {
      event_id: "EVT-S03",
      driver_id: "DRV-S03",
      driver_name: "Alex Nguyen",
      event_type: "HOS soft violation — unassigned driving",
      severity: "Medium",
      event_date: "2026-04-08T22:00:00",
      status: "In Review",
      notes: "ELD gap 47 minutes; driver statement pending.",
      linked_load_id: "L005",
      evidence_image_url: null,
      insurance_claim_needed: false,
      estimated_claim_exposure: 0,
    },
    {
      event_id: "EVT-S04",
      driver_id: "DRV-S04",
      driver_name: "Priya Shah",
      event_type: "Yard speed — geofence alert",
      severity: "Low",
      event_date: "2026-03-28T16:45:00",
      status: "Reviewed",
      notes: "Verified yard limit; coaching logged.",
      internal_notes: "Safety reviewed 4/1 — no further action.",
      linked_load_id: undefined,
      evidence_image_url: null,
      insurance_claim_needed: false,
      estimated_claim_exposure: 0,
    },
    {
      event_id: "EVT-S05",
      driver_id: "DRV-S01",
      driver_name: "Jordan Blake",
      event_type: "Pre-trip photo incomplete",
      severity: "Low",
      event_date: "2026-03-15T07:00:00",
      status: "Closed",
      notes: "Driver re-submitted; closed by terminal manager.",
      linked_load_id: "L003",
      evidence_image_url: "/mocks/mock_seal.jpg",
      insurance_claim_needed: false,
      estimated_claim_exposure: 0,
    },
  ];
}
