import type { VaultLevelTwoConfig } from "@/components/marketing/MarketingVaultLevelTwo";

export const recordsDocumentation: VaultLevelTwoConfig = {
  slug: "records-documentation",
  domain: "Records & Documentation",
  title: "Records & Documentation",
  description: "The administrative domain that turns a driver's scattered professional documents into an organized, current, retrievable, and historically understandable record.",
  realityTitle: "A professional record is more than a folder of files",
  realityLead: "Records & Documentation controls what exists, what it represents, who it belongs to, how current it is, and how it can be found or explained later.",
  reality: [
    "A CDL, medical certificate, MVR, training record, certification, employment document, or supporting credential may arrive through email, a phone camera, a paper file, an employer portal, a scanned folder, or a disconnected database. Each location can hold a copy, but none of them alone explains which document belongs to the driver, which version is current, or what evidence supports it.",
    "BOF creates continuity around the driver's record without turning the Vault into an employer's file cabinet. The driver remains the center and source of the professional record. Employers can receive appropriate documentation for legitimate qualification or hiring work, while the driver retains a maintained record that can move from Employer A to Employer B to Employer C.",
  ],
  mechanicsTitle: "The mechanics of a durable record",
  mechanicsLead: "Every document carries administrative meaning that must remain connected instead of being reduced to an upload timestamp.",
  mechanics: [
    ["Identity", "Preserve the document's identity, source, type, driver association, and relationship to a professional qualification."],
    ["Dates", "Record effective dates, expiration dates, issue context, and the dates that determine whether attention is required."],
    ["Status", "Distinguish current, missing, duplicate, superseded, expired, pending review, and otherwise unresolved conditions."],
    ["Review", "Keep completeness, legibility, supporting evidence, and review activity visible without claiming that every document is independently certifiable."],
    ["Availability", "Make the appropriate current record retrievable for the driver or an authorized employer process while preserving its history."],
  ],
  lifecycleTitle: "Document to preserved record",
  lifecycleLead: "The lifecycle shows how a file becomes an accountable professional record rather than an isolated attachment.",
  lifecycle: [
    ["Document", "A driver submits or transfers a professional document or supporting evidence."],
    ["Classification", "BOF identifies the document type, purpose, source, and relevant credential relationship."],
    ["Association", "The record is connected to the driver and the qualification or professional context it supports."],
    ["Status", "Dates and administrative conditions establish whether the record is current, missing, expired, or superseded."],
    ["Review", "A reviewer can assess completeness, legibility, consistency, and whether further evidence is needed."],
    ["Verification", "An authorized process can record supported verification outcomes without BOF becoming the regulator."],
    ["Availability", "The driver can retrieve appropriate documentation for a legitimate employer or qualification process."],
    ["History", "Replacements, status changes, and prior versions remain explainable instead of disappearing."],
  ],
  workflowsTitle: "Three record workflows",
  workflowsLead: "These examples show how records move through the domain and where administrative responsibility must remain visible.",
  workflows: [
    { title: "New credential intake", starting: "A driver receives a renewed medical certificate or certification and submits a scan or image.", record: "The document, source, type, driver association, effective dates, and supporting qualification context.", actors: "The driver submits; BOF organizes the record; an authorized reviewer may inspect the submission; an employer may later request appropriate evidence.", exception: "The image is incomplete, unreadable, duplicated, or missing a required page.", ownership: "The driver owns supplying a usable replacement; BOF preserves the condition and routes the next review step.", history: "The original submission and its outcome remain connected to the accepted or replacement record." },
    { title: "Superseded document retrieval", starting: "A prospective employer asks why the current credential differs from a document previously used in a qualification process.", record: "The current document, prior version, replacement relationship, dates, and the reason the older record was superseded.", actors: "The driver provides context; BOF makes the chain retrievable; the employer applies its own qualification rules.", exception: "Two versions appear current or the source of one copy cannot be established.", ownership: "The unresolved identity or source question is assigned for clarification before the record is represented as settled.", history: "The older version remains visible as historical context rather than being silently overwritten." },
    { title: "Scattered record reconciliation", starting: "A driver has copies across email, a phone, paper files, an employer portal, and a scanned folder.", record: "Candidate documents are classified, compared, associated, deduplicated, and given an explicit status.", actors: "The driver supplies access or copies; BOF organizes and records relationships; authorized reviewers resolve questions.", exception: "A duplicate or conflicting copy cannot be confidently identified as the current source.", ownership: "The driver or designated reviewer owns the clarification; the unresolved state remains visible until resolved.", history: "The reconciliation decision explains what was retained, what was superseded, and why the current record is trusted." },
  ],
  exceptionsTitle: "When the record is incomplete, the gap becomes work",
  exceptionsLead: "Records administration fails when a missing page or uncertain version looks like a complete record. BOF keeps the condition visible and actionable.",
  exceptions: [
    "A missing, duplicate, expired, or questionable document is not treated as a silent absence. The condition is tied to the driver, the affected credential, the evidence available, the owner of the next step, and the date of follow-up.",
    "Accountability stays with the correct actor. The driver may need to provide a replacement; a reviewer may need to assess evidence; an employer may need to request or interpret documentation for its own process. BOF records the path without taking ownership of the employer's decision.",
    "Until resolved, the record can remain incomplete or not ready to share. That status prevents a management view from confusing an uploaded file with a usable professional record.",
  ],
  continuityTitle: "Continuity preserves the record behind the current file",
  continuityLead: "The newest document is useful only when the record can explain what it replaced and how it became current.",
  continuity: [
    "The driver may change employers, fleets, or operating environments. The professional record does not restart with each transition. Its associations, dates, review outcomes, replacements, and unresolved questions remain connected to the driver.",
    "This is how the Vault differs from an employer's Operations File Cabinet. The File Cabinet preserves the organization's operating records. The Vault preserves the driver's portable professional documentation and the history needed to understand the current state.",
  ],
  consequenceTitle: "A documentation condition has a professional consequence",
  consequenceLead: "Management needs to see what the record condition means, what action is due, and what remains unresolved.",
  condition: "A current credential has an unreadable page and its prior version is superseded.",
  consequence: "The driver may be unable to provide a complete qualification package on time.",
  action: "Assign replacement evidence, preserve the exception, and show readiness only after review.",
  levelThreeTitle: "Records & Documentation — Future Level 3 subjects",
  levelThreeLead: "These are the deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Record Indexing", "How document identity, type, driver association, source, and qualification context become a findable index."],
    ["Record Retrieval", "How an authorized person finds the appropriate current record without losing historical context."],
    ["Record Lifecycle", "How intake, classification, status, review, replacement, availability, and archival states are managed."],
    ["Record Metadata", "How dates, source, evidence, status, ownership, and relationships give a file administrative meaning."],
    ["Record Audit", "How the record shows changes, decisions, access context, unresolved questions, and accountability over time."],
  ],
  ctaTitle: "Build a professional record that can be understood later",
  ctaLead: "The BOF Vault assessment helps identify where documents, status, review, retrieval, and history are breaking down today.",
};

export const continuityHistory: VaultLevelTwoConfig = {
  slug: "continuity-history",
  domain: "Continuity & History",
  title: "Continuity & History",
  description: "The administrative domain that explains what happened to the driver's record, when it happened, why it changed, and what remains current now.",
  realityTitle: "Current state is not the whole record",
  realityLead: "Continuity & History controls the chain between the record that exists today and the events, replacements, status changes, and employment transitions that produced it.",
  reality: [
    "Simply storing the newest credential is insufficient. A current document may have replaced an expired certificate, corrected an inconsistent record, followed a verification question, or arrived after an employer transition. Without the historical chain, a reviewer sees a file but not the explanation behind its current state.",
    "The driver can move from Employer A to Employer B to Employer C while the professional record remains connected to the driver. The Vault preserves enough history to show what existed, what changed, when it changed, why it changed, what replaced it, what verification occurred, and what remains relevant.",
  ],
  mechanicsTitle: "The mechanics of continuity",
  mechanicsLead: "History is useful when each event explains a meaningful change in the record rather than becoming an unstructured activity log.",
  mechanics: [
    ["Current state", "Represent what is true now: current, expired, pending review, superseded, incomplete, or ready for an authorized use."],
    ["Historical event", "Preserve an upload, replacement, review, verification, status change, employer transition, or correction with its timing."],
    ["Relationship", "Connect a new document or status to the prior record it replaces, updates, clarifies, or leaves unresolved."],
    ["Reason", "Capture why the record changed, including renewal, correction, expiration, employer handoff, or verification outcome."],
    ["Accountability", "Keep the actor, next action, decision context, and follow-up visible across time and organizational boundaries."],
  ],
  lifecycleTitle: "From event to coherent history",
  lifecycleLead: "The continuity lifecycle separates the current answer from the events that make that answer explainable.",
  lifecycle: [
    ["Existing record", "Start with the current professional document, status, and known relationships."],
    ["Change event", "Record the upload, replacement, expiration, review, correction, or employment transition."],
    ["Comparison", "Relate the changed item to what existed before and identify what is different."],
    ["Reason", "Preserve why the change occurred and who supplied or recorded the information."],
    ["Status update", "Update current state without deleting the historical state that came before it."],
    ["Verification history", "Connect review or verification activity to the version and evidence considered at that time."],
    ["Continuity check", "Confirm the record remains associated with the driver through employer or fleet transition."],
    ["Management view", "Show current condition, aging, open action, and the history needed to interpret them."],
  ],
  workflowsTitle: "Three continuity workflows",
  workflowsLead: "These workflows show why continuity is an administrative control, not a decorative audit trail.",
  workflows: [
    { title: "Credential replacement", starting: "A driver submits a renewed credential after the prior credential is approaching expiration.", record: "The new document, prior version, effective and expiration dates, source, and replacement relationship.", actors: "The driver submits; BOF records the transition; a reviewer or authorized verifier may assess the new evidence.", exception: "The new document has a date conflict or the prior version cannot be matched confidently.", ownership: "The driver supplies clarification or corrected evidence; the reviewer records the outcome; BOF preserves the open question until closure.", history: "The prior credential remains historical, and the reason the new record became current is visible." },
    { title: "Employer transition", starting: "The driver leaves Employer A and begins a qualification process with Employer B.", record: "The driver's existing documents, current statuses, prior review context, and the event marking the employer transition.", actors: "The driver carries the record; Employer B requests appropriate documentation; BOF maintains relationships without transferring ownership.", exception: "Employer B requires evidence not present or disputes whether a prior record is current.", ownership: "The driver provides missing material; Employer B owns its qualification decision; BOF records the request and resulting status context.", history: "The record shows continuity across A to B instead of presenting B as a new identity or empty file." },
    { title: "Historical verification question", starting: "A reviewer questions why a document was previously accepted or why a status changed.", record: "The document version, evidence considered, prior review, reviewer identity, decision status, and subsequent correction.", actors: "The reviewer investigates; the driver may provide context; an employer uses the result for its own process.", exception: "Supporting evidence is incomplete or a prior decision cannot be reconstructed from the available record.", ownership: "The unresolved question is assigned for follow-up and cannot be represented as settled merely because a newer file exists.", history: "The verification change and its reason remain attached to the affected version and current state." },
  ],
  exceptionsTitle: "An unresolved historical question stays visible",
  exceptionsLead: "Continuity breaks when an old condition is overwritten instead of resolved. The Vault preserves uncertainty until an accountable action changes it.",
  exceptions: [
    "An expired, superseded, inconsistent, or disputed record can affect the meaning of the current file. The right response is to relate the condition to its owner, evidence, next action, and due follow-up rather than deleting the old state.",
    "A status change is not automatically a resolution. A reviewer may need to explain a decision, the driver may need to replace documentation, or an employer may need to apply its own policy. Each actor's responsibility remains distinct and historically visible.",
    "If the condition remains unresolved, management sees both the current limitation and the aging history. The record does not imply readiness simply because activity has occurred.",
  ],
  continuityTitle: "The record survives changes in employment",
  continuityLead: "Continuity means the driver's professional record remains coherent while employers, fleets, reviewers, and qualification contexts change.",
  continuity: [
    "The Vault connects Employer A, Employer B, and Employer C as contexts around the same driver-centered record. It does not make every employer a permanent owner of the Vault, and it does not copy one employer's operating file into the driver's professional record.",
    "Current state answers what is true now. Historical record answers how that state came to be. Both are necessary when a credential expires, a document is replaced, verification changes, or a later employer needs to understand prior context.",
  ],
  consequenceTitle: "A missing history changes the meaning of readiness",
  consequenceLead: "Management must be able to distinguish a resolved replacement from an unexplained disappearance of the prior record.",
  condition: "A current credential exists, but its prior version and replacement reason are absent.",
  consequence: "A prospective employer may face uncertainty about continuity, timing, or whether the current record addresses the earlier condition.",
  action: "Reconstruct the event chain, assign clarification, and keep the current state qualified until the history is understood.",
  levelThreeTitle: "Continuity & History — Future Level 3 subjects",
  levelThreeLead: "These are the deeper workflow subjects beneath this Level 2 domain. They are visible architectural gateways, not active links.",
  levelThree: [
    ["Continuity Documentation", "The documents and relationships that keep the driver's record connected across employment and credential changes."],
    ["Continuity Events", "The structured events that explain uploads, replacements, expirations, reviews, transitions, and corrections."],
    ["Continuity Audit", "The history of actors, decisions, access context, changes, and unresolved conditions."],
    ["Continuity Chain", "The relationship between what existed, what changed, what replaced it, and what is current."],
    ["Continuity Archive", "The durable historical context retained when a record is no longer current but still explains the professional story."],
  ],
  ctaTitle: "Keep the driver's record coherent through change",
  ctaLead: "The BOF Vault assessment helps identify where current status is disconnected from the history required to trust and explain it.",
};

export const verificationEvidence: VaultLevelTwoConfig = {
  slug: "verification-evidence",
  domain: "Verification & Evidence",
  title: "Verification & Evidence",
  description: "The administrative domain that distinguishes submitted documentation from reviewed evidence, verification status, and actual readiness for an employer process.",
  realityTitle: "A submitted document is not automatically verified",
  realityLead: "Verification & Evidence controls what was submitted, what was reviewed, what is supported, what remains uncertain, and what status can responsibly be shown.",
  reality: [
    "A driver may submit a CDL image, medical documentation, MVR, certification, or supporting record. Submission establishes that evidence entered the Vault. It does not prove completeness, authenticity, current validity, or readiness. Review determines what can be understood from the material; verification records what an authorized process can support.",
    "BOF can organize the evidence and preserve reviewer involvement, questions, outcomes, and history. It cannot independently certify every document, replace a regulator, or become the employer that decides whether the driver qualifies. The prospective employer receives appropriate context and applies its own hiring and qualification process.",
  ],
  mechanicsTitle: "The verification distinctions",
  mechanicsLead: "Keeping these states separate prevents an uploaded file from being mistaken for a supported professional conclusion.",
  mechanics: [
    ["Submission", "The driver provides a document or evidence item and its known source or context."],
    ["Review", "A person examines completeness, legibility, dates, consistency, and whether questions remain."],
    ["Verification", "An authorized reviewer or process records what evidence supports, without implying universal independent certification."],
    ["Status", "The record reflects current, incomplete, awaiting review, awaiting verification, expired, questionable, or resolved conditions."],
    ["Readiness", "The available evidence and status are considered usable for a particular employer process, which the employer still owns."],
  ],
  lifecycleTitle: "From submission to responsible readiness",
  lifecycleLead: "The lifecycle makes clear where evidence enters, where human judgment occurs, and where status must remain qualified.",
  lifecycle: [
    ["Submit", "The driver provides documentation and identifies its known source and professional purpose."],
    ["Intake", "BOF records the evidence item, driver association, document identity, and submitted context."],
    ["Review", "A reviewer examines completeness, legibility, dates, consistency, and obvious gaps."],
    ["Question", "Missing, inconsistent, questionable, or unsupported elements become explicit questions."],
    ["Evidence", "Supporting material, source information, and reviewer notes are related to the item under review."],
    ["Verify", "An authorized process records an outcome or leaves the item awaiting verification."],
    ["Status", "The record shows the qualified administrative state rather than an overbroad conclusion."],
    ["Readiness", "An employer can assess appropriate documentation for its own process with the available context."],
  ],
  workflowsTitle: "Three verification workflows",
  workflowsLead: "Each example separates the evidence event from the decision and preserves the unresolved path when support is insufficient.",
  workflows: [
    { title: "Evidence submitted for review", starting: "A driver uploads a credential image and identifies the issuing source.", record: "The submission, source identification, document type, dates, driver association, and supporting context.", actors: "The driver submits; BOF records intake; a reviewer examines the material; an employer may later consume appropriate status.", exception: "The image is incomplete, the source is unclear, or a required supporting page is absent.", ownership: "The driver supplies better evidence; the reviewer records the review result; BOF keeps the item awaiting review or incomplete until action occurs.", history: "The initial submission and review outcome remain available even if a replacement document is accepted." },
    { title: "Inconsistent evidence", starting: "A submitted credential date conflicts with another professional record or supporting document.", record: "Both evidence items, their sources, dates, relationship, reviewer question, and resulting status.", actors: "The reviewer identifies the inconsistency; the driver provides clarification; an employer applies its own qualification judgment.", exception: "The conflict cannot be resolved from available evidence or the source cannot be confirmed.", ownership: "The unresolved question belongs to the evidence or clarification owner; it cannot be upgraded to verified by elapsed time.", history: "The question, response, and any status change explain why the current record differs from the earlier submission." },
    { title: "Verification status changes", starting: "New supporting evidence changes the outcome of a prior review or verification.", record: "The prior outcome, new evidence, reviewer action, updated status, and effective time of the change.", actors: "An authorized reviewer records the change; the driver supplies evidence; an employer sees only appropriate information for its process.", exception: "The new material resolves one question but leaves another unresolved or expired.", ownership: "The reviewer documents scope and remaining questions; the driver addresses missing evidence; BOF preserves both outcomes.", history: "The verification history shows what was supported at each point rather than rewriting the past." },
  ],
  exceptionsTitle: "Uncertainty must become an owned next step",
  exceptionsLead: "Missing, incomplete, expired, inconsistent, questionable, awaiting review, and awaiting verification are different conditions with different next actions.",
  exceptions: [
    "A missing document may require driver submission. An incomplete document may require a page or corrected scan. An expired document may require renewal. An inconsistent record may require clarification. A questionable source may require authorized follow-up. Each condition needs its own status and owner.",
    "Review and verification are not interchangeable. A reviewer can determine that material is legible and internally consistent without independently confirming its external authenticity. A verification outcome must state what was supported and what remains outside the evidence available.",
    "Until the condition is resolved, readiness remains qualified for the relevant employer process. BOF preserves the path from question to evidence to outcome, while the employer retains its legal and operational decision.",
  ],
  continuityTitle: "Verification history gives status context",
  continuityLead: "A verification can change, a credential can expire, and new evidence can alter the administrative picture without erasing what was previously considered.",
  continuity: [
    "The driver remains the center of the record while evidence, reviewers, employers, and qualification contexts change around it. A later employer can receive appropriate current documentation and status without inheriting another employer's decision or becoming owner of the Vault.",
    "The history preserves which version was reviewed, what supporting evidence existed, who recorded the outcome, what questions remained, and why status changed. That context is what allows management to distinguish a genuinely resolved condition from a newer file that merely hides an older question.",
  ],
  consequenceTitle: "Verification status affects professional readiness",
  consequenceLead: "Management sees the difference between evidence that exists, evidence that is supported, and evidence that is ready for a particular employer process.",
  condition: "A credential was submitted, but review found a missing page and the source remains unconfirmed.",
  consequence: "The driver may not have a complete, supportable package for the next qualification request.",
  action: "Assign evidence follow-up, retain awaiting-verification status, and show readiness only within the employer's own decision process.",
  levelThreeTitle: "Verification & Evidence — Future Level 3 subjects",
  levelThreeLead: "These are the deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes are created here.",
  levelThree: [
    ["Evidence Intake", "How submitted documents, sources, context, and driver associations enter the verification record."],
    ["Evidence Review", "How completeness, legibility, dates, consistency, and questions are examined by an authorized reviewer."],
    ["Evidence Validation", "How supported outcomes are recorded with appropriate limits and without overstating independent certification."],
    ["Evidence Chain", "How documents, supporting evidence, reviewer actions, questions, and status changes remain related."],
    ["Evidence Archive", "How prior submissions, outcomes, and unresolved questions remain available as historical context."],
  ],
  ctaTitle: "Make evidence and readiness distinguishable",
  ctaLead: "The BOF Vault assessment helps identify where submissions, review, verification, status, and employer readiness are being conflated.",
};

export const exceptionsDisputes: VaultLevelTwoConfig = {
  slug: "exceptions-disputes",
  domain: "Exceptions & Disputes",
  title: "Exceptions & Disputes",
  description: "The administrative domain that keeps incomplete, conflicting, disputed, or aging conditions visible until the driver's record has an owned path to resolution.",
  realityTitle: "An exception is an administrative condition, not an error message",
  realityLead: "Exceptions & Disputes controls what prevents a driver's record from being treated as complete, current, verified, or accepted for a particular process.",
  reality: [
    "A missing medical-card page, conflicting credential date, disputed employment record, rejected evidence item, or unresolved ownership question can interrupt a driver's professional record. The important question is not merely whether the system shows an error. It is whether the condition is classified, routed, owned, aged, corrected, and historically explainable.",
    "The Vault keeps the driver at the center of that work. BOF can preserve the condition and route administrative follow-up, while the driver supplies clarification or replacement evidence and an employer applies its own qualification decision. The exception remains part of the portable record rather than disappearing inside one employer's file cabinet.",
  ],
  mechanicsTitle: "The mechanics of an owned exception",
  mechanicsLead: "A useful exception record says what is wrong, what it affects, who must act, what evidence is needed, and what happened next.",
  mechanics: [
    ["Intake", "Capture the condition, affected driver record, source, triggering evidence, date, and initial context."],
    ["Classification", "Distinguish missing, conflicting, disputed, expired, rejected, incomplete, or otherwise unresolved conditions."],
    ["Routing", "Direct the next action to the driver, reviewer, verifier, employer contact, or designated administrator."],
    ["Aging", "Keep due dates, follow-up attempts, elapsed time, and current status visible while the condition remains open."],
    ["Resolution", "Record the corrective evidence, decision, owner, outcome, and historical reason the condition changed."],
  ],
  lifecycleTitle: "Visibility to resolution",
  lifecycleLead: "The exception lifecycle prevents a condition from being lost between an alert and an undocumented closure.",
  lifecycle: [
    ["Detect", "A missing, conflicting, disputed, expired, or rejected condition enters the administrative view."],
    ["Classify", "The condition receives a meaningful type, severity, affected record, and process context."],
    ["Route", "The next action moves to the actor who can provide evidence, review the dispute, or make the applicable decision."],
    ["Own", "A named owner, due date, and follow-up expectation remain attached to the open condition."],
    ["Investigate", "Records, evidence, prior history, and involved people are compared without assuming the first submission is correct."],
    ["Correct", "The driver or responsible actor supplies a replacement, clarification, or other corrective material."],
    ["Decide", "An authorized reviewer or employer process records the applicable outcome and its limits."],
    ["Preserve", "The original condition, action path, resolution, and any remaining limitation stay in history."],
  ],
  workflowsTitle: "Three exception and dispute workflows",
  workflowsLead: "Each workflow shows how an exception becomes accountable work rather than a dead-end warning.",
  workflows: [
    { title: "Conflicting credential dates", starting: "A current credential and a supporting record show different issue or expiration dates.", record: "Both documents, their sources, driver association, date fields, and the conflict classification.", actors: "The driver provides clarification; BOF routes and records the condition; a reviewer assesses evidence; an employer owns its qualification decision.", exception: "Neither source can establish which date is authoritative or a replacement record is delayed.", ownership: "The clarification owner remains visible with follow-up and aging; resolution requires accepted evidence or an explicitly qualified status.", history: "The conflict, evidence considered, decision, and reason for the final date remain attached to the record." },
    { title: "Disputed employment record", starting: "A driver disputes an employment-related document or its association with the professional record.", record: "The disputed document, driver's statement, source context, related credential, and review status.", actors: "The driver raises the dispute; BOF records it; an authorized reviewer investigates; a former or prospective employer may provide context without owning the Vault.", exception: "The parties provide inconsistent accounts or the original source cannot be obtained.", ownership: "The dispute stays assigned for review and cannot be silently marked resolved because a new document was uploaded.", history: "The dispute, evidence, outcome, and any limitation on use remain available to explain later status." },
    { title: "Aging incomplete follow-up", starting: "A required document page or supporting evidence is missing after an initial request.", record: "The open exception, requested item, owner, request dates, follow-up attempts, and readiness impact.", actors: "The driver supplies the missing item; BOF tracks the request; the reviewer confirms completeness; the employer considers the qualified result.", exception: "The owner does not respond, the evidence remains incomplete, or the deadline passes.", ownership: "Aging remains visible and can be escalated or re-routed; closure requires documented evidence or a recorded decision to retain the limitation.", history: "The request and aging trail show why the record was not ready and what ultimately changed its condition." },
  ],
  exceptionsTitle: "The broken path still needs an owner",
  exceptionsLead: "Disputed and unresolved conditions require visibility, ownership, action, resolution, and history in that order and often more than once.",
  exceptions: [
    "Missing information is not the same as conflicting information. A disputed record is not the same as rejected evidence. Each condition gets its own classification, evidence request, owner, and next action so the driver and management can understand what is actually blocking progress.",
    "Aging is part of accountability. If a request is unanswered, a review is pending, or a dispute cannot be resolved, the Vault preserves the elapsed condition and the follow-up path rather than presenting an unexplained green status.",
    "Resolution means the corrective evidence or decision is recorded with scope and history. If the condition remains unresolved, the driver record can remain incomplete or not ready for the relevant employer process.",
  ],
  continuityTitle: "Exceptions follow the driver's record across employers",
  continuityLead: "A condition does not vanish because the driver changes carriers, operating environments, or returns to a prior employer.",
  continuity: [
    "The Vault preserves the exception, its evidence, owner, aging, resolution, and historical status as the driver moves from Employer A to Employer B to Employer C. A new employer can receive appropriate current context without inheriting another employer's decision or becoming owner of the portable record.",
    "When a driver returns to a prior employer, the record can show what was previously disputed, what changed during the intervening period, and which condition is current now. Continuity makes a resolved exception distinguishable from a deleted one.",
  ],
  consequenceTitle: "An unresolved exception changes professional readiness",
  consequenceLead: "Management needs the administrative condition, the operational consequence, the required action, and the preserved history together.",
  condition: "A disputed credential remains open after the requested source evidence was not supplied.",
  consequence: "The driver may not have an accepted or complete record for the next qualification process.",
  action: "Keep the dispute assigned and aging, request corrective evidence, and record the eventual resolution or limitation.",
  levelThreeTitle: "Exceptions & Disputes — Future Level 3 subjects",
  levelThreeLead: "These are deeper workflow subjects beneath this Level 2 domain. They are visible architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Exception Intake", "How missing, conflicting, disputed, rejected, expired, or incomplete conditions enter the administrative record."],
    ["Exception Routing", "How the next action moves to the actor who can supply, review, decide, or resolve the condition."],
    ["Dispute Review", "How conflicting accounts and evidence are examined with scope, ownership, and reviewer history."],
    ["Dispute Resolution", "How corrective evidence, decisions, limitations, and outcomes change the exception status."],
    ["Exception Aging", "How elapsed time, due dates, escalations, and unresolved responsibility remain visible."],
  ],
  ctaTitle: "Turn unresolved conditions into accountable work",
  ctaLead: "The BOF Vault assessment helps identify where exceptions, disputes, aging, ownership, and resolution are falling out of the driver's record.",
};

export const accountabilityOversight: VaultLevelTwoConfig = {
  slug: "accountability-oversight",
  domain: "Accountability & Oversight",
  title: "Accountability & Oversight",
  description: "The administrative domain that preserves who submitted, reviewed, verified, requested, decided, and owned the next action around a driver's portable record.",
  realityTitle: "A record is accountable when responsibility remains visible",
  realityLead: "Accountability & Oversight controls the chain from record to reviewer to decision to action to outcome to history.",
  reality: [
    "Storage alone cannot explain who supplied a document, who examined it, who requested additional evidence, who verified a condition, who accepted a correction, or who still owns an unresolved question. Those relationships matter when a driver's record crosses employers, departments, reviewers, and qualification processes.",
    "The Vault preserves responsibility without becoming the employer or regulator. The driver owns the professional record and may submit evidence; BOF records administrative activity and routes work; authorized reviewers and employers retain the decisions their roles require. Oversight makes those boundaries visible over time.",
  ],
  mechanicsTitle: "The mechanics of responsibility",
  mechanicsLead: "Oversight turns activity into an explainable chain of actors, decisions, actions, outcomes, and limits.",
  mechanics: [
    ["Submitted by", "Identify who supplied the record, when it entered the Vault, and what context accompanied it."],
    ["Reviewed by", "Preserve who examined completeness, dates, consistency, and supporting evidence."],
    ["Verified by", "Record the authorized verification role, scope, evidence considered, and limits of the outcome."],
    ["Action owner", "Show who must request, correct, clarify, approve, escalate, or follow up on the next condition."],
    ["Oversight", "Keep supervisory review, compliance checks, decisions, outcomes, and audit history available."],
  ],
  lifecycleTitle: "Record to accountable outcome",
  lifecycleLead: "This lifecycle follows responsibility rather than merely the movement of a file.",
  lifecycle: [
    ["Submit", "A driver or authorized participant provides information and identifies its source and purpose."],
    ["Assign", "The record is connected to the driver, credential, qualification context, and responsible administrative queue."],
    ["Review", "A reviewer examines the material and records what was checked, what was found, and what remains unknown."],
    ["Request", "Additional evidence or correction is requested from a named actor with a due expectation."],
    ["Verify", "An authorized role records what can be supported and the scope of that conclusion."],
    ["Supervise", "A supervisor or oversight function examines aging, exceptions, decisions, and unresolved responsibility."],
    ["Decide", "The applicable administrative or employer decision is recorded by the role that owns it."],
    ["Audit", "The chain of responsibility and outcome remains available as historical context."],
  ],
  workflowsTitle: "Three accountability and oversight workflows",
  workflowsLead: "These workflows show how the Vault preserves responsibility without collapsing distinct roles into a generic administrator.",
  workflows: [
    { title: "Review requests more evidence", starting: "A reviewer finds that a submitted credential does not establish completeness for its intended use.", record: "The submitted document, review finding, evidence request, driver association, and review status.", actors: "The driver supplies evidence; the reviewer records the request; BOF tracks the action; an employer later applies its own qualification process.", exception: "The requested evidence is not supplied or the reviewer cannot determine whether the response addresses the gap.", ownership: "The reviewer owns the review outcome; the driver owns supplying material; oversight sees aging and can escalate without changing the underlying decision.", history: "The request, response, reviewer action, and final status remain connected to the record." },
    { title: "Supervisory compliance check", starting: "An oversight review samples current driver records and finds inconsistent status handling across submissions.", record: "The sampled records, reviewer activity, status rationale, compliance finding, and corrective action.", actors: "A supervisor performs oversight; reviewers explain decisions; BOF preserves the audit chain; the driver may provide missing context.", exception: "The original reviewer or evidence source cannot be identified from the available history.", ownership: "The oversight owner assigns reconstruction or corrective work and records the limitation rather than attributing an unsupported decision.", history: "The audit finding and correction remain visible so later users understand why process or status changed." },
    { title: "Verification responsibility handoff", starting: "A reviewer completes an initial review and an authorized verifier must determine whether evidence supports a stated condition.", record: "The review result, verification request, evidence set, verifier identity, scope, and status transition.", actors: "The reviewer hands off context; the verifier records the supported outcome; the driver supplies clarification; the employer retains its hiring decision.", exception: "The verifier can support only part of the record or identifies a new question.", ownership: "Each role owns its boundary: reviewer for review, verifier for supported verification, driver for evidence, employer for qualification.", history: "The handoff and partial or changed outcome remain attached to the document version and current status." },
  ],
  exceptionsTitle: "Oversight exposes responsibility that storage hides",
  exceptionsLead: "When a record is incomplete or a decision is questioned, accountability must show who acted, what they knew, what they decided, and what remains due.",
  exceptions: [
    "An unidentified submitter, missing reviewer, unsupported verification, or ownerless request is itself an administrative exception. It should be classified and routed for reconstruction or correction instead of being treated as ordinary history.",
    "Supervisory review does not erase the original responsibility. It adds an oversight action, finding, and required correction. Compliance checks can reveal a process gap while preserving the driver's record and the distinct role of the employer's decision.",
    "Where evidence or history is insufficient, the record remains qualified. An audit trail must not manufacture certainty; it should show the limitation, owner, follow-up, and outcome when one becomes available.",
  ],
  continuityTitle: "Responsibility remains connected through transition",
  continuityLead: "The driver can change employers, carriers, operating environments, or return to a former employer without losing the chain of administrative responsibility.",
  continuity: [
    "A later employer can see appropriate current documentation and status without inheriting a former employer's internal decision. The Vault preserves who submitted, reviewed, verified, requested, and changed the record while keeping the driver as its center.",
    "New evidence, resolved exceptions, and changed oversight findings become new events in the chain. The historical record explains what was known at each point and why the current responsibility or status differs from the past. This is distinct from the employer's Operations File Cabinet, which preserves organizational operating records rather than ownership of the driver's portable Vault.",
  ],
  consequenceTitle: "Unclear responsibility creates an operational consequence",
  consequenceLead: "Management needs to see the administrative condition, the resulting qualification or readiness risk, the responsible action, and the chain that supports it.",
  condition: "A verification status is present, but the verifier and evidence scope are not preserved.",
  consequence: "A prospective employer cannot reliably interpret the status or determine what remains for its own process.",
  action: "Reconstruct the reviewer and verifier chain, qualify the status, and assign the missing accountability work.",
  levelThreeTitle: "Accountability & Oversight — Future Level 3 subjects",
  levelThreeLead: "These are deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Accountability Documentation", "How submissions, reviewer actions, decisions, requests, owners, and outcomes are recorded."],
    ["Oversight Review", "How supervisors examine current conditions, aging work, exceptions, and decision quality."],
    ["Oversight Audit", "How audit history preserves findings, evidence, responsibility, corrections, and limitations."],
    ["Administrative Review", "How an authorized reviewer evaluates record context, status, evidence, and unresolved questions."],
    ["Supervisory Actions", "How escalation, correction, approval, follow-up, and closure are assigned and preserved."],
  ],
  ctaTitle: "Make responsibility visible around the record",
  ctaLead: "The BOF Vault assessment helps identify where review, verification, oversight, and next-action ownership are disappearing into disconnected systems.",
};

export const administrativeActions: VaultLevelTwoConfig = {
  slug: "administrative-actions",
  domain: "Administrative Actions",
  title: "Administrative Actions",
  description: "The administrative domain that moves a driver's record from condition to action to result, updates its status, and preserves the action history that explains what changed.",
  realityTitle: "The record changes when someone acts on its condition",
  realityLead: "Administrative Actions controls what happens after information enters the Vault and a request, correction, approval, verification step, or decision becomes necessary.",
  reality: [
    "A record can be present yet require work: a credential needs correction, evidence must be requested, a reviewer must approve a status update, or an exception needs routing. An action is not just a button event. It is an accountable administrative record with an initiating condition, responsible actor, result, updated status, and historical consequence.",
    "The driver remains the owner of the portable professional record. BOF coordinates and preserves administrative actions; reviewers, verifiers, supervisors, and employers act within their authority. The resulting history travels with the driver rather than becoming trapped in the operating system of one employer.",
  ],
  mechanicsTitle: "The mechanics of an administrative action",
  mechanicsLead: "Every action should explain why it started, who performed it, what it changed, and what remains afterward.",
  mechanics: [
    ["Trigger", "Identify the condition, request, status, or evidence gap that requires an administrative action."],
    ["Route", "Send the action to the person or role authorized to request, correct, review, approve, or verify."],
    ["Perform", "Record the action, relevant evidence, decision context, date, actor, and scope."],
    ["Result", "Capture approval, correction, rejection, update, clarification, escalation, or unresolved outcome."],
    ["Archive", "Preserve the action, updated status, audit detail, and relationship to the driver's record."],
  ],
  lifecycleTitle: "Condition to preserved action history",
  lifecycleLead: "This lifecycle focuses on the administrative work that changes a record's condition after intake.",
  lifecycle: [
    ["Condition", "A missing, expired, disputed, incomplete, or reviewable state requires follow-up."],
    ["Request", "A named actor receives a request for evidence, correction, approval, or clarification."],
    ["Route", "The action is directed to the authorized role and given timing, context, and ownership."],
    ["Review", "The response or proposed change is examined against the affected record and supporting evidence."],
    ["Decide", "An authorized actor approves, rejects, updates, verifies, escalates, or leaves the condition unresolved."],
    ["Apply", "The result changes the record's current status with a clear effective context."],
    ["Follow up", "Remaining questions, dependencies, or corrective steps are carried into the next action."],
    ["Preserve", "The action and result become part of the permanent historical record."],
  ],
  workflowsTitle: "Three administrative action workflows",
  workflowsLead: "The workflows show how action changes condition while preserving role boundaries and historical continuity.",
  workflows: [
    { title: "Correction request", starting: "A review identifies an incorrect name, date, association, or classification on a professional record.", record: "The affected document, correction request, proposed value, source evidence, and current status.", actors: "The driver supplies corrected information; BOF routes the request; a reviewer validates the change; an employer uses the resulting record for its own process.", exception: "The correction conflicts with another source or the submitted replacement does not resolve the original error.", ownership: "The driver owns supplying correction evidence; the reviewer owns the decision to apply it; unresolved conflict remains assigned.", history: "The original value, correction action, evidence, actor, and updated status remain available for audit and continuity." },
    { title: "Administrative approval", starting: "A reviewed record is ready for an authorized approval or status decision within a defined process.", record: "The review result, evidence scope, approval request, approver, decision, and effective status.", actors: "A reviewer prepares context; an authorized approver decides; BOF preserves the action; the employer retains its own qualification authority.", exception: "Approval is rejected, limited to part of the record, or returned for additional evidence.", ownership: "The approver owns the decision; the driver or reviewer owns corrective follow-up; the return reason stays visible until action is complete.", history: "Approval, rejection, limitation, and later replacement actions form a connected decision history." },
    { title: "Status update after verification", starting: "New evidence changes a record that was awaiting verification or previously marked unresolved.", record: "The evidence, verification action, prior status, new status, actor, and effective time.", actors: "The driver submits; an authorized verifier records the supported result; BOF updates the administrative record; an employer interprets readiness for its own process.", exception: "The new evidence resolves one condition but reveals another or has a narrower scope than requested.", ownership: "The verifier documents scope and remaining work; the driver addresses missing evidence; BOF preserves the partial result.", history: "The status change points back to the action and evidence that caused it instead of rewriting the prior state." },
  ],
  exceptionsTitle: "An action is incomplete until its result is known",
  exceptionsLead: "Requests, approvals, corrections, and verification actions can fail, stall, or resolve only part of a condition. The Vault keeps that work visible.",
  exceptions: [
    "A routed request with no response, an approval without scope, a correction without source evidence, or an update that leaves a second question unresolved must not look complete. The action remains open or qualified with an owner and next step.",
    "Rejected actions also belong in history. A rejection explains what was considered, why it did not change the record, what consequence remains, and whether a new action can be taken with better evidence.",
    "Archival continuity means the action is preserved even after the current status changes. The driver, reviewer, verifier, supervisor, and employer can distinguish the result from the condition that initiated it.",
  ],
  continuityTitle: "Actions preserve continuity across operating change",
  continuityLead: "The action history remains part of the driver's record when employers, carriers, evidence sources, or operating contexts change.",
  continuity: [
    "A later employer can receive appropriate current documentation without receiving another employer's administrative system or inheriting its decisions. The action history shows how the current record was corrected, approved, verified, or left qualified.",
    "If the driver returns to a prior employer, the Vault can show the actions taken since the earlier relationship and distinguish a new request from a repeated unresolved condition. Continuity is preserved through events, not through silent overwrites. The Vault remains different from the employer's Operations File Cabinet: it carries the driver's portable professional record, while the File Cabinet carries organizational operating records.",
  ],
  consequenceTitle: "An administrative action changes what management can rely on",
  consequenceLead: "Management needs to see the condition, the operational consequence, the required action, and the history of the result.",
  condition: "A credential remains awaiting verification after a routed evidence request is only partially answered.",
  consequence: "The driver may remain unready for a specific qualification process even though activity is visible.",
  action: "Record the partial result, assign the remaining evidence action, and preserve the status change with scope.",
  levelThreeTitle: "Administrative Actions — Future Level 3 subjects",
  levelThreeLead: "These are deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Administrative Routing", "How conditions and requests move to the role authorized to perform the next action."],
    ["Administrative Approvals", "How review context, decision authority, approval scope, rejection, and return reasons are recorded."],
    ["Administrative Audit", "How actions, actors, evidence, decisions, status changes, and unresolved work remain reviewable."],
    ["Administrative History", "How every meaningful action explains what changed, when, why, and with what consequence."],
    ["Administrative Archive", "How completed, rejected, superseded, and historical actions remain available without confusing current state."],
  ],
  ctaTitle: "Make every record-changing action explainable",
  ctaLead: "The BOF Vault assessment helps identify where requests, approvals, corrections, status changes, and action history are losing continuity.",
};

export const identityAccess: VaultLevelTwoConfig = {
  slug: "identity-access",
  domain: "Identity & Access",
  title: "Identity & Access",
  description: "The administrative domain that establishes the driver's relationship to a portable professional record and controls who may see or act on relevant information.",
  realityTitle: "The driver owns the portable professional record",
  realityLead: "Identity & Access controls the chain from identity establishment to authorized visibility without turning the Vault into an employer-owned personnel file.",
  reality: [
    "A professional record is only useful when the Vault can establish that it belongs to the correct driver and can distinguish the driver's own access from an employer, reviewer, or verifier's limited process access. Account establishment, identity verification, authentication, credential management, and access history all contribute to that relationship.",
    "The driver may move from Employer A to Employer B to Employer C without creating a completely new professional record each time. An employer or authorized reviewer can interact with relevant information for a legitimate process, but access does not transfer ownership of the Vault or grant complete visibility by default.",
  ],
  mechanicsTitle: "The mechanics of controlled record access",
  mechanicsLead: "Access is meaningful only when identity, authorization, scope, action, and audit history remain connected.",
  mechanics: [
    ["Identity", "Establish the driver account, identity attributes, credential relationship, and evidence used to connect the person to the record."],
    ["Authentication", "Require the account holder or invited participant to prove control of the permitted access path before the record is shown."],
    ["Authorization", "Decide whether a driver, employer, reviewer, or verifier may perform a specific action or see a specific record scope."],
    ["Visibility", "Show relevant documentation and status without assuming that every participant should see the entire portable record."],
    ["Audit", "Preserve access requests, grants, denials, changes, revocations, and credential events for later review."],
  ],
  lifecycleTitle: "Identity establishment to continued control",
  lifecycleLead: "This lifecycle separates who the driver is, who may enter, what they may see, and how continued control is preserved.",
  lifecycle: [
    ["Establish identity", "Create the driver's Vault relationship and collect the account and identity context needed to distinguish the record owner."],
    ["Request access", "A driver, prospective employer, reviewer, or verifier requests access to a defined record scope or action."],
    ["Authorize", "An appropriate authority evaluates role, purpose, scope, and timing instead of granting complete access automatically."],
    ["Authenticate", "The participant proves control of the account or invitation before access is allowed."],
    ["Show relevant record", "The authorized participant sees only the documentation, status, or action context needed for the stated process."],
    ["Act or review", "The driver, reviewer, verifier, or employer performs the permitted administrative action within its role."],
    ["Change access", "Permissions, credentials, invitations, and access limits are updated when purpose or employment context changes."],
    ["Audit and continue", "The access history, revocation, and current controls remain connected to the driver's portable record."],
  ],
  workflowsTitle: "Three identity and access workflows",
  workflowsLead: "These workflows show how access can support an employer process without converting the Vault into an employer repository.",
  workflows: [
    { title: "Driver establishes Vault identity", starting: "A driver creates or claims the account that will carry the portable professional record.", record: "Identity attributes, account credentials, supporting identity evidence, driver association, and establishment status.", actors: "The driver establishes the relationship; BOF records and reviews identity evidence; an authorized process may verify identity within its scope.", exception: "Identity details conflict, evidence fails review, or the account appears to match an existing driver relationship.", ownership: "The driver owns clarification and credential control; BOF routes review and preserves any unresolved identity condition.", history: "Establishment evidence, changes, failed attempts, and the final identity status remain available as access history." },
    { title: "Prospective employer requests relevant access", starting: "A prospective employer needs appropriate professional records for its own hiring or qualification process.", record: "The access request, stated purpose, requested scope, relevant documents, status context, and expiration or revocation terms.", actors: "The employer requests; the driver authorizes or declines; BOF controls the request; reviewers or verifiers interact only within their assigned scope.", exception: "The request is too broad, the driver disputes the purpose, credentials are expired, or the requested record is not ready to share.", ownership: "The driver controls the portable record and access decision; the employer owns its qualification process; BOF preserves the request and result.", history: "The request, authorization, viewed scope, actions, expiry, and revocation remain connected without making the employer the record owner." },
    { title: "Identity or access condition requires review", starting: "An identity mismatch, unauthorized attempt, incorrect permission, or disputed identity condition is detected.", record: "The affected account or record, access event, credentials, evidence, permission state, reviewer action, and current restriction.", actors: "BOF routes the condition; the driver provides clarification; an authorized reviewer assesses evidence; an employer may be blocked or limited until resolved.", exception: "The identity cannot be confirmed, the access attempt is unauthorized, or the requested correction conflicts with prior history.", ownership: "The identity or permission owner remains assigned; access stays limited or revoked until a documented resolution is reached.", history: "The failed attempt, review, correction, permission change, and reason for restored or denied access remain auditable." },
  ],
  exceptionsTitle: "Access failure protects the record while creating work",
  exceptionsLead: "Identity mismatch, failed verification, unauthorized attempts, expired credentials, incorrect permissions, disputed identity, and revocation are different conditions with different actions.",
  exceptions: [
    "An access denial is not a complete resolution. The Vault records whether the issue concerns identity, authentication, authorization, scope, credential currency, or an unauthorized attempt, then assigns the next action to the driver, reviewer, verifier, or administrator who can address it.",
    "A prospective employer does not automatically receive complete record visibility. The driver may authorize relevant information for a defined purpose and period, while BOF preserves access boundaries and the employer applies its own qualification process.",
    "If identity cannot be established or access is revoked, the record remains protected and the condition remains visible. Restoring access requires an accountable change, not merely a later login attempt.",
  ],
  continuityTitle: "The driver's identity travels with the record",
  continuityLead: "Controlled access lets the professional record remain useful through employment transitions without repeating identity from scratch or surrendering ownership.",
  continuity: [
    "When the driver moves from Employer A to Employer B to Employer C, the Vault relationship remains connected to the driver. Each employer receives only the access scope appropriate to its process, and the driver's identity, credentials, access history, and revocations remain part of the portable record.",
    "The Vault is not an employer-owned personnel file or a general document repository. The Operations File Cabinet serves organizational records; BOF Vault serves the driver's portable professional record and records who was allowed to interact with relevant information over time.",
  ],
  consequenceTitle: "An access condition changes professional readiness",
  consequenceLead: "Management needs to see the administrative condition, the resulting visibility or qualification consequence, the required action, and the preserved access history.",
  condition: "A prospective employer's access request is broader than the driver-authorized record scope.",
  consequence: "The requested qualification process may pause while the driver decides what relevant documentation can be shared.",
  action: "Narrow or deny the request, record the authorization decision, and preserve the access boundary and follow-up history.",
  levelThreeTitle: "Identity & Access — Future Level 3 subjects",
  levelThreeLead: "These are deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Identity Verification", "How the Vault establishes the driver's identity and resolves mismatches or disputed identity evidence."],
    ["Access Control", "How roles, purpose, scope, authorization, expiration, and revocation determine record visibility."],
    ["Access Audit", "How requests, grants, denials, viewed scope, credential events, and revocations remain reviewable."],
    ["Credential Management", "How account credentials, authentication conditions, expiration, recovery, and secure changes are maintained."],
    ["Secure Self-Service", "How the driver manages identity context, sharing decisions, access requests, and portable record control."],
  ],
  ctaTitle: "Keep the driver's record portable and controlled",
  ctaLead: "The BOF Vault assessment helps identify where identity, access scope, authorization, credential control, and access history need clearer ownership.",
};

export const vaultIntake: VaultLevelTwoConfig = {
  slug: "intake",
  domain: "Intake",
  title: "Vault Intake",
  description: "The administrative beginning of the driver's professional record, where submitted documents and evidence become organized conditions ready for review and next action.",
  realityTitle: "Submission is not the record",
  realityLead: "Vault Intake is distinct from the operational /intake route and from the BOF Vault assessment: it receives the driver's professional material and starts its administrative lifecycle.",
  reality: [
    "A driver may submit a new CDL, medical document, MVR, certification, training record, or supporting evidence through a secure Vault path. Receipt alone does not make that material a complete record, a verified document, or proof of readiness. Intake must identify what arrived, associate it with the driver, assess its condition, and determine what happens next.",
    "Vault Intake is not the BOF Operational Intake Engine, not /assessment/bof-vault, and not the recovered static document-intake demo. It is the driver-centered entry point to a portable professional record. The Operations File Cabinet remains the home for organizational records; the Vault carries the driver's documentation and its intake history.",
  ],
  mechanicsTitle: "The mechanics of Vault Intake",
  mechanicsLead: "Intake creates the initial administrative record and routes uncertainty instead of treating every upload as accepted documentation.",
  mechanics: [
    ["Receive", "Capture the driver's submission, receipt time, source, submission context, and the material actually received."],
    ["Identify", "Determine document identity, type, issuing source, dates, and the professional purpose the material may support."],
    ["Associate", "Connect the submission to the correct driver and relevant credential or qualification context."],
    ["Assess", "Check completeness, duplicates, legibility, consistency, and whether supporting evidence is required."],
    ["Route", "Assign accepted, pending, incomplete, duplicate, inconsistent, rejected, or verification-needed status and next action."],
  ],
  lifecycleTitle: "Submission to organized administrative record",
  lifecycleLead: "Intake begins the lifecycle; it does not collapse classification, review, verification, and readiness into one upload event.",
  lifecycle: [
    ["Submit", "The driver provides a document or evidence item through the Vault's driver-centered intake path."],
    ["Receive", "The Vault records what arrived, when it arrived, and the source or context identified by the driver."],
    ["Identify", "The item is classified by document identity, type, source, dates, and professional purpose."],
    ["Associate", "The submission is matched to the correct driver and credential relationship."],
    ["Check", "Completeness, duplicate status, legibility, consistency, and supporting evidence needs are reviewed."],
    ["Create record", "The submission becomes an administrative record with a qualified status, not automatically a verified or ready record."],
    ["Route follow-up", "Missing information, exception work, review, or verification is assigned to the appropriate next owner."],
    ["Preserve history", "The submission, intake decision, status, follow-up, and later replacement remain connected over time."],
  ],
  workflowsTitle: "Three Vault Intake workflows",
  workflowsLead: "These workflows show how intake conditions determine what the driver's record can become next.",
  workflows: [
    { title: "New credential submission", starting: "A driver submits a newly issued CDL, medical document, certification, or training record.", record: "The submitted item, source, document type, dates, driver association, and professional purpose.", actors: "The driver submits; intake records and classifies; a reviewer checks completeness; an authorized verifier may later assess support.", exception: "The item is unreadable, missing required pages, duplicated, or cannot be associated confidently with the driver.", ownership: "The driver supplies a usable or clarifying submission; the intake or review owner routes the condition and records the resulting status.", history: "Receipt, classification, review outcome, later verification, and any replacement remain connected to the original submission." },
    { title: "Incomplete or ambiguous submission", starting: "The driver submits a partial scan, unclear source, inconsistent date, or document with ambiguous purpose.", record: "The received material, missing information, ambiguity classification, requested clarification, and affected driver record.", actors: "The driver provides clarification; intake records the condition; a reviewer examines the response; BOF routes any verification need.", exception: "Clarification is not supplied, the source remains uncertain, or the response resolves only part of the gap.", ownership: "The driver owns missing evidence; the reviewer owns the assessment; the record stays incomplete, pending, or awaiting verification until resolved.", history: "The initial ambiguous submission, follow-up requests, responses, and final disposition remain visible rather than being overwritten." },
    { title: "Replacement supersedes earlier record", starting: "The driver submits a renewed or corrected document that should replace an earlier professional record.", record: "The replacement item, earlier record, effective and expiration dates, supersession relationship, and intake status.", actors: "The driver submits; intake compares versions; a reviewer confirms the relationship; an authorized verifier may review supporting evidence.", exception: "The replacement conflicts with the prior record, does not cover the expected period, or cannot be linked to the same credential.", ownership: "The driver supplies clarification; the reviewer decides whether the supersession relationship is supported; unresolved conflict remains open.", history: "The earlier record remains historical, the replacement reason is preserved, and the current status points to the accepted version." },
  ],
  exceptionsTitle: "Intake makes uncertainty visible at the beginning",
  exceptionsLead: "A submission may be accepted, awaiting review, incomplete, duplicated, inconsistent, rejected, awaiting supporting evidence, or routed for verification.",
  exceptions: [
    "Each intake status has a different consequence. An accepted submission can proceed to review; an incomplete item needs driver follow-up; a duplicate needs comparison; an inconsistent item needs clarification; a rejected item needs a new submission or documented reason; a verification-needed item must remain qualified until an authorized process acts.",
    "A review queue is not proof that the record is ready. It is an ownership and routing condition that tells the driver, BOF, reviewer, and eventual employer what remains to be done and who is expected to do it.",
    "If no corrective action arrives, the incomplete or unresolved intake condition remains part of the record history. Intake begins continuity by preserving what was submitted and why its status changed later.",
  ],
  continuityTitle: "Intake history carries forward with the driver",
  continuityLead: "The first submission remains meaningful when later employers, replacements, evidence, and status changes need to be understood.",
  continuity: [
    "A driver can carry the Vault from Employer A to Employer B to Employer C. The intake history shows what was submitted, what was accepted or questioned, which replacement superseded an earlier record, and what remains current without restarting the professional record at every employer.",
    "Vault Intake is deliberately separate from the operational /intake route and the Vault assessment. It creates the beginning of the driver's portable record, while later domains handle review, verification, exceptions, actions, access, continuity, and employer-specific readiness.",
  ],
  consequenceTitle: "An intake condition determines the next professional step",
  consequenceLead: "Management needs to distinguish received material from an organized record and distinguish an organized record from verification or readiness.",
  condition: "A replacement credential is received but its source and relationship to the prior record remain ambiguous.",
  consequence: "The driver may not have a reliable current record for a prospective employer's qualification process.",
  action: "Route clarification, retain the prior version, qualify the status, and update the record only after the replacement relationship is supported.",
  levelThreeTitle: "Vault Intake — Future Level 3 subjects",
  levelThreeLead: "These are deeper workflow subjects beneath this Level 2 domain. They are architectural gateways only; no Level 3 routes exist in this batch.",
  levelThree: [
    ["Intake Routing", "How submissions, review queues, missing information, exceptions, and verification needs move to the next owner."],
    ["Intake Validation", "How identity, document type, source, dates, completeness, duplicates, consistency, and association are assessed."],
    ["Intake Storage", "How received material becomes a durable driver-associated record with status, relationships, and history."],
  ],
  ctaTitle: "Start the driver's record with the right condition",
  ctaLead: "The BOF Vault assessment helps identify where professional submissions are being received without clear classification, ownership, status, or continuity.",
};
