export type CanonicalRouteProfile = {
  route: string;
  pageName: string;
  functionalArea: string;
  routeFamily: string;
  access: "public" | "authenticated" | "demo";
  status: "canonical" | "legacy" | "duplicate" | "recovered";
  dataSource: string;
  canonicalHomeRoute?: string;
  canonicalDetailPattern?: string;
  header: string;
  miniHeader: string;
  parentPage?: string;
  primaryChildren?: string[];
  duplicates?: string[];
};

export const BOF_CANONICAL_PAGE_REGISTRY: CanonicalRouteProfile[] = [
  {
    route: "/business-operations",
    pageName: "Business Operations",
    functionalArea: "Business Operations",
    routeFamily: "marketing-public-story",
    access: "public",
    status: "canonical",
    dataSource: "recovered-public-archive",
    canonicalHomeRoute: "/business-operations",
    canonicalDetailPattern: "/business-operations/*",
    header: "BOF marketing navigation",
    miniHeader: "Business operations overview",
    parentPage: "/",
    primaryChildren: ["/business-operations/route-optimization", "/business-operations/operations-dashboard"],
    duplicates: ["/recovered/business-operations", "/legacy/business-operations"],
  },
  {
    route: "/documents",
    pageName: "Operations File Cabinet",
    functionalArea: "Documents / Operations File Cabinet",
    routeFamily: "document-cabinet",
    access: "authenticated",
    status: "canonical",
    dataSource: "generated-document-registry",
    canonicalHomeRoute: "/documents",
    canonicalDetailPattern: "/documents/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Operations file cabinet",
    parentPage: "/dashboard",
    primaryChildren: ["/documents/template-packs", "/documents/driver-vault"],
    duplicates: ["/recovered/documents", "/demo/documents"],
  },
  {
    route: "/drivers",
    pageName: "Drivers",
    functionalArea: "Drivers",
    routeFamily: "driver-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "driver-vault + generated files",
    canonicalHomeRoute: "/drivers",
    canonicalDetailPattern: "/drivers/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Driver records",
    parentPage: "/dashboard",
    primaryChildren: ["/drivers/[id]", "/drivers/[id]/documents"],
    duplicates: ["/driver-portal", "/legacy/drivers"],
  },
  {
    route: "/loads",
    pageName: "Loads",
    functionalArea: "Loads",
    routeFamily: "load-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "load-workflow + generated-docs",
    canonicalHomeRoute: "/loads",
    canonicalDetailPattern: "/loads/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Load operations",
    parentPage: "/dispatch",
    primaryChildren: ["/loads/[id]", "/loads/[id]/trip-release"],
    duplicates: ["/dispatch", "/legacy/loads"],
  },
  {
    route: "/dispatch",
    pageName: "Dispatch",
    functionalArea: "Dispatch",
    routeFamily: "dispatch-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "dispatch-workflow",
    canonicalHomeRoute: "/dispatch",
    canonicalDetailPattern: "/dispatch/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Dispatch command center",
    parentPage: "/dashboard",
    primaryChildren: ["/dispatch/[id]", "/trip-release/[id]"],
    duplicates: ["/loads", "/dispatch-v1", "/dispatch-v2"],
  },
  {
    route: "/safety",
    pageName: "Safety & Compliance",
    functionalArea: "Safety & Compliance",
    routeFamily: "safety-command-center",
    access: "authenticated",
    status: "canonical",
    dataSource: "safety-evidence + compliance vault",
    canonicalHomeRoute: "/safety",
    canonicalDetailPattern: "/safety/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Safety command center",
    parentPage: "/dashboard",
    primaryChildren: ["/safety/incidents", "/safety/claims"],
    duplicates: ["/recovered/safety", "/legacy/safety"],
  },
  {
    route: "/settlements",
    pageName: "Settlements & Billing",
    functionalArea: "Settlements & Billing",
    routeFamily: "settlement-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "settlement-packets + finance templates",
    canonicalHomeRoute: "/settlements",
    canonicalDetailPattern: "/settlements/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Settlements and billing",
    parentPage: "/dashboard",
    primaryChildren: ["/settlements/[id]", "/settlements/[id]/audit"],
    duplicates: ["/finance", "/legacy/settlements"],
  },
  {
    route: "/maintenance",
    pageName: "Maintenance",
    functionalArea: "Maintenance",
    routeFamily: "asset-maintenance",
    access: "authenticated",
    status: "canonical",
    dataSource: "asset-maintenance-registry",
    canonicalHomeRoute: "/maintenance",
    canonicalDetailPattern: "/maintenance/[id]",
    header: "Authenticated BOF app shell",
    miniHeader: "Maintenance overview",
    parentPage: "/dashboard",
    primaryChildren: ["/maintenance/[id]", "/maintenance/[id]/inspection"],
    duplicates: ["/legacy/maintenance"],
  },
  {
    route: "/operational-chat",
    pageName: "Operational Chat",
    functionalArea: "Operational Chat",
    routeFamily: "communication-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "conversation-history",
    canonicalHomeRoute: "/operational-chat",
    canonicalDetailPattern: "/operational-chat/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Interactions and messages",
    parentPage: "/dashboard",
    primaryChildren: ["/operational-chat"],
    duplicates: ["/messages", "/conversations", "/legacy/conversations"],
  },
  {
    route: "/documents/company-operations-vault",
    pageName: "Company Operations Vault",
    functionalArea: "Company Operations",
    routeFamily: "vault-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "company-operations-vault",
    canonicalHomeRoute: "/documents/company-operations-vault",
    canonicalDetailPattern: "/documents/company-operations-vault/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Company operations vault",
    parentPage: "/documents",
    primaryChildren: ["/documents/company-operations-vault", "/documents"],
    duplicates: ["/company-operations", "/operations-vault", "/legacy/company-operations"],
  },
  {
    route: "/government",
    pageName: "Government",
    functionalArea: "Public sector",
    routeFamily: "marketing-sector",
    access: "public",
    status: "canonical",
    dataSource: "recovered-sector-content",
    canonicalHomeRoute: "/government",
    canonicalDetailPattern: "/government/*",
    header: "Public marketing navigation",
    miniHeader: "Government solutions",
    parentPage: "/",
    primaryChildren: ["/government/municipal-services", "/government/logistics-policy"],
    duplicates: ["/legacy/government", "/recovered/government"],
  },
  {
    route: "/dashboard",
    pageName: "Dashboard",
    functionalArea: "Command Center",
    routeFamily: "executive-overview",
    access: "authenticated",
    status: "canonical",
    dataSource: "dashboard-aggregate",
    canonicalHomeRoute: "/dashboard",
    canonicalDetailPattern: "/dashboard/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Executive overview",
    parentPage: "/",
    primaryChildren: ["/dispatch", "/loads", "/drivers", "/safety"],
    duplicates: ["/command-center", "/legacy/dashboard"],
  },
  {
    route: "/command-center",
    pageName: "Command Center",
    functionalArea: "Command Center",
    routeFamily: "operating-command-center",
    access: "demo",
    status: "duplicate",
    dataSource: "demo-command-center-v4",
    canonicalHomeRoute: "/dashboard",
    canonicalDetailPattern: "/command-center/*",
    header: "Demo BOF app shell",
    miniHeader: "Three portals. One operating system.",
    parentPage: "/dashboard",
    primaryChildren: ["/portals/driver", "/portals/customer", "/portals/manager"],
    duplicates: ["/dashboard", "/legacy/command-center"],
  },
  {
    route: "/portals/driver",
    pageName: "Driver Portal",
    functionalArea: "Driver Portal",
    routeFamily: "portal-experience",
    access: "demo",
    status: "canonical",
    dataSource: "demo-portal-config",
    canonicalHomeRoute: "/portals/driver",
    canonicalDetailPattern: "/portals/driver/[driverId]",
    header: "Portal navigation",
    miniHeader: "Driver operations portal",
    parentPage: "/portals",
    primaryChildren: ["/portals/driver/[driverId]"],
    duplicates: ["/drivers", "/legacy/driver-portal"],
  },
  {
    route: "/portals/customer",
    pageName: "Customer / Shipper Portal",
    functionalArea: "Customer / Shipper Portal",
    routeFamily: "portal-experience",
    access: "demo",
    status: "canonical",
    dataSource: "demo-portal-config",
    canonicalHomeRoute: "/portals/customer",
    canonicalDetailPattern: "/portals/customer/[loadId]",
    header: "Portal navigation",
    miniHeader: "Customer visibility portal (demo loads)",
    parentPage: "/portals",
    primaryChildren: ["/shipper-portal/[loadId]"],
    duplicates: ["/shipper-portal", "/legacy/customer-portal"],
  },
  {
    route: "/customer-portal",
    pageName: "Customer Portal (customer-facing workspace)",
    functionalArea: "Customer / Shipper Portal",
    routeFamily: "portal-experience",
    access: "demo",
    status: "canonical",
    dataSource: "recovered-customer-portal-workspace",
    canonicalHomeRoute: "/customer-portal",
    canonicalDetailPattern: "/customer-portal/*",
    header: "Customer portal rail",
    miniHeader: "Intake through billing / factoring",
    parentPage: "/",
    primaryChildren: [
      "/customer-portal/load-intake",
      "/customer-portal/quotes",
      "/customer-portal/shipments",
      "/customer-portal/assignment",
      "/customer-portal/documents",
      "/customer-portal/tracking",
      "/customer-portal/billing",
    ],
    duplicates: ["/portals/customer", "/shipper-portal", "/legacy/customer-portal"],
  },
  {
    route: "/rf-actions",
    pageName: "Exception Management",
    functionalArea: "Exception Management",
    routeFamily: "action-queue",
    access: "authenticated",
    status: "canonical",
    dataSource: "risk-and-exception-queue",
    canonicalHomeRoute: "/rf-actions",
    canonicalDetailPattern: "/rf-actions/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Exception management",
    parentPage: "/dashboard",
    primaryChildren: ["/money-at-risk", "/rf-actions"],
    duplicates: ["/money-at-risk", "/legacy/risk"],
  },
  {
    route: "/operational-chat",
    pageName: "Conversations",
    functionalArea: "Conversations",
    routeFamily: "communication-operations",
    access: "authenticated",
    status: "canonical",
    dataSource: "operational-chat-history",
    canonicalHomeRoute: "/operational-chat",
    canonicalDetailPattern: "/operational-chat/*",
    header: "Authenticated BOF app shell",
    miniHeader: "Operational communications",
    parentPage: "/dashboard",
    primaryChildren: ["/operational-chat"],
    duplicates: ["/conversations", "/messages"],
  },
];

export const BOF_CANONICAL_ROUTE_FAMILY = {
  guidance: "Choose the strongest implementation by completeness, auth model, data source, and route hierarchy, then converge all internal navigation to that canonical route.",
  priorities: [
    "functional completeness",
    "canonical data integration",
    "authorization and security",
    "route architecture",
    "visual consistency",
    "reusability",
    "historical quality",
    "mobility quality",
    "maintainability",
  ],
  canonicalFamilies: [
    "Business Operations",
    "Drivers",
    "Loads",
    "Dispatch",
    "Documents / Operations File Cabinet",
    "Safety & Compliance",
    "Settlements & Billing",
    "Maintenance",
    "Conversations",
    "Company Operations",
    "Driver Portal",
    "Customer / Shipper Portal",
    "Command Center",
    "Exception Management",
  ],
};
