export type OperationsFileCabinetItem = {
  id: string;
  title: string;
  cabinet:
    | "Driver Qualification Files"
    | "Secondary Driver Documents"
    | "Dispatch & Load Operations"
    | "Contracts / Customer / Legal"
    | "Safety / Claims / Insurance"
    | "HR / Talent / Performance"
    | "Policies & SOPs"
    | "Finance / Settlements / Back Office"
    | "Training & Knowledge Base";
  section:
    | "Blank Templates"
    | "Completed Demo Samples"
    | "Company Policies & SOPs"
    | "BOF Dispatch Templates"
    | "Claims Forms"
    | "Legal / Contracts"
    | "External Resources"
    | "Needs Review / Coming Later"
    | "Related Policies / Acknowledgments"
    | "Finance Templates"
    | "Policy-Based Training";
  category:
    | "Driver Qualification Files"
    | "Secondary Driver Documents"
    | "Dispatch & Load Operations"
    | "Safety / Claims / Insurance"
    | "HR / Talent / Performance"
    | "Policies & SOPs"
    | "Finance / Settlements / Back Office"
    | "Training & Knowledge Base"
    | "Contracts / Customer / Legal";
  type:
    | "driver-file"
    | "template"
    | "policy"
    | "checklist"
    | "form"
    | "video"
    | "article"
    | "sop"
    | "contract"
    | "training"
    | "external_resource";
  audience: Array<
    | "driver"
    | "manager"
    | "dispatcher"
    | "hr"
    | "finance"
    | "safety"
    | "customer"
    | "legal"
    | "owner"
    | "vendor"
    | "dispatch"
    | "maintenance"
    | "procurement"
    | "it"
    | "admin"
    | "compliance"
    | "billing"
    | "sales"
  >;
  status: "available" | "available_route" | "template" | "needs_review" | "external_resource" | "coming_soon";
  description: string;
  href?: string;
  sourceAuthenticity: "official_template" | "generated_from_template" | "external_resource" | "coming_soon";
  documentOwner: "employer" | "platform" | "external";
  employerName: string;
  isBlankTemplate?: boolean;
  isCompletedSample?: boolean;
  tags?: string[];
  sampleHref?: string;
  templateHref?: string;
};

export const OPERATIONS_FILE_CABINET_REGISTRY: OperationsFileCabinetItem[] = [
  // Driver Qualification Files - Blank Templates
  {
    id: "driver-cdl-template",
    title: "CDL Verification Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank CDL verification template for new driver qualification",
    href: "/generated/templates/driver-docs/cdl-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["qualification", "license", "compliance"]
  },
  {
    id: "driver-medical-template",
    title: "Medical Card Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank medical card template for DOT physical examination",
    href: "/generated/templates/driver-docs/medical-card-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["medical", "dot", "physical"]
  },
  {
    id: "driver-mvr-template",
    title: "MVR Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank motor vehicle record template for driving history review",
    href: "/generated/templates/driver-docs/mvr-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["driving", "record", "mvr"]
  },
  {
    id: "driver-clearinghouse-template",
    title: "FMCSA Compliance Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank FMCSA clearinghouse compliance template",
    href: "/generated/templates/driver-docs/fmcsa-compliance-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["fmcsa", "clearinghouse", "drug", "alcohol"]
  },
  {
    id: "driver-i9-template",
    title: "I-9 Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr"],
    status: "template",
    description: "Blank I-9 employment eligibility verification template",
    href: "/generated/templates/driver-docs/i9-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["employment", "eligibility", "i9"]
  },
  {
    id: "driver-w9-template",
    title: "W-9 Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "finance"],
    status: "template",
    description: "Blank W-9 tax form template for owner-operators",
    href: "/generated/templates/driver-docs/w9-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["tax", "w9", "contractor"]
  },
  {
    id: "driver-emergency-contact-template",
    title: "Emergency Contact Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank emergency contact information template",
    href: "/generated/templates/driver-docs/emergency-contact-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["emergency", "contact", "medical"]
  },
  {
    id: "driver-bank-info-template",
    title: "Bank Information Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "finance"],
    status: "template",
    description: "Blank bank information template for direct deposit",
    href: "/generated/templates/driver-docs/bank-information-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["banking", "direct", "deposit"]
  },
  {
    id: "driver-road-test-template",
    title: "Road Test Certificate Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank road test evaluation and certification template",
    href: "/generated/templates/driver-docs/road-test-certificate-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["road", "test", "evaluation"]
  },
  {
    id: "driver-employment-verification-template",
    title: "Employment Verification Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr"],
    status: "template",
    description: "Blank employment verification and history template",
    href: "/generated/templates/driver-docs/employment-verification-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["employment", "verification", "history"]
  },
  {
    id: "driver-safety-policy-template",
    title: "Safety Policy Acknowledgment Template",
    cabinet: "Driver Qualification Files",
    section: "Blank Templates",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr", "safety"],
    status: "template",
    description: "Blank safety policy acknowledgment and certification template",
    href: "/generated/templates/driver-docs/safety-policy-acknowledgment-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["safety", "policy", "acknowledgment"]
  },
  // Driver Qualification Files - Completed Demo Samples
  {
    id: "driver-cdl-sample-john-carter",
    title: "CDL Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Completed CDL verification completed operating example",
    href: "/generated/drivers/DRV-001/cdl.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/cdl-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-medical-sample-john-carter",
    title: "Medical Card Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Completed medical card completed operating example",
    href: "/generated/drivers/DRV-001/medical-card.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/medical-card-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-mvr-sample-john-carter",
    title: "MVR Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Completed MVR completed operating example",
    href: "/generated/drivers/DRV-001/mvr.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/mvr-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-clearinghouse-sample-john-carter",
    title: "FMCSA Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Completed FMCSA clearinghouse completed operating example",
    href: "/generated/drivers/DRV-001/fmcsa-compliance.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/fmcsa-compliance-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-w9-sample-john-carter",
    title: "W-9 Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "finance"],
    status: "available",
    description: "Completed W-9 completed operating example",
    href: "/generated/drivers/DRV-001/w9.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/w9-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-application",
    title: "Driver Application",
    cabinet: "Driver Qualification Files",
    section: "Needs Review / Coming Later",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr"],
    status: "needs_review",
    description: "Standard driver employment application form",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["application", "employment", "coming"]
  },
  {
    id: "driver-road-test-sample-john-carter",
    title: "Road Test Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Completed road test completed operating example",
    href: "/generated/drivers/DRV-001/road-test-certificate.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/road-test-certificate-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-employment-verification-sample-john-carter",
    title: "Employment Verification Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "form",
    audience: ["driver", "manager", "hr"],
    status: "available",
    description: "Completed employment verification completed operating example",
    href: "/generated/drivers/DRV-001/employment_verification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/employment-verification-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-emergency-contacts-sample-john-carter",
    title: "Emergency Contacts Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "dispatcher"],
    status: "available",
    description: "Completed emergency contacts completed operating example",
    href: "/generated/drivers/DRV-001/emergency-contact.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/emergency-contact-template.html",
    tags: ["sample", "completed", "demo"]
  },
  {
    id: "driver-profile",
    title: "Driver Profile",
    cabinet: "Driver Qualification Files",
    section: "Needs Review / Coming Later",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "hr"],
    status: "needs_review",
    description: "Complete driver profile and documentation access",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["profile", "dashboard", "coming"]
  },
  {
    id: "driver-bank-info-sample-john-carter",
    title: "Bank Information Completed Sample — John Carter",
    cabinet: "Driver Qualification Files",
    section: "Completed Demo Samples",
    category: "Driver Qualification Files",
    type: "driver-file",
    audience: ["driver", "manager", "finance"],
    status: "available",
    description: "Completed bank information completed operating example",
    href: "/generated/drivers/DRV-001/bank-information.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    templateHref: "/generated/templates/driver-docs/bank-information-template.html",
    tags: ["sample", "completed", "demo"]
  },
  // Secondary Driver Documents
  {
    id: "driver-coaching-notes",
    title: "Coaching Notes",
    cabinet: "Secondary Driver Documents",
    section: "Needs Review / Coming Later",
    category: "Secondary Driver Documents",
    type: "driver-file",
    audience: ["driver", "manager", "safety"],
    status: "needs_review",
    description: "Driver coaching documentation and follow-up records",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["coaching", "documentation", "coming"]
  },
  {
    id: "driver-safety-scorecards",
    title: "Safety Scorecards",
    cabinet: "Secondary Driver Documents",
    section: "Needs Review / Coming Later",
    category: "Secondary Driver Documents",
    type: "driver-file",
    audience: ["driver", "manager", "safety"],
    status: "needs_review",
    description: "Monthly safety performance metrics and trends",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["safety", "performance", "coming"]
  },
  {
    id: "driver-incident-history-john-carter",
    title: "Incident History — John Carter Sample",
    cabinet: "Secondary Driver Documents",
    section: "Completed Demo Samples",
    category: "Secondary Driver Documents",
    type: "driver-file",
    audience: ["driver", "manager", "safety"],
    status: "available",
    description: "Complete incident and violation history tracking sample",
    href: "/generated/drivers/DRV-001/incident-report.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["sample", "incident", "history"]
  },
  {
    id: "driver-training-completions",
    title: "Training Completion Records",
    cabinet: "Secondary Driver Documents",
    section: "Needs Review / Coming Later",
    category: "Secondary Driver Documents",
    type: "driver-file",
    audience: ["driver", "manager", "hr", "safety"],
    status: "needs_review",
    description: "Training course completion certificates and records",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["training", "completion", "coming"]
  },
  {
    id: "driver-disciplinary-notices",
    title: "Disciplinary Notices",
    cabinet: "Secondary Driver Documents",
    section: "Needs Review / Coming Later",
    category: "Secondary Driver Documents",
    type: "form",
    audience: ["driver", "manager", "hr"],
    status: "needs_review",
    description: "Disciplinary action notices and documentation",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["disciplinary", "notices", "coming"]
  },
  {
    id: "driver-communication-logs",
    title: "Driver Communication Logs",
    cabinet: "Secondary Driver Documents",
    section: "Needs Review / Coming Later",
    category: "Secondary Driver Documents",
    type: "form",
    audience: ["driver", "manager", "dispatcher"],
    status: "needs_review",
    description: "Driver communication and interaction documentation logs",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["communication", "logs", "coming"]
  },

  // Dispatch & Load Operations
  {
    id: "dispatch-load-intake",
    title: "Load Tender / Order Sheet",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "form",
    audience: ["dispatcher", "manager"],
    status: "available",
    description: "Standard load booking and information collection form",
    href: "/documents/template-packs/load-tender-order-sheet.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["load", "intake", "booking"]
  },
  {
    id: "dispatch-vehicle-inspection",
    title: "Vehicle Inspection Checklist",
    cabinet: "Dispatch & Load Operations",
    section: "Needs Review / Coming Later",
    category: "Dispatch & Load Operations",
    type: "checklist",
    audience: ["dispatcher", "driver", "safety"],
    status: "needs_review",
    description: "Vehicle inspection and safety check before departure",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["vehicle", "inspection", "coming"]
  },
  {
    id: "dispatch-route-readiness",
    title: "Route / Dispatch Readiness Checklist",
    cabinet: "Dispatch & Load Operations",
    section: "Completed Demo Samples",
    category: "Dispatch & Load Operations",
    type: "checklist",
    audience: ["dispatcher", "driver", "manager"],
    status: "available_route",
    description: "L001 pre-trip packet workspace with dispatch review, driver signoff, document thumbnails, and release controls.",
    href: "/trip-release/L001",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["sample", "pretrip", "planning"]
  },
  {
    id: "dispatch-rate-confirmation",
    title: "Rate Confirmation",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "manager", "customer"],
    status: "available",
    description: "Rate confirmation and pricing agreement documentation",
    href: "/documents/template-packs/rate-confirmation.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["rate", "confirmation", "pricing"]
  },
  {
    id: "dispatch-bill-of-lading",
    title: "Bill of Lading",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "driver", "customer"],
    status: "available",
    description: "Standard bill of lading for freight documentation",
    href: "/documents/template-packs/bill-of-lading.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["bill", "lading", "freight"]
  },
  {
    id: "dispatch-proof-delivery",
    title: "Proof of Delivery",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "driver", "customer"],
    status: "available",
    description: "Proof of delivery documentation and signature collection",
    href: "/documents/template-packs/proof-of-delivery.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["proof", "delivery", "signature"]
  },
  {
    id: "dispatch-work-order-sample",
    title: "Work Order — L001 Sample",
    cabinet: "Dispatch & Load Operations",
    section: "Completed Demo Samples",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "driver", "customer"],
    status: "available",
    description: "Work order sample for specialized services and requirements",
    href: "/generated/loads/L001/work-order.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["sample", "work", "order"]
  },
  {
    id: "dispatch-insurance-notice-sample",
    title: "Insurance Notice — L001 Sample",
    cabinet: "Dispatch & Load Operations",
    section: "Completed Demo Samples",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "customer", "legal"],
    status: "available",
    description: "Insurance coverage and claims notice sample",
    href: "/generated/loads/L001/insurance-notification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["sample", "insurance", "notice"]
  },
  {
    id: "dispatch-invoice-sample",
    title: "Invoice — L001 Sample",
    cabinet: "Dispatch & Load Operations",
    section: "Completed Demo Samples",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "finance", "customer"],
    status: "available",
    description: "Standard invoice sample for billing and settlements",
    href: "/generated/loads/L001/invoice.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["sample", "invoice", "billing"]
  },
  {
    id: "dispatch-claim-intake",
    title: "Claim Intake Form",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "form",
    audience: ["dispatcher", "safety", "legal"],
    status: "available",
    description: "Initial claim reporting and information collection form",
    href: "/documents/template-packs/claim-intake-form.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["claim", "intake", "reporting"]
  },
  {
    id: "dispatch-master-agreement-sample",
    title: "Delta Advanced Trucking, Inc. Master Services Agreement",
    cabinet: "Dispatch & Load Operations",
    section: "Legal / Contracts",
    category: "Dispatch & Load Operations",
    type: "contract",
    audience: ["dispatcher", "manager", "customer", "legal"],
    status: "available",
    description: "Master services agreement governing tender, proof, payment, insurance, claims, and dispute handling for Delta Advanced Trucking, Inc.",
    href: "/generated/agreements/DAT-MSA-001/delta-advanced-trucking-master-services-agreement.pdf",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["master services agreement", "contract", "customer", "dispatch"]
  },
  // Safety / Claims / Insurance
  {
    id: "safety-accident-report",
    title: "Accident Report Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Comprehensive accident reporting and documentation form",
    href: "/generated/claims/L003/accident-report.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["accident", "report", "sample", "completed"]
  },
  {
    id: "safety-incident-response",
    title: "Incident Response Checklist",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "checklist",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Step-by-step incident response and documentation checklist",
    href: "/generated/claims/L003/incident-report.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["incident", "response", "checklist", "sample", "completed"]
  },
  {
    id: "claims-intake-safety",
    title: "Claim Intake Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Claims Forms",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["manager", "safety", "customer", "legal"],
    status: "available",
    description: "Standard cargo damage claim intake and documentation",
    href: "/documents/template-packs/claim-intake-form.html",
    sourceAuthenticity: "official_template",
    documentOwner: "platform",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["claim", "intake", "cargo"]
  },
  {
    id: "claims-insurance-claim",
    title: "Insurance Claim Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["manager", "safety", "legal"],
    status: "available",
    description: "Insurance claim submission and documentation form",
    href: "/generated/claims/L003/insurance-notification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["insurance", "claim", "sample", "completed"]
  },
  {
    id: "claims-police-report",
    title: "Police Report Request Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "needs_review",
    description: "Police incident report request and documentation template",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["police", "report", "coming"]
  },
  {
    id: "safety-driver-statement",
    title: "Driver Statement Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Driver statement form for accident and incident reporting",
    href: "/generated/claims/L003/driver-statement.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["driver", "statement", "sample", "completed"]
  },
  {
    id: "claims-witness-statement",
    title: "Witness Statement Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "needs_review",
    description: "Witness statement collection and documentation form",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["witness", "statement", "coming"]
  },
  {
    id: "claims-damage-assessment",
    title: "Damage Assessment Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["manager", "safety", "customer"],
    status: "available",
    description: "Damage assessment and cost estimate documentation form",
    href: "/generated/claims/L003/damage-photo-packet.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["damage", "assessment", "sample", "completed"]
  },
  {
    id: "claims-photo-documentation",
    title: "Photo Documentation Checklist",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "checklist",
    audience: ["driver", "manager", "safety"],
    status: "available",
    description: "Photo documentation and evidence collection checklist for claims",
    href: "/generated/claims/L003/photo-evidence-log.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["photo", "documentation", "checklist", "sample", "completed"]
  },
  {
    id: "claims-claim-packet",
    title: "Claim Packet Template",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "template",
    audience: ["manager", "safety", "customer", "legal"],
    status: "needs_review",
    description: "Complete claim packet template with all required documentation",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["claim", "packet", "coming"]
  },
  {
    id: "claims-collection-demand",
    title: "Collection & Demand Letter Templates",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "template",
    audience: ["manager", "legal", "customer"],
    status: "needs_review",
    description: "Collection and demand letter templates for claims",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["collection", "demand", "coming"]
  },
  {
    id: "claims-insurance-notice",
    title: "Insurance Notice Letter",
    cabinet: "Safety / Claims / Insurance",
    section: "Claims Forms",
    category: "Safety / Claims / Insurance",
    type: "template",
    audience: ["manager", "safety", "legal"],
    status: "available",
    description: "Insurance notification and claim reporting documentation",
    href: "/generated/loads/L001/insurance-notification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["insurance", "notice", "sample"]
  },
  {
    id: "claims-escalation-sop",
    title: "Delta Advanced Trucking, Inc. Claims, Proof Packet & Insurance Escalation SOP",
    cabinet: "Safety / Claims / Insurance",
    section: "Company Policies & SOPs",
    category: "Safety / Claims / Insurance",
    type: "policy",
    audience: ["manager", "safety", "legal", "finance"],
    status: "available",
    description: "Standard operating procedures for claims escalation, proof packet documentation, and insurance workflow",
    href: "/generated/company-operations-vault/DAT_SOP_CLM_001_Rev3_1.pdf",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["claims", "insurance", "risk", "sop", "procedures", "proof-packet"]
  },
  {
    id: "safety-evidence-photos",
    title: "Safety Evidence Photos",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety"],
    status: "needs_review",
    description: "Individual safety evidence photos and documentation",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["evidence", "photos", "coming"]
  },
  {
    id: "claims-settlement-agreement",
    title: "Settlement Agreement Template",
    cabinet: "Safety / Claims / Insurance",
    section: "Needs Review / Coming Later",
    category: "Safety / Claims / Insurance",
    type: "contract",
    audience: ["manager", "safety", "customer", "legal"],
    status: "needs_review",
    description: "Claim settlement agreement and release template",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["settlement", "agreement", "coming"]
  },
  {
    id: "contract-document-preservation",
    title: "Document Preservation Notice",
    cabinet: "Contracts / Customer / Legal",
    section: "Legal / Contracts",
    category: "Contracts / Customer / Legal",
    type: "template",
    audience: ["manager", "legal", "hr"],
    status: "needs_review",
    description: "Document preservation and retention notice template",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["document", "preservation", "coming"]
  },

  // Policies & SOPs Cabinet - Add missing cabinet
  {
    id: "policy-code-of-conduct",
    title: "Code of Conduct Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "hr", "safety"],
    status: "needs_review",
    description: "Company code of conduct and ethical guidelines",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["conduct", "ethics", "policy"]
  },
  {
    id: "policy-information-security",
    title: "Information Security Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "hr", "admin"],
    status: "needs_review",
    description: "Information security and data protection policies",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["security", "data", "policy"]
  },

  // Finance / Settlements / Back Office Cabinet - Add missing cabinet
  {
    id: "finance-invoice-template",
    title: "Invoice Template",
    cabinet: "Finance / Settlements / Back Office",
    section: "Needs Review / Coming Later",
    category: "Finance / Settlements / Back Office",
    type: "template",
    audience: ["manager", "finance", "customer"],
    status: "needs_review",
    description: "Standard invoice template for billing and settlements",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["invoice", "billing", "finance"]
  },
  {
    id: "finance-expense-report",
    title: "Expense Report Form",
    cabinet: "Finance / Settlements / Back Office",
    section: "Needs Review / Coming Later",
    category: "Finance / Settlements / Back Office",
    type: "form",
    audience: ["driver", "manager", "finance"],
    status: "needs_review",
    description: "Employee expense reporting and reimbursement form",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["expense", "reimbursement", "finance"]
  },

  // Training & Knowledge Base Cabinet - Add missing cabinet
  {
    id: "training-safety-program",
    title: "Safety Training Program",
    cabinet: "Training & Knowledge Base",
    section: "Needs Review / Coming Later",
    category: "Training & Knowledge Base",
    type: "training",
    audience: ["driver", "manager", "safety"],
    status: "needs_review",
    description: "Comprehensive safety training program and materials",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["training", "safety", "program"]
  },
  {
    id: "training-compliance-courses",
    title: "Compliance Training Courses",
    cabinet: "Training & Knowledge Base",
    section: "External Resources",
    category: "Training & Knowledge Base",
    type: "external_resource",
    audience: ["driver", "manager", "hr"],
    status: "needs_review",
    description: "External compliance training resources and courses",
    sourceAuthenticity: "external_resource",
    documentOwner: "external",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["training", "compliance", "external"]
  },

  // Add missing Claims Forms section
  {
    id: "claims-accident-report",
    title: "Accident Report Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Claims Forms",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "needs_review",
    description: "Comprehensive accident reporting and documentation form",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["accident", "report", "claims"]
  },
  {
    id: "claims-damage-report",
    title: "Cargo Damage Report Form",
    cabinet: "Safety / Claims / Insurance",
    section: "Claims Forms",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "customer"],
    status: "needs_review",
    description: "Cargo damage assessment and reporting form",
    sourceAuthenticity: "coming_soon",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["damage", "cargo", "claims"]
  },

  // Add missing External Resources section items
  {
    id: "external-fmcsa-regulations",
    title: "FMCSA Regulations Portal",
    cabinet: "Safety / Claims / Insurance",
    section: "External Resources",
    category: "Safety / Claims / Insurance",
    type: "external_resource",
    audience: ["driver", "manager", "safety", "compliance"],
    status: "available",
    description: "Link to FMCSA regulations and compliance resources",
    href: "https://www.fmcsa.dot.gov",
    sourceAuthenticity: "external_resource",
    documentOwner: "external",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["fmcsa", "regulations", "external"]
  },
  {
    id: "external-dot-resources",
    title: "DOT Resource Center",
    cabinet: "Training & Knowledge Base",
    section: "External Resources",
    category: "Training & Knowledge Base",
    type: "external_resource",
    audience: ["driver", "manager", "safety"],
    status: "available",
    description: "Department of Transportation training and resource center",
    href: "https://www.transportation.gov",
    sourceAuthenticity: "external_resource",
    documentOwner: "external",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["dot", "training", "external"]
  },

  // Accounting Templates - Finance / Settlements / Back Office
  {
    id: "driver-settlement-statement",
    title: "Driver Settlement Statement",
    cabinet: "Finance / Settlements / Back Office",
    section: "Blank Templates",
    category: "Finance / Settlements / Back Office",
    type: "template",
    audience: ["driver", "manager", "finance", "dispatcher"],
    status: "template",
    description: "Multi-section settlement statement with earnings, deductions, and YTD totals",
    href: "/documents/accounting-templates/driver-settlement-statement.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["settlement", "statement", "accounting", "template"]
  },
  {
    id: "fuel-card-reconciliation-worksheet",
    title: "Fuel Card Reconciliation Worksheet",
    cabinet: "Finance / Settlements / Back Office",
    section: "Blank Templates",
    category: "Finance / Settlements / Back Office",
    type: "template",
    audience: ["driver", "manager", "finance", "dispatcher"],
    status: "template",
    description: "Weekly fuel reconciliation with 14-column table and exception escalation matrix",
    href: "/documents/accounting-templates/fuel-card-reconciliation-worksheet.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["fuel", "reconciliation", "accounting", "template"]
  },
  {
    id: "fleet-asset-register",
    title: "Fleet Asset Register",
    cabinet: "Finance / Settlements / Back Office",
    section: "Blank Templates",
    category: "Finance / Settlements / Back Office",
    type: "template",
    audience: ["manager", "finance", "maintenance", "admin"],
    status: "template",
    description: "23-column scrollable asset register with fleet summary and capitalization policy",
    href: "/documents/accounting-templates/fleet-asset-register.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["fleet", "assets", "register", "accounting", "template"]
  },
  {
    id: "ifta-quarterly-mileage-fuel-log",
    title: "IFTA Quarterly Mileage & Fuel Log",
    cabinet: "Finance / Settlements / Back Office",
    section: "Blank Templates",
    category: "Finance / Settlements / Back Office",
    type: "template",
    audience: ["driver", "manager", "finance", "dispatcher"],
    status: "template",
    description: "Quarterly IFTA reporting with all 58 jurisdictions and filing deadline reminders",
    href: "/documents/accounting-templates/ifta-quarterly-mileage-fuel-log.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["ifta", "mileage", "fuel", "quarterly", "compliance", "template"]
  },

  // Dispatch & Load Operations - BOF Dispatch Templates
  {
    id: "dispatch-load-intake-form",
    title: "Load Intake Form",
    cabinet: "Dispatch & Load Operations",
    section: "BOF Dispatch Templates",
    category: "Dispatch & Load Operations",
    type: "template",
    audience: ["dispatcher", "manager", "customer"],
    status: "template",
    description: "Standard load intake form for customer load requests",
    href: "/documents/template-packs/load-intake-form.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["dispatch", "load", "intake", "template"]
  },
  // Contracts / Customer / Legal - Legal / Contracts
  {
    id: "contract-carrier-agreement",
    title: "Carrier Agreement Template",
    cabinet: "Contracts / Customer / Legal",
    section: "Legal / Contracts",
    category: "Contracts / Customer / Legal",
    type: "contract",
    audience: ["manager", "legal", "customer", "owner"],
    status: "template",
    description: "Standard carrier service agreement template",
    href: "/documents/template-packs/carrier-agreement.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["contract", "carrier", "agreement", "template"]
  },
  {
    id: "contract-customer-agreement",
    title: "Customer Service Agreement",
    cabinet: "Contracts / Customer / Legal",
    section: "Legal / Contracts",
    category: "Contracts / Customer / Legal",
    type: "contract",
    audience: ["manager", "legal", "customer", "sales"],
    status: "template",
    description: "Customer service agreement and terms template",
    href: "/documents/template-packs/customer-agreement.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["contract", "customer", "agreement", "template"]
  },
  {
    id: "contract-bill-of-lading",
    title: "Bill of Lading Template",
    cabinet: "Contracts / Customer / Legal",
    section: "Legal / Contracts",
    category: "Contracts / Customer / Legal",
    type: "template",
    audience: ["dispatcher", "driver", "customer", "finance"],
    status: "template",
    description: "Standard bill of lading template for freight shipments",
    href: "/documents/template-packs/bill-of-lading.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    tags: ["contract", "bol", "freight", "template"]
  },

  // HR / Talent / Performance - Blank Templates
  {
    id: "hr-performance-review",
    title: "Delta Advanced Trucking, Inc. Driver HR Performance Review Form",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Trucking-specific HR review form covering dispatch execution, safety, documentation, proof packets, settlement support, and BOF system review.",
    href: "/generated/company-operations-vault/hr-templates/driver-hr-performance-review-form.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "template"]
  },
  {
    id: "hr-driver-coaching-corrective-action",
    title: "Delta Advanced Trucking, Inc. Driver Coaching / Corrective Action Form",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Coaching and corrective-action form tied to dispatch records, safety events, proof packets, settlement holds, and compliance action IDs.",
    href: "/generated/company-operations-vault/hr-templates/driver-coaching-corrective-action-form.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "corrective action"]
  },
  {
    id: "hr-new-driver-onboarding-checklist",
    title: "Delta Advanced Trucking, Inc. New Driver Onboarding Checklist",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "checklist",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "New-driver onboarding checklist for identity, qualification, payroll setup, BOF system setup, policy acknowledgments, and dispatch readiness.",
    href: "/generated/company-operations-vault/hr-templates/new-driver-onboarding-checklist.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "new driver"]
  },
  {
    id: "hr-driver-policy-acknowledgment",
    title: "Delta Advanced Trucking, Inc. Driver Policy Acknowledgment Form",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Driver acknowledgment form for handbook, safety, dispatch communication, proof packet, settlement, claims, and BOF platform-use policies.",
    href: "/generated/company-operations-vault/hr-templates/driver-policy-acknowledgment-form.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "policy"]
  },
  {
    id: "hr-payroll-settlement-dispute-review",
    title: "Delta Advanced Trucking, Inc. Payroll / Settlement Dispute Review Form",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Payroll and settlement dispute review form for driver explanation, disputed amount, proof documents, BOF records, findings, and adjustment approval.",
    href: "/generated/company-operations-vault/hr-templates/payroll-settlement-dispute-review-form.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "dispute"]
  },
  {
    id: "hr-return-to-work-fitness-for-duty",
    title: "Delta Advanced Trucking, Inc. Return-to-Work / Fitness-for-Duty Review Form",
    cabinet: "HR / Talent / Performance",
    section: "Blank Templates",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Return-to-work and fitness-for-duty review form for safety events, compliance issues, restrictions, training, and dispatch eligibility decisions.",
    href: "/generated/company-operations-vault/hr-templates/return-to-work-fitness-for-duty-review-form.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isBlankTemplate: true,
    isCompletedSample: false,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "return to work"]
  },
  {
    id: "hr-noah-wilson-annual-performance-review-2026",
    title: "Completed Annual Review - Noah Wilson (DRV-010)",
    cabinet: "HR / Talent / Performance",
    section: "Completed Demo Samples",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Completed annual review sample using the current Noah Wilson HOS coaching, reroute, safety-bonus, and dispatch-readiness storyline.",
    href: "/generated/company-operations-vault/hr-samples/noah-wilson-annual-performance-review-2026.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["hr", "driver review", "performance", "coaching", "compliance", "safety", "payroll", "settlement", "onboarding", "annual review", "sample"]
  },
  {
    id: "hr-benefits-enrollment-john-carter",
    title: "Benefits Enrollment - John Carter (DRV-001)",
    cabinet: "HR / Talent / Performance",
    section: "Completed Demo Samples",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr"],
    status: "available",
    description: "Completed employee benefits enrollment sample from the driver HR/payroll file.",
    href: "/generated/drivers/DRV-001/hr-payroll/benefits-enrollment.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["hr", "benefits", "enrollment", "driver review", "payroll", "onboarding", "sample"]
  },
  {
    id: "hr-employee-handbook-acknowledgment-john-carter",
    title: "Employee Handbook Acknowledgment - John Carter (DRV-001)",
    cabinet: "HR / Talent / Performance",
    section: "Completed Demo Samples",
    category: "HR / Talent / Performance",
    type: "form",
    audience: ["manager", "hr", "safety"],
    status: "available",
    description: "Completed handbook acknowledgment sample from the driver HR/payroll file.",
    href: "/generated/drivers/DRV-001/hr-payroll/employee-handbook-acknowledgment.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["hr", "handbook", "acknowledgment", "policy", "onboarding", "sample"]
  },

  // Training & Knowledge Base - Policy-Based Training
  {
    id: "training-safety-orientation",
    title: "Safety Orientation Training",
    cabinet: "Training & Knowledge Base",
    section: "Policy-Based Training",
    category: "Training & Knowledge Base",
    type: "training",
    audience: ["driver", "manager", "safety", "hr"],
    status: "available",
    description: "New driver safety orientation and policy training",
    href: "/generated/company-operations-vault/10-safety-compliance-governance-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["training", "safety", "orientation", "policy"]
  },
  {
    id: "training-hazmat-certification",
    title: "HAZMAT Certification Training",
    cabinet: "Training & Knowledge Base",
    section: "Policy-Based Training",
    category: "Training & Knowledge Base",
    type: "training",
    audience: ["driver", "manager", "safety"],
    status: "available",
    description: "HAZMAT handling and certification training program",
    href: "/generated/company-operations-vault/10-safety-compliance-governance-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["training", "hazmat", "certification", "safety"]
  },
  // Company Operations Vault - Additional Policies
  {
    id: "company-operations-vault-index",
    title: "Company Operations Vault Index & Naming Standards",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "hr", "finance", "safety", "legal", "owner"],
    status: "available",
    description: "Master index and naming standards for all company operations documents",
    href: "/generated/company-operations-vault/00-company-operations-vault-index-and-naming-standards.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["operations", "vault", "index", "standards", "policy"]
  },
  {
    id: "employee-handbook",
    title: "Delta Advanced Trucking, Inc. Employee Handbook",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Comprehensive employee handbook with workplace policies and procedures",
    href: "/generated/company-operations-vault/01-employee-handbook-template.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["employee", "handbook", "workplace", "policy"]
  },
  {
    id: "code-of-conduct",
    title: "Code of Conduct and Workplace Policies",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "hr", "safety"],
    status: "available",
    description: "Workplace behavior standards and code of conduct policies",
    href: "/generated/company-operations-vault/02-code-of-conduct-and-workplace-policies.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["code", "conduct", "workplace", "behavior", "policy"]
  },
  {
    id: "hr-onboarding-offboarding",
    title: "HR Onboarding and Offboarding Checklist",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "hr", "driver"],
    status: "available",
    description: "Employee lifecycle procedures for onboarding and offboarding",
    href: "/generated/company-operations-vault/03-hr-onboarding-and-offboarding-checklist.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["hr", "onboarding", "offboarding", "checklist", "policy"]
  },
  {
    id: "payroll-compensation-policy",
    title: "Payroll, Compensation and Deductions Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "hr", "finance", "driver"],
    status: "available",
    description: "Financial policies for payroll, compensation, and deductions",
    href: "/generated/company-operations-vault/04-payroll-compensation-and-deductions-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["payroll", "compensation", "deductions", "financial", "policy"]
  },
  {
    id: "accounting-finance-sop",
    title: "Accounting, Finance Close, AP/AR SOP",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "sop",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Standard operating procedures for accounting and finance operations",
    href: "/generated/company-operations-vault/05-accounting-finance-close-ap-ar-sop.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["accounting", "finance", "sop", "procedures"]
  },
  {
    id: "factoring-receivables-policy",
    title: "Factoring and Receivables Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Receivables management and factoring procedures",
    href: "/generated/company-operations-vault/06-factoring-and-receivables-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["factoring", "receivables", "financial", "policy"]
  },
  {
    id: "vendor-maintenance-policy",
    title: "Vendor Maintenance and Purchasing Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "procurement", "maintenance"],
    status: "available",
    description: "Procurement policies and vendor management procedures",
    href: "/generated/company-operations-vault/08-vendor-maintenance-and-purchasing-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["vendor", "procurement", "purchasing", "policy"]
  },
  {
    id: "mission-vision-principles",
    title: "Mission, Vision and Operating Principles",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "hr", "owner"],
    status: "available",
    description: "Company mission, vision, and core operating principles",
    href: "/generated/company-operations-vault/09-mission-vision-and-operating-principles.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["mission", "vision", "principles", "company", "policy"]
  },
  {
    id: "safety-compliance-governance",
    title: "Safety Compliance Governance Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "safety", "hr"],
    status: "available",
    description: "Safety compliance and governance framework",
    href: "/generated/company-operations-vault/10-safety-compliance-governance-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["safety", "compliance", "governance", "policy"]
  },
  {
    id: "information-security-governance",
    title: "Information Security Governance Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "it", "hr", "safety"],
    status: "available",
    description: "Data protection and information security governance",
    href: "/generated/company-operations-vault/11-information-security-governance-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["security", "information", "data", "policy"]
  },
  {
    id: "acceptable-use-policy",
    title: "Acceptable Use of Company Systems Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "it", "hr"],
    status: "available",
    description: "Acceptable use policies for company systems and technology",
    href: "/generated/company-operations-vault/12-acceptable-use-of-company-systems-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["acceptable", "use", "systems", "technology", "policy"]
  },
  {
    id: "information-classification-policy",
    title: "Information Classification Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "it", "hr", "legal"],
    status: "available",
    description: "Data classification and handling procedures",
    href: "/generated/company-operations-vault/13-information-classification-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["classification", "information", "data", "policy"]
  },
  {
    id: "data-protection-standard",
    title: "Data Protection and Secure Handling Standard",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "it", "hr", "legal"],
    status: "available",
    description: "Secure data handling and protection standards",
    href: "/generated/company-operations-vault/14-data-protection-and-secure-handling-standard.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["data", "protection", "security", "standard"]
  },
  {
    id: "privacy-employee-data-policy",
    title: "Privacy and Employee Data Handling Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "hr", "legal"],
    status: "available",
    description: "Employee privacy and data handling policies",
    href: "/generated/company-operations-vault/15-privacy-and-employee-data-handling-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["privacy", "employee", "data", "policy"]
  },
  {
    id: "vendor-security-assessment-policy",
    title: "Vendor Security Assessment Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "procurement", "it", "legal"],
    status: "available",
    description: "Security assessment procedures for vendors and partners",
    href: "/generated/company-operations-vault/16-vendor-security-assessment-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["vendor", "security", "assessment", "policy"]
  },
  {
    id: "ai-use-governance-policy",
    title: "AI Use and Automation Governance Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "it", "hr", "legal"],
    status: "available",
    description: "AI and automation usage governance and policies",
    href: "/generated/company-operations-vault/17-ai-use-and-automation-governance-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["ai", "automation", "governance", "technology", "policy"]
  },
  {
    id: "driver-worker-classification-policy",
    title: "Driver Worker Classification and Owner-Operator Engagement Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["driver", "manager", "hr", "legal"],
    status: "available",
    description: "Driver classification and owner-operator engagement policies",
    href: "/generated/company-operations-vault/18-driver-worker-classification-and-owner-operator-engagement-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["driver", "classification", "owner", "operator", "policy"]
  },
  {
    id: "tax-audit-readiness-policy",
    title: "Tax and Regulatory Audit Readiness Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "finance", "legal"],
    status: "available",
    description: "Tax compliance and audit readiness procedures",
    href: "/generated/company-operations-vault/19-tax-and-regulatory-audit-readiness-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["tax", "audit", "compliance", "regulatory", "policy"]
  },
  {
    id: "fuel-mileage-tax-checklist",
    title: "Fuel, Mileage and Excise Tax Support Checklist",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "checklist",
    audience: ["driver", "manager", "finance"],
    status: "available",
    description: "Fuel tax and mileage reporting support checklist",
    href: "/generated/company-operations-vault/20-fuel-mileage-and-excise-tax-support-checklist.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["fuel", "mileage", "tax", "checklist", "compliance"]
  },
  {
    id: "cash-flow-management-policy",
    title: "Cash Flow Management and Receivables Acceleration Policy",
    cabinet: "Policies & SOPs",
    section: "Company Policies & SOPs",
    category: "Policies & SOPs",
    type: "policy",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Cash flow management and receivables acceleration procedures",
    href: "/generated/company-operations-vault/21-cash-flow-management-and-receivables-acceleration-policy.html",
    sourceAuthenticity: "official_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    tags: ["cash", "flow", "receivables", "financial", "policy"]
  },

  // Claims Documents - Safety / Claims / Insurance
  {
    id: "claims-accident-report-l003",
    title: "Accident Report - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Accident report documentation for load L003",
    href: "/generated/claims/L003/accident-report.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["accident", "report", "sample", "L003"]
  },
  {
    id: "claims-claim-intake-l003",
    title: "Claim Intake Form - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Claim intake form for load L003",
    href: "/generated/claims/L003/claim-intake.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["claim", "intake", "sample", "L003"]
  },
  {
    id: "claims-claim-packet-l003",
    title: "Claim Packet - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Complete claim packet for load L003",
    href: "/generated/claims/L003/claim-packet.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["claim", "packet", "sample", "L003"]
  },
  {
    id: "claims-damage-photo-packet-l003",
    title: "Damage Photo Packet - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Damage photo documentation packet for load L003",
    href: "/generated/claims/L003/damage-photo-packet.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["damage", "photo", "packet", "sample", "L003"]
  },
  {
    id: "claims-driver-statement-l003",
    title: "Driver Statement - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Driver statement for load L003 incident",
    href: "/generated/claims/L003/driver-statement.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["driver", "statement", "sample", "L003"]
  },
  {
    id: "claims-incident-report-l003",
    title: "Incident Report - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Incident report documentation for load L003",
    href: "/generated/claims/L003/incident-report.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["incident", "report", "sample", "L003"]
  },
  {
    id: "claims-insurance-notification-l003",
    title: "Insurance Notification - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Insurance notification for load L003",
    href: "/generated/claims/L003/insurance-notification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["insurance", "notification", "sample", "L003"]
  },
  {
    id: "claims-photo-evidence-log-l003",
    title: "Photo Evidence Log - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Photo evidence log for load L003",
    href: "/generated/claims/L003/photo-evidence-log.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["photo", "evidence", "log", "sample", "L003"]
  },
  {
    id: "claims-seal-verification-l003",
    title: "Seal Verification - L003",
    cabinet: "Safety / Claims / Insurance",
    section: "Completed Demo Samples",
    category: "Safety / Claims / Insurance",
    type: "form",
    audience: ["driver", "manager", "safety", "legal"],
    status: "available",
    description: "Seal verification documentation for load L003",
    href: "/generated/claims/L003/seal-verification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["seal", "verification", "sample", "L003"]
  },

  // Factoring Documents - Finance / Settlements / Back Office
  {
    id: "factoring-invoice-l011",
    title: "Factoring Invoice - L011",
    cabinet: "Finance / Settlements / Back Office",
    section: "Completed Demo Samples",
    category: "Finance / Settlements / Back Office",
    type: "form",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Factoring invoice for load L011",
    href: "/generated/factoring/L011/invoice.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["factoring", "invoice", "sample", "L011"]
  },
  {
    id: "factoring-rate-confirmation-l011",
    title: "Factoring Rate Confirmation - L011",
    cabinet: "Finance / Settlements / Back Office",
    section: "Completed Demo Samples",
    category: "Finance / Settlements / Back Office",
    type: "form",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Factoring rate confirmation for load L011",
    href: "/generated/loads/L011/rate-confirmation.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["factoring", "rate", "confirmation", "sample", "L011"]
  },
  {
    id: "factoring-notification-l011",
    title: "Factoring Notification - L011",
    cabinet: "Finance / Settlements / Back Office",
    section: "Completed Demo Samples",
    category: "Finance / Settlements / Back Office",
    type: "form",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Factoring notification for load L011",
    href: "/generated/factoring/L011/factoring-notification.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["factoring", "notification", "sample", "L011"]
  },
  {
    id: "post-trip-factoring-packet-l011",
    title: "Post-Trip Factoring Packet - L011",
    cabinet: "Finance / Settlements / Back Office",
    section: "Completed Demo Samples",
    category: "Finance / Settlements / Back Office",
    type: "form",
    audience: ["manager", "finance", "billing"],
    status: "available",
    description: "Complete post-trip factoring packet with all required documents for load L011",
    href: "/generated/factoring/L011/post-trip-factoring-packet.html",
    sourceAuthenticity: "generated_from_template",
    documentOwner: "employer",
    employerName: "Delta Advanced Trucking, Inc.",
    isCompletedSample: true,
    tags: ["factoring", "packet", "post-trip", "sample", "L011"]
  }
];

export type OperationsFileCabinetCategory = OperationsFileCabinetItem["category"];
export type OperationsFileCabinetType = OperationsFileCabinetItem["type"];
export type OperationsFileCabinetAudience = OperationsFileCabinetItem["audience"][number];
export type OperationsFileCabinetStatus = OperationsFileCabinetItem["status"];

export function getOperationsFileCabinetItems(): OperationsFileCabinetItem[] {
  return OPERATIONS_FILE_CABINET_REGISTRY;
}

export function getOperationsFileCabinetItemsByCategory(category: OperationsFileCabinetCategory): OperationsFileCabinetItem[] {
  return OPERATIONS_FILE_CABINET_REGISTRY.filter(item => item.category === category);
}

export function getOperationsFileCabinetItemsByType(type: OperationsFileCabinetType): OperationsFileCabinetItem[] {
  return OPERATIONS_FILE_CABINET_REGISTRY.filter(item => item.type === type);
}

export function getOperationsFileCabinetItemsByAudience(audience: OperationsFileCabinetAudience): OperationsFileCabinetItem[] {
  return OPERATIONS_FILE_CABINET_REGISTRY.filter(item => item.audience.includes(audience));
}

export function getOperationsFileCabinetItemsByStatus(status: OperationsFileCabinetStatus): OperationsFileCabinetItem[] {
  return OPERATIONS_FILE_CABINET_REGISTRY.filter(item => item.status === status);
}

export function getOperationsFileCabinetCategories(): OperationsFileCabinetCategory[] {
  const categories = new Set<OperationsFileCabinetCategory>();
  OPERATIONS_FILE_CABINET_REGISTRY.forEach(item => categories.add(item.category));
  return Array.from(categories);
}

export function getOperationsFileCabinetTypes(): OperationsFileCabinetType[] {
  const types = new Set<OperationsFileCabinetType>();
  OPERATIONS_FILE_CABINET_REGISTRY.forEach(item => types.add(item.type));
  return Array.from(types);
}

export function getOperationsFileCabinetAudiences(): OperationsFileCabinetAudience[] {
  const audiences = new Set<OperationsFileCabinetAudience>();
  OPERATIONS_FILE_CABINET_REGISTRY.forEach(item => item.audience.forEach(audience => audiences.add(audience)));
  return Array.from(audiences);
}

export function getOperationsFileCabinetStatuses(): OperationsFileCabinetStatus[] {
  const statuses = new Set<OperationsFileCabinetStatus>();
  OPERATIONS_FILE_CABINET_REGISTRY.forEach(item => statuses.add(item.status));
  return Array.from(statuses);
}
