export type QaItem = { question: string; answer: string };
export type QaGroup = { title: string; items: readonly QaItem[] };

export const QA_GROUPS: readonly QaGroup[] = [
  {
    title: "What BOF Is and Why It Matters",
    items: [
      {
        question: "What exactly is BOF?",
        answer: "BOF is an integrated business platform and outsourced back-office service for transportation fleets. It combines technology, automation, artificial intelligence, workflows, and administrative services to manage operational records and business processes. BOF provides integrated modules for driver qualification, compliance administration, settlements and payroll, financial management, and exception tracking. These modules connect to a single operating record that ties together drivers, equipment, loads, customers, financial transactions, documents, events, and exceptions. This matters because it allows growing transportation fleets to access organizational capabilities previously available only to large companies. A fleet does not have to build a miniature version of a large transportation company to operate professionally at scale. BOF reduces administrative burden, replaces repetitive administrative work with integrated systems and automation, reduces the need for additional back-office staff as the fleet grows, and creates the foundation for profitable, scalable operations. The owner retains complete control of strategic decisions, operating policy, dispatch, hiring, customer relationships, and business direction."
      },
      {
        question: "Is BOF software, an outsourced back office, or both?",
        answer: "BOF is both. BOF functions as an integrated technology platform that a customer can configure and use, and also as an outsourced back-office service provider. The BOF technology platform includes integrated modules for driver management, compliance, payroll, accounting, settlements, dispatch support, maintenance, procurement, and document control. A customer can implement BOF as software and operate many of its functions internally. Alternatively, depending on the services selected, BOF can assume the operational responsibility for these functions through monitoring, tracking, identifying exceptions, performing follow-up, resolving issues, and maintaining records. This is similar to how large transportation companies operate internal departments for these functions. BOF packages this capability for mid-sized and growing fleets. This provides flexibility and scalability. A smaller fleet might use BOF for document organization and compliance tracking while maintaining internal payroll and accounting. A growing fleet might outsource settlements and payroll processing to BOF. The economic advantage is clear: the fleet receives professional-grade administrative infrastructure and can scale that infrastructure without proportionally increasing internal headcount."
      },
      {
        question: "Can BOF actually replace administrative staff?",
        answer: "Yes. BOF is designed to replace administrative workload, and where outsourced, can replace the need for staff performing that workload. BOF can assume responsibility for administrative functions that would otherwise require internal employees, including driver qualification tracking, document management, compliance monitoring, payroll processing, accounting, settlements, maintenance coordination, and procurement administration. Traditional fleets accumulate administrative staff as they grow. A 30-truck fleet might need a dedicated dispatcher, a safety/compliance person, an HR person, a payroll/accounting person, a maintenance coordinator, and various administrative assistants. These roles exist because the volume and complexity of administrative work exceeds what one or two people can manage. BOF replaces the infrastructure and capacity these roles provide. Where BOF is outsourced, the fleet can reduce or eliminate these roles and replace them with BOF's integrated platform and services. A small team at the fleet can focus on strategic decisions, customer relationships, recruiting, and operations, while BOF handles the administrative workload. This transforms fleet economics. Administrative staff represent a substantial fixed cost that grows with fleet size. When a fleet of 25 trucks adds one more truck, the owner doesn't automatically need a new back-office employee, but the work grows. BOF allows fleets to scale operations without scaling headcount proportionally."
      }
    ]
  },
  {
    title: "The Operating Record and Finance-Operations Integration",
    items: [
      {
        question: "What is the BOF Operating Record?",
        answer: "The BOF Operating Record is the central architectural concept in BOF. It ties together drivers, equipment, loads, customers, documents, financial transactions, events, and exceptions into a single coherent record. Instead of maintaining separate records like a dispatch log, a driver file, a maintenance file, a financial spreadsheet, a compliance checklist, and an email archive, BOF maintains an operating record where all these elements connect. A driver named John is on file with qualifications, credentials, training, medical certification status, and safety history. A load is assigned to John and specific equipment. That load has customer requirements, required documents, proof requirements, and a budget. As John executes the load, the pre-trip checklist connects to the equipment record. The delivery connects to the customer. The expenses connect to the load and the driver. The proof documents connect to the customer requirement and the invoice. The settlement connects to the expenses, the driver compensation, and the company's cash flow. If the driver has a safety incident during the load, that incident connects to the driver record, the equipment record, the customer record, the load record, the corrective action required, the training required, and the driver's safety history. This matters because it converts administrative information from scattered data into organized knowledge. When a problem emerges, the information is already connected. Management can see not just what happened, but what it cost, what it earned, what documents exist, what compliance status applied, and what exceptions emerged."
      },
      {
        question: "How does BOF connect operations to finance?",
        answer: "BOF connects them by treating each operational event as both an operational fact and a financial transaction. Traditional fleets maintain separate operational and financial records. Operations knows what was dispatched, who executed it, and what happened. Finance knows what was billed, what was paid, and where the money went. The two records rarely connect. BOF connects them by design. A load is created with a budget including customer rate, expected equipment cost, expected driver compensation, and expected fuel. The load is assigned to a driver and equipment. The load executes. The driver incurs actual expenses like fuel, tolls, lumping, and reimbursements. The carrier completes the delivery and invoices the customer. The customer pays or disputes. The driver settles with the company. When the load completes and is invoiced, the system instantly calculates profitability by subtracting cost from revenue. In a traditional fleet, this requires pulling information from dispatch records, accounting ledgers, settlement files, and driver expense files, then manually calculating. By then the load is history. In BOF, that calculation is immediate because the data is integrated. This transforms profitability visibility and management decision-making. Fleet owners traditionally cannot answer questions like Which customers are most profitable or Which routes are underpriced because the information is scattered and reconciliation is time-consuming. BOF enables real-time visibility into load-level profitability, customer profitability, driver productivity, and cost control."
      }
    ]
  },
  {
    title: "Driver Administration and Lifecycle",
    items: [
      {
        question: "What does BOF do for drivers?",
        answer: "BOF organizes the entire driver administrative lifecycle from recruitment through ongoing management in a single integrated driver record. BOF manages driver qualifications, credentials, training, documents, pre-trip readiness, load history, proof, reimbursements, settlements, payroll, and BOF Vault access. The driver lifecycle in BOF includes: onboarding and recruitment with background check status, employment documents, I-9 verification, and initial training status; qualifications and credentials including driver licenses, medical certifications, Clearinghouse status, CDL endorsements, and hazmat certifications with automatic expiration monitoring; training and compliance including training completion, refresher requirements, safety training, customer-specific training, and compliance status; safety and performance records including safety incidents, performance metrics, corrective actions, and coaching; pre-trip and load readiness including required documents, proof requirements, customer requirements, equipment status, and compliance status; compensation and settlements including expenses like fuel reimbursement, tolls, detention, and lumping, plus driver settlements per load or pay period and payroll integration; BOF Vault as a portable driver document repository that travels with the driver between employers, retaining credentials, qualifications, and historical records; and load history as a complete record of all loads executed, revenue generated, expenses incurred, and profitability. This matters because it reduces administrative friction for drivers, provides complete visibility into driver productivity and compliance for fleets, creates an auditable compliance record for DOT and insurance purposes, and eliminates separate driver record systems and manual compensation calculations."
      },
      {
        question: "What is BOF Vault for drivers?",
        answer: "BOF Vault is a digital container that holds driver qualifications, credentials, training records, and other professional documents. The driver's BOF account and vault travel with the driver if they change employers. A driver's career traditionally involves losing their administrative record when they change jobs. Qualifications, training records, performance history, and documents remain with the previous employer. The next employer has to request copies or start over with background checks and verification. BOF Vault reverses this paradigm. The driver maintains a Vault that includes their license, medical certification, training certificates, medical opinion documents, background check results, previous performance records, and other qualification evidence. When the driver changes employers, they bring their BOF Vault to the new company. The new employer can view the Vault with the driver's permission, verify credentials instantly, and avoid duplicating background checks or training. The driver's career history and qualifications follow them, reducing onboarding friction. This matters for driver recruiting and retention. A driver applying to a new carrier can share their BOF Vault immediately, proving qualifications without paperwork delays. This accelerates hiring. For the driver, it creates a professional credential record that proves qualifications to multiple employers over their career, which increases the driver's market value and security. For fleets, it reduces onboarding time and cost, enables better hiring decisions based on complete historical information, and improves retention because drivers appreciate working for companies that use professional systems."
      }
    ]
  },
  {
    title: "Dispatch, Compliance, and Financial Visibility",
    items: [
      {
        question: "How does BOF support dispatch?",
        answer: "BOF organizes the administrative context around a load so dispatch can make informed decisions without researching scattered records. BOF does not replace dispatch. Dispatch makes the decisions about what loads to move, which drivers to assign, and when to release. BOF supports these decisions by organizing the information required to make them. When dispatch makes a release decision, many factors matter: Is the driver qualified for this load? Is the equipment in compliance? Are all required customer documents in place? Are there any safety or compliance flags on the driver or equipment? What are the load profitability expectations? Are there any known exceptions? Traditionally, dispatch answers these questions by asking around: calling the compliance person, checking the maintenance board, emailing the driver, looking at the load folder. This is slow and error-prone. BOF assembles this information into a single readiness view showing driver status, equipment status, load requirements, readiness summary, and exceptions and actions. Dispatch can release when readiness is green, can see if yellow items are manageable, and knows what must be resolved before releasing if readiness is red. This matters because it accelerates dispatch decisions, reduces the risk of releasing unready loads which causes customer problems and compliance violations, and improves driver satisfaction."
      },
      {
        question: "How does BOF handle compliance and safety administration?",
        answer: "BOF handles compliance and safety by automating monitoring, organizing records, tracking exceptions, and coordinating follow-up while preserving human judgment for regulated decisions. BOF can assume responsibility for monitoring compliance status, tracking required documents and certifications, identifying expired or missing items, assigning follow-up actions, and maintaining an auditable compliance record. BOF does not make compliance decisions or judgment calls; qualified personnel do. Compliance and safety administration involves multiple parallel processes including driver qualifications like licenses, medical certifications, clearinghouse status, training records, background checks, drug testing, and various certifications with validity periods and renewal requirements; equipment compliance including truck and trailer inspections, maintenance records, out-of-service determinations; safety administration including incident investigation, corrective actions, training requirements resulting from incidents, and performance tracking; and regulatory reporting including annual compliance certifications, audits, licensing renewals, and regulatory filings. BOF automates the coordination by tracking every driver qualification with validity dates and automatically generating alerts 30, 14, 7, and 1 days before renewal; tracking inspection schedules and generating reminders; creating incident records when incidents are reported and tracking corrective actions and training; and assembling documentation for audits and filings. This matters because it prevents compliance failures that result in fines, out-of-service declarations, and insurance claims, and because it eliminates manual coordination work so compliance managers can focus on exceptions and investigations."
      },
      {
        question: "How does BOF improve financial visibility and profitability?",
        answer: "BOF improves financial visibility by connecting operations to finance so management can see load profitability, customer profitability, and cost control in real time. BOF enables load-by-load and customer-by-customer profitability analysis because the operational event, the load, is connected to its financial consequence: cost and revenue. In a traditional fleet, a load is executed, an invoice is sent, the driver settles, and eventually in month-end accounting someone calculates if the load was profitable. But by then it is old news. If the fleet discovers the load was unprofitable, the price has been set, the driver has been paid, and the decision cannot be changed. In a BOF fleet, the load is created with a budget including customer rate, expected equipment cost, expected driver compensation, and expected fuel. As the load executes, actual expenses are recorded. When the load completes and is invoiced, the system instantly calculates profitability: revenue minus cost equals profit or loss. This analysis scales: by aggregating load data, management can answer which customers are most profitable, which routes are most profitable, which drivers generate the most profit per load, and where the company is losing money. This information enables strategic decisions about pricing, customer selection, equipment deployment, and driver management. This matters because profitability-driven management replaces guesswork. Many fleet companies operate for years without actually knowing which customers, routes, or loads are profitable. They make pricing and customer decisions based on intuition. BOF provides the data foundation for profit-driven management."
      }
    ]
  },
  {
    title: "Scaling, Control, and Service Options",
    items: [
      {
        question: "How does BOF help fleets scale?",
        answer: "BOF helps fleets scale by replacing the traditional scaling model where more trucks equals more staff with a model where administrative infrastructure scales with transaction volume instead of headcount. BOF enables fleets to grow without proportionally increasing administrative staff. Traditional scaling looks like: 10 trucks means the owner manages everything; 15 trucks requires adding a part-time dispatcher; 25 trucks requires adding a full-time dispatcher and a safety person; 35 trucks requires adding a compliance person, a maintenance coordinator, and an accounting person; 50 trucks requires adding an HR person and more administrative support. Each truck level creates a new staff position. BOF flips this: 10 trucks means the owner using BOF manages everything using integrated systems; 25 trucks means the owner plus 1 dispatcher plus BOF handles all administrative work that would have required 2 to 3 additional people; 50 trucks means owner plus 2 dispatchers plus BOF handles administrative work that would have required 5 to 6 people; 100 trucks means owner plus team plus BOF handles administrative work that would have required 10 to 15 people. The administrative infrastructure BOF scales with transaction volume: more loads, more drivers, more documents, without requiring proportional headcount increases. This matters because it preserves fleet profitability as the fleet grows. In the traditional model, administrative costs grow with headcount, eroding profitability as the fleet scales. With BOF, administrative costs are variable per transaction rather than fixed per employee, so profitability can improve as scale increases."
      },
      {
        question: "Do I have to give up control of my fleet to use BOF?",
        answer: "No. The fleet owner retains complete control of strategy, operations, hiring, customers, pricing, and business decisions. BOF operates the administrative layer authorized by the owner. Outsourcing administrative work to BOF does not mean outsourcing control of the business. The owner authorizes what functions BOF performs and retains authority over strategic decisions and operating policy. The owner retains control of customers by deciding which customers to serve, what rates to charge, and what service to provide; dispatch and operations by retaining dispatch in-house and deciding which loads to move and which drivers to assign; equipment by deciding what equipment to buy, when to replace it, and how to deploy it; hiring and compensation by deciding what positions to staff internally and what compensation to pay; strategy by deciding the fleet's strategic direction, growth targets, and business model; and safety and compliance policy by setting the safety culture and compliance standards. The owner authorizes BOF to perform driver qualification tracking and monitoring, compliance administration and exception follow-up, document management and organization, settlement calculation and payroll coordination, accounts receivable and customer invoicing, accounts payable and vendor coordination, financial management and reporting, and maintenance scheduling and coordination. The owner can change the arrangement by adding or subtracting services based on the fleet's needs. This model is similar to how large companies operate. The CEO does not personally manage payroll processing, accounts payable, or document filing. These functions are managed by internal departments or outsourced to providers. The CEO makes strategic decisions and holds the departments accountable."
      }
    ]
  }
];
