import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Finance | BackOfficeFleet", description: "Financial administration for growing trucking fleets." };

const responsibilities = [
  ["Payroll", "Fleet work today: reconcile driver settlement inputs, deductions, approvals, holds, and payroll timing between operations, spreadsheets, and a payroll provider. BOF can organize the inputs and exceptions before payroll coordination.", "Records maintained: settlement status, pay inputs, deductions, approvals, holds, supporting proof, and next action."],
  ["Cash Management", "Fleet work today: assemble a view of expected receipts, held money, upcoming obligations, and operating pressure from separate finance and operations records. BOF provides visibility and coordination rather than promising a financial result.", "Records maintained: cash-related exceptions, timing context, open receivables, holds, obligations, owner, and review status."],
  ["Excise Taxes", "Fleet work today: maintain recurring tax records, reporting periods, supporting fuel and operating information, deadlines, and handoffs to the appropriate tax professional or provider. BOF can track the administrative process and missing inputs.", "Records maintained: period, filing or review deadline, supporting records, responsible owner, handoff, and completion status."],
  ["Invoicing", "Fleet work today: match delivery proof, accessorials, deductions, customer requirements, and invoice details before sending or correcting an invoice. BOF connects invoice readiness to the load and proof record.", "Records maintained: load reference, POD and BOL status, accessorial support, deduction context, invoice status, dispute reason, and owner."],
  ["Factoring", "Fleet work today: assemble receivables and proof packets for factoring review while chasing missing documents through email and shared folders. BOF keeps packet readiness and missing evidence visible.", "Records maintained: receivable, proof packet, invoice, customer, missing item, submission status, and follow-up owner."],
  ["Financial Administration", "Fleet work today: reconcile vendor, customer, driver, load, settlement, and accounting information across systems and recurring reports. BOF organizes the administrative record and routes exceptions for resolution.", "Records maintained: financial reference, linked operating record, status, supporting documents, approval history, and unresolved action."],
] as const;

export default function FinancePage() {
  return <main className="bof-service-page"><div className="bof-mkt-container">
    <header className="bof-service-page__hero"><p className="bof-home-eyebrow">What BOF Takes Over</p><h1>FINANCE</h1><p>BOF can take responsibility for the financial administration behind the fleet, connecting settlements, proof, invoices, receivables, deductions, and cash visibility in one record.</p></header>
    <section className="bof-service-page__section"><h2>What a 20–30 truck fleet has to build internally</h2><p>At this size, finance work often sits between the owner, bookkeeper, payroll provider, dispatch, and operations staff. Someone must reconcile spreadsheets, email, accounting records, proof, and settlement questions by hand. BOF can take over that coordination and exception follow-up without claiming to be a bank, lender, accounting firm, payroll provider, or tax advisor.</p></section>
    <section className="bof-service-page__section"><h2>Financial responsibilities</h2><div className="bof-service-page__items">{responsibilities.map(([title, work, records]) => <article key={title}><h3>{title}</h3><p>{work}</p><p><strong>{records}</strong></p></article>)}</div></section>
    <section className="bof-service-page__section bof-service-page__section--dark"><h2>How the work connects</h2><p>Settlement information connects to drivers and loads. Delivery proof supports invoices. Invoices and receivables inform factoring and cash review. Deductions and exceptions stay attached to the operating record instead of being reconciled later from memory.</p><p>BOF identifies missing evidence, aging follow-up, unresolved deductions, and deadline-driven actions so a finance question has a visible owner and next step.</p></section>
    <section className="bof-service-page__section"><h2>Operational outcome</h2><p>The fleet gets a more usable financial administration record and fewer manual handoffs between operations and finance. BOF can take responsibility for the recurring coordination that would otherwise increase the need for additional finance or accounting support as the fleet grows.</p><div className="bof-service-page__actions"><Link href="/dashboard" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">SEE BOF IN ACTION</Link><Link href="/book-assessment?source=finance" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-secondary">FLEET ASSESSMENT</Link></div></section>
  </div></main>;
}
