import type { ClientLoadRequest } from "@/lib/client-load-requests";
import type { IntakeWizardState } from "@/lib/load-requirements-intake-types";

/** Builds the canonical load-intake wizard state from an approved client load request row. */
export function buildIntakeWizardStateFromClientRequest(request: ClientLoadRequest): IntakeWizardState {
  return {
    lastDraftSavedAt: null,
    shipper: {
      shipper_id: "SHIP-CLIENT-REQUEST",
      shipper_name: request.companyName,
      primary_contact_name: request.contactName,
      primary_contact_email: request.contactEmail,
      primary_contact_phone: request.contactPhone,
    },
    facility: {
      facility_id: "FAC-CLIENT-REQUEST",
      shipper_id: "SHIP-CLIENT-REQUEST",
      facility_name: request.pickupFacilityName,
      address: request.pickupAddress1,
      city: request.pickupCity,
      state: request.pickupState,
      zip: request.pickupZip ?? "",
      facility_rules: request.pickupInstructions || "",
      appointment_required: true,
    },
    loadRequirement: {
      load_requirement_id: `LR-${request.requestId}`,
      shipper_id: "SHIP-CLIENT-REQUEST",
      facility_id: "FAC-CLIENT-REQUEST",
      load_id_input: "",
      pickup_at: `${request.pickupDate}T${request.pickupTime || "08:00"}`,
      delivery_at: `${request.deliveryDate}T${request.deliveryTime || "17:00"}`,
      commodity: request.commodity,
      weight: request.weight || 0,
      pallet_count: request.palletCount || 0,
      piece_count: request.palletCount || 0,
      rate_linehaul: request.quotedRate || 0,
      assigned_driver_id: "",
      truck_id: "",
      trailer_id: "",
      intake_status: "scheduled",
      bol_number: request.bolNumber || "",
      invoice_number: "",
      seal_number: request.sealNumber || "",
      rfid_proof_required: false,
      insurance_requirements_summary: request.specialInsuranceNotes || "",
      pod_bol_instructions: request.deliveryInstructions || "",
      backhaul_pay: 0,
      claim_damage_flag: false,
      equipment_type: request.equipmentType,
      special_handling: request.specialHandlingInstructions || "",
      destination_facility_name: request.deliveryFacilityName,
      destination_address: request.deliveryAddress1,
      destination_city: request.deliveryCity,
      destination_state: request.deliveryState,
      destination_zip: request.deliveryZip ?? "",
      route_memory_key: "",
      temperature_required: Boolean(request.temperatureRequirement),
      temperature_min: undefined,
      temperature_max: undefined,
    },
    compliance: {
      requirement_id: `REQ-${request.requestId}`,
      load_requirement_id: `LR-${request.requestId}`,
      seal_required: Boolean(request.sealRequired),
      seal_number_required: Boolean(request.sealRequired),
      pickup_photos_required: false,
      delivery_photos_required: true,
      cargo_photos_required: Boolean(request.cargoPhotoRequired),
      insuranceRequirementType: "Standard COI",
      cargoCoverageLevel: "$250k",
      certificateRequired: Boolean(request.insuranceRequired),
      additionalInsuredRequired: false,
      facilityEndorsementRequired: false,
      bolRequirementType: "Standard shipper BOL",
      signedBolRequired: true,
      palletCountRequired: true,
      pieceCountRequired: true,
      sealNotationRequired: Boolean(request.sealRequired),
      bolSpecialInstructions: request.pickupInstructions || "",
      podRequirementType: "POD + photo evidence",
      signedPodRequired: true,
      receiverPrintedNameRequired: true,
      deliveryPhotoRequired: true,
      emptyTrailerPhotoRequired: false,
      sealVerificationRequired: Boolean(request.sealRequired),
      gpsTimestampRequired: true,
      podSpecialInstructions: request.deliveryInstructions || "",
      insurance_requirements: request.specialInsuranceNotes || "",
      appointment_window_start: `${request.pickupDate}T${request.pickupTime || "08:00"}`,
      appointment_window_end: `${request.deliveryDate}T${request.deliveryTime || "17:00"}`,
      bol_instructions: request.pickupInstructions || "",
      pod_requirements: request.deliveryInstructions || "",
      accessorial_rules: request.paymentTerms || "",
      lumper_expected: Boolean(request.pickupInstructions?.toLowerCase().includes("lumper")),
    },
    loadPacket: null,
  };
}
