export interface BankInfoData {
  driverId: string;
  fullName: string;
  streetAddress: string;
  city: string;
  state: string;
  zip: string;
  phone: string;
  email: string;
  bankName: string;
  routingNumber: string;
  accountNumber: string;
  accountType: "Checking" | "Savings";
  paymentPreference: string;
  bankInfoStatus: string;
  submissionDate: string;
  taxClassification: string;
  tinType: string;
  w9Status: string;
}

// TODO: In production this should come from the BOF payroll/banking API.
export const bankInfoData: BankInfoData[] = [
  {
    driverId: "DRV-001",
    fullName: "John Carter",
    streetAddress: "1240 W 6th St",
    city: "Cleveland",
    state: "OH",
    zip: "44113",
    phone: "206-667-3424",
    email: "jcarter@yahoo.com",
    paymentPreference: "Direct Deposit",
    bankName: "Huntington National Bank",
    accountType: "Checking",
    routingNumber: "423877480",
    accountNumber: "••••••5636",
    submissionDate: "April 10, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-002",
    fullName: "Maria Lopez",
    streetAddress: "450 N Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    phone: "707-773-6386",
    email: "marialopez@aol.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Checking",
    routingNumber: "465266204",
    accountNumber: "••••••1328",
    submissionDate: "June 03, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-003",
    fullName: "Alex Kim",
    streetAddress: "780 Peachtree St",
    city: "Atlanta",
    state: "GA",
    zip: "30308",
    phone: "675-486-1335",
    email: "alexkim@gmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Checking",
    routingNumber: "942648543",
    accountNumber: "••••••4641",
    submissionDate: "July 15, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-004",
    fullName: "Priya Patel",
    streetAddress: "2200 Superior Ave",
    city: "Cleveland",
    state: "OH",
    zip: "44114",
    phone: "359-469-5960",
    email: "priyapatel@yahoo.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Savings",
    routingNumber: "190070998",
    accountNumber: "••••••7109",
    submissionDate: "May 20, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-005",
    fullName: "Kenji Tanaka",
    streetAddress: "115 E Broad St",
    city: "Columbus",
    state: "OH",
    zip: "43215",
    phone: "871-429-6220",
    email: "ktanaka@yahoo.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Checking",
    routingNumber: "426693965",
    accountNumber: "••••••8966",
    submissionDate: "August 05, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-006",
    fullName: "Marcus Chen",
    streetAddress: "500 Pacific Ave",
    city: "Dallas",
    state: "TX",
    zip: "75202",
    phone: "283-876-4322",
    email: "mchen@hotmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Checking",
    routingNumber: "973738233",
    accountNumber: "••••••0803",
    submissionDate: "September 09, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-007",
    fullName: "Sofia Gomez",
    streetAddress: "815 Prospect Ave",
    city: "Cleveland",
    state: "OH",
    zip: "44115",
    phone: "896-828-7164",
    email: "sofiagomez@yahoo.com",
    paymentPreference: "Direct Deposit",
    bankName: "Bank of America",
    accountType: "Checking",
    routingNumber: "865581806",
    accountNumber: "••••••9424",
    submissionDate: "October 01, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-008",
    fullName: "Liam Smith",
    streetAddress: "240 Madison Ave",
    city: "Toledo",
    state: "OH",
    zip: "43604",
    phone: "820-223-4829",
    email: "liamsmith@gmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "PNC Bank",
    accountType: "Checking",
    routingNumber: "560687670",
    accountNumber: "••••••4220",
    submissionDate: "June 24, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-009",
    fullName: "Emma Brown",
    streetAddress: "330 Civic Center Dr",
    city: "Columbus",
    state: "OH",
    zip: "43215",
    phone: "206-700-7666",
    email: "emmabrown@yahoo.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Savings",
    routingNumber: "347101867",
    accountNumber: "••••••8087",
    submissionDate: "July 29, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-010",
    fullName: "Noah Wilson",
    streetAddress: "110 W Adams St",
    city: "Chicago",
    state: "IL",
    zip: "60603",
    phone: "582-987-2387",
    email: "nwilson@gmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "Chase Bank",
    accountType: "Checking",
    routingNumber: "446897081",
    accountNumber: "••••••6839",
    submissionDate: "August 19, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-011",
    fullName: "Olivia Lee",
    streetAddress: "600 Peachtree St",
    city: "Atlanta",
    state: "GA",
    zip: "30308",
    phone: "337-857-3607",
    email: "olee@hotmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "Bank of America",
    accountType: "Savings",
    routingNumber: "207931918",
    accountNumber: "••••••2449",
    submissionDate: "September 16, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
  {
    driverId: "DRV-012",
    fullName: "Robert Johnson",
    streetAddress: "618 S Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60605",
    phone: "618-667-2121",
    email: "robertjohnson@hotmail.com",
    paymentPreference: "Direct Deposit",
    bankName: "Wells Fargo Bank",
    accountType: "Checking",
    routingNumber: "782385202",
    accountNumber: "••••••1916",
    submissionDate: "October 14, 2024",
    bankInfoStatus: "Verified",
    taxClassification: "Individual/Sole Proprietor",
    tinType: "SSN",
    w9Status: "Received",
  },
];

export const bankInfoByDriverId = new Map(bankInfoData.map((d) => [d.driverId, d]));

