export interface EmergencyContact {
  name: string;
  relationship: string;
  phone: string;
  email: string;
  address: string;
}

export interface Driver {
  id: string;
  firstName: string;
  lastName: string;
  fullName: string;
  phone: string;
  email: string;
  fullAddress: string;
  dob: string;
  gender: string;
  hair: string;
  eyes: string;
  height: string;
  weight: string;
  ethnicity: string;
  licenseClass: string;
  licenseNumber: string;
  licenseState: string;
  primaryContact: EmergencyContact;
  secondaryContact: EmergencyContact;
}

export type DriverWithEC = Driver;

// TODO: In production this should come from the BOF driver API.
export const emergencyContactDrivers: DriverWithEC[] = [
  {
    id: "DRV-001",
    firstName: "John",
    lastName: "Carter",
    fullName: "John Carter",
    phone: "206-667-3424",
    email: "jcarter@yahoo.com",
    fullAddress: "1240 W 6th St, Cleveland, OH 44113",
    dob: "01/08/1971",
    gender: "M",
    hair: "Black",
    eyes: "Green",
    height: "5'-10\"",
    weight: "180",
    ethnicity: "Caucasian",
    licenseClass: "Class A",
    licenseNumber: "OH1668243",
    licenseState: "OH",
    primaryContact: {
      name: "Sarah Carter",
      relationship: "Spouse",
      phone: "206-482-0199",
      email: "sarah.carter@gmail.com",
      address: "1240 W 6th St, Cleveland, OH 44113",
    },
    secondaryContact: {
      name: "Mark Carter",
      relationship: "Brother",
      phone: "216-347-8321",
      email: "mcarter@aol.com",
      address: "3920 Lorain Ave, Cleveland, OH 44113",
    },
  },
  {
    id: "DRV-002",
    firstName: "Maria",
    lastName: "Lopez",
    fullName: "Maria Lopez",
    phone: "707-773-6386",
    email: "marialopez@aol.com",
    fullAddress: "450 N Michigan Ave, Chicago, IL 60611",
    dob: "01/04/1983",
    gender: "F",
    hair: "Brown",
    eyes: "Hazel",
    height: "5'-3\"",
    weight: "134",
    ethnicity: "Hispanic",
    licenseClass: "Class A",
    licenseNumber: "IL3091126",
    licenseState: "IL",
    primaryContact: {
      name: "Carlos Lopez",
      relationship: "Spouse",
      phone: "312-739-4718",
      email: "clopez@yahoo.com",
      address: "450 N Michigan Ave, Chicago, IL 60611",
    },
    secondaryContact: {
      name: "Rosa Hernandez",
      relationship: "Mother",
      phone: "312-482-2364",
      email: "rosa.hernandez@gmail.com",
      address: "1835 S Blue Island Ave, Chicago, IL 60608",
    },
  },
  {
    id: "DRV-003",
    firstName: "Alex",
    lastName: "Kim",
    fullName: "Alex Kim",
    phone: "675-486-1335",
    email: "alexkim@gmail.com",
    fullAddress: "780 Peachtree St, Atlanta, GA 30308",
    dob: "01/04/1971",
    gender: "M",
    hair: "Brown",
    eyes: "Blue",
    height: "6'-2\"",
    weight: "214",
    ethnicity: "Asian",
    licenseClass: "Class A",
    licenseNumber: "GA7446431",
    licenseState: "GA",
    primaryContact: {
      name: "Min-Ji Kim",
      relationship: "Spouse",
      phone: "404-347-8293",
      email: "minji.kim@hotmail.com",
      address: "780 Peachtree St, Atlanta, GA 30308",
    },
    secondaryContact: {
      name: "Daniel Kim",
      relationship: "Brother",
      phone: "770-618-4917",
      email: "dkim@yahoo.com",
      address: "2145 Buford Hwy, Atlanta, GA 30329",
    },
  },
  {
    id: "DRV-004",
    firstName: "Priya",
    lastName: "Patel",
    fullName: "Priya Patel",
    phone: "359-469-5960",
    email: "priyapatel@yahoo.com",
    fullAddress: "2200 Superior Ave, Cleveland, OH 44114",
    dob: "08/12/1993",
    gender: "F",
    hair: "Brown",
    eyes: "Blue",
    height: "5'-7\"",
    weight: "148",
    ethnicity: "South Asian",
    licenseClass: "Class A",
    licenseNumber: "OH8493496",
    licenseState: "OH",
    primaryContact: {
      name: "Raj Patel",
      relationship: "Spouse",
      phone: "216-618-3847",
      email: "raj.patel@aol.com",
      address: "2200 Superior Ave, Cleveland, OH 44114",
    },
    secondaryContact: {
      name: "Anita Sharma",
      relationship: "Sister",
      phone: "216-739-6102",
      email: "anita.sharma@hotmail.com",
      address: "1480 E 9th St, Cleveland, OH 44114",
    },
  },
  {
    id: "DRV-005",
    firstName: "Kenji",
    lastName: "Tanaka",
    fullName: "Kenji Tanaka",
    phone: "871-429-6220",
    email: "ktanaka@yahoo.com",
    fullAddress: "115 E Broad St, Columbus, OH 43215",
    dob: "10/18/1966",
    gender: "M",
    hair: "Black",
    eyes: "Green",
    height: "5'-10\"",
    weight: "193",
    ethnicity: "Asian",
    licenseClass: "Class A",
    licenseNumber: "OH2779041",
    licenseState: "OH",
    primaryContact: {
      name: "Yuki Tanaka",
      relationship: "Spouse",
      phone: "614-823-9012",
      email: "ytanaka@gmail.com",
      address: "115 E Broad St, Columbus, OH 43215",
    },
    secondaryContact: {
      name: "Hiroshi Tanaka",
      relationship: "Father",
      phone: "614-276-3485",
      email: "htanaka@aol.com",
      address: "445 N High St, Columbus, OH 43215",
    },
  },
  {
    id: "DRV-006",
    firstName: "Marcus",
    lastName: "Chen",
    fullName: "Marcus Chen",
    phone: "283-876-4322",
    email: "mchen@hotmail.com",
    fullAddress: "500 Pacific Ave, Dallas, TX 75202",
    dob: "02/08/1970",
    gender: "M",
    hair: "Bald",
    eyes: "Brown",
    height: "6'-1\"",
    weight: "238",
    ethnicity: "Asian",
    licenseClass: "Class A",
    licenseNumber: "TX3261112",
    licenseState: "TX",
    primaryContact: {
      name: "Linda Chen",
      relationship: "Spouse",
      phone: "214-491-6734",
      email: "linda.chen@yahoo.com",
      address: "500 Pacific Ave, Dallas, TX 75202",
    },
    secondaryContact: {
      name: "Wei Chen",
      relationship: "Brother",
      phone: "214-384-8923",
      email: "wei.chen@gmail.com",
      address: "2727 Commerce St, Dallas, TX 75226",
    },
  },
  {
    id: "DRV-007",
    firstName: "Sofia",
    lastName: "Gomez",
    fullName: "Sofia Gomez",
    phone: "896-828-7164",
    email: "sofiagomez@yahoo.com",
    fullAddress: "815 Prospect Ave, Cleveland, OH 44115",
    dob: "12/14/1999",
    gender: "F",
    hair: "Blonde",
    eyes: "Blue",
    height: "5'-4\"",
    weight: "122",
    ethnicity: "Hispanic",
    licenseClass: "Class A",
    licenseNumber: "OH6635833",
    licenseState: "OH",
    primaryContact: {
      name: "Miguel Gomez",
      relationship: "Father",
      phone: "216-276-1482",
      email: "mgomez@hotmail.com",
      address: "2847 Clark Ave, Cleveland, OH 44109",
    },
    secondaryContact: {
      name: "Isabel Torres",
      relationship: "Mother",
      phone: "216-917-7536",
      email: "itorres@yahoo.com",
      address: "4310 Lorain Ave, Cleveland, OH 44113",
    },
  },
  {
    id: "DRV-008",
    firstName: "Liam",
    lastName: "Smith",
    fullName: "Liam Smith",
    phone: "820-223-4829",
    email: "liamsmith@gmail.com",
    fullAddress: "240 Madison Ave, Toledo, OH 43604",
    dob: "08/23/1964",
    gender: "M",
    hair: "Blonde",
    eyes: "Blue",
    height: "6'-2\"",
    weight: "194",
    ethnicity: "Caucasian",
    licenseClass: "Class A",
    licenseNumber: "OH9450480",
    licenseState: "OH",
    primaryContact: {
      name: "Jessica Smith",
      relationship: "Spouse",
      phone: "419-384-2938",
      email: "jessica.smith@gmail.com",
      address: "240 Madison Ave, Toledo, OH 43604",
    },
    secondaryContact: {
      name: "Brian Smith",
      relationship: "Brother",
      phone: "419-653-6147",
      email: "brian.smith@hotmail.com",
      address: "520 Jefferson Ave, Toledo, OH 43604",
    },
  },
  {
    id: "DRV-009",
    firstName: "Emma",
    lastName: "Brown",
    fullName: "Emma Brown",
    phone: "206-700-7666",
    email: "emmabrown@yahoo.com",
    fullAddress: "330 Civic Center Dr, Columbus, OH 43215",
    dob: "10/16/1984",
    gender: "F",
    hair: "Black",
    eyes: "Brown",
    height: "5'-4\"",
    weight: "144",
    ethnicity: "Caucasian",
    licenseClass: "Class B",
    licenseNumber: "OH6116714",
    licenseState: "OH",
    primaryContact: {
      name: "Michael Brown",
      relationship: "Spouse",
      phone: "614-917-7261",
      email: "mbrown@aol.com",
      address: "330 Civic Center Dr, Columbus, OH 43215",
    },
    secondaryContact: {
      name: "Laura Davis",
      relationship: "Sister",
      phone: "614-491-1893",
      email: "ldavis@gmail.com",
      address: "175 S 3rd St, Columbus, OH 43215",
    },
  },
  {
    id: "DRV-010",
    firstName: "Noah",
    lastName: "Wilson",
    fullName: "Noah Wilson",
    phone: "582-987-2387",
    email: "nwilson@gmail.com",
    fullAddress: "110 W Adams St, Chicago, IL 60603",
    dob: "09/11/1966",
    gender: "M",
    hair: "Black",
    eyes: "Hazel",
    height: "6'-3\"",
    weight: "219",
    ethnicity: "Black",
    licenseClass: "Class A",
    licenseNumber: "IL3858215",
    licenseState: "IL",
    primaryContact: {
      name: "Angela Wilson",
      relationship: "Spouse",
      phone: "312-653-8145",
      email: "angela.wilson@yahoo.com",
      address: "110 W Adams St, Chicago, IL 60603",
    },
    secondaryContact: {
      name: "Terrance Wilson",
      relationship: "Brother",
      phone: "773-823-4628",
      email: "terrance.wilson@aol.com",
      address: "7830 S Cottage Grove Ave, Chicago, IL 60619",
    },
  },
  {
    id: "DRV-011",
    firstName: "Olivia",
    lastName: "Lee",
    fullName: "Olivia Lee",
    phone: "337-857-3607",
    email: "olee@hotmail.com",
    fullAddress: "600 Peachtree St, Atlanta, GA 30308",
    dob: "03/14/1968",
    gender: "F",
    hair: "Brown",
    eyes: "Hazel",
    height: "5'-5\"",
    weight: "148",
    ethnicity: "South Asian",
    licenseClass: "Class A",
    licenseNumber: "GA8190601",
    licenseState: "GA",
    primaryContact: {
      name: "Vikram Sharma",
      relationship: "Spouse",
      phone: "404-741-3619",
      email: "vsharma@gmail.com",
      address: "600 Peachtree St, Atlanta, GA 30308",
    },
    secondaryContact: {
      name: "Meera Nair",
      relationship: "Sister",
      phone: "678-294-2740",
      email: "mnair@hotmail.com",
      address: "1255 Ponce De Leon Ave, Atlanta, GA 30306",
    },
  },
  {
    id: "DRV-012",
    firstName: "Robert",
    lastName: "Johnson",
    fullName: "Robert Johnson",
    phone: "618-667-2121",
    email: "robertjohnson@hotmail.com",
    fullAddress: "618 S Michigan Ave, Chicago, IL 60605",
    dob: "04/11/1990",
    gender: "M",
    hair: "Blonde",
    eyes: "Green",
    height: "6'-1\"",
    weight: "209",
    ethnicity: "Caucasian",
    licenseClass: "Class A",
    licenseNumber: "IL1895570",
    licenseState: "IL",
    primaryContact: {
      name: "Karen Johnson",
      relationship: "Spouse",
      phone: "312-294-5478",
      email: "karen.johnson@hotmail.com",
      address: "618 S Michigan Ave, Chicago, IL 60605",
    },
    secondaryContact: {
      name: "David Johnson",
      relationship: "Brother",
      phone: "312-741-9317",
      email: "david.johnson@yahoo.com",
      address: "425 S Wabash Ave, Chicago, IL 60605",
    },
  },
];

