import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "People & HR | BackOfficeFleet",
  description: "Administrative People and HR operations for growing trucking fleets.",
};

const responsibilities = [
  ["Recruiting", "Fleet work today: collect applications, compare candidates, schedule follow-up, and move qualified people into onboarding across inboxes and spreadsheets. BOF takes responsibility for organizing the recruiting handoff, candidate status, required records, and next action so recruiting does not end at a phone call.", "Records maintained: candidate status, contact history, role requirements, document requests, and onboarding readiness."],
  ["Onboarding", "Fleet work today: chase forms, IDs, tax documents, training items, and policy acknowledgements before a new driver can be considered for work. BOF connects the request to driver qualification and the driver record instead of leaving the process in shared drives.", "Records maintained: onboarding checklist, received and missing items, review status, assigned owner, and qualification handoff."],
  ["Driver Records", "Fleet work today: keep licenses, medical cards, MVRs, restrictions, training, and employment records current while dates and documents change. BOF maintains the driver record and flags missing, expiring, conflicting, or overdue information.", "Records maintained: driver profile, credential dates, qualification evidence, restrictions, training history, notes, and readiness status."],
  ["Performance Management", "Fleet work today: connect operating performance, coaching notes, incidents, recognition, and incentive context without rebuilding the story from dispatch and payroll records. BOF keeps the administrative performance record connected to the relevant operating events.", "Records maintained: review notes, assigned actions, performance context, coaching follow-up, and supported incentive inputs."],
  ["Training & Development", "Fleet work today: track required training, renewals, coaching, and completion evidence through manual reminders. BOF identifies due and overdue actions, keeps completion records, and connects training status to safety, compliance, and readiness review.", "Records maintained: training requirement, due date, completion evidence, reviewer, follow-up owner, and related safety record."],
  ["Benefits Administration", "Fleet work today: coordinate enrollment questions, changes, eligibility records, and provider follow-up as an administrative process separate from the rest of the workforce record. BOF can organize the workflow, dates, documents, and handoffs without acting as an insurer or benefits provider.", "Records maintained: request status, eligibility context, submitted documentation, deadlines, provider handoff, and unresolved action."],
] as const;

export default function PeopleHrPage() {
  return <main className="bof-service-page"><div className="bof-mkt-container">
    <header className="bof-service-page__hero"><p className="bof-home-eyebrow">What BOF Takes Over</p><h1>PEOPLE &amp; HR</h1><p>BOF can take responsibility for the administrative lifecycle behind the fleet&apos;s workforce, from recruiting and onboarding through records, performance, training, and benefits coordination.</p></header>
    <section className="bof-service-page__section"><h2>What a 20–30 truck fleet has to build internally</h2><p>As the fleet grows, people work is often distributed across the owner, dispatch, safety, payroll, and whoever has time to chase the next document. Email, spreadsheets, shared drives, reminders, and manual follow-up become the operating system. BOF can take over the coordination and record maintenance that would otherwise require additional back-office staffing.</p></section>
    <section className="bof-service-page__section"><h2>Administrative responsibilities</h2><div className="bof-service-page__items">{responsibilities.map(([title, work, records]) => <article key={title}><h3>{title}</h3><p>{work}</p><p><strong>{records}</strong></p></article>)}</div></section>
    <section className="bof-service-page__section bof-service-page__section--dark"><h2>How the work connects</h2><p>Recruiting becomes onboarding. Onboarding becomes qualification and a driver record. The driver record becomes readiness evidence for dispatch. Performance and training connect back to safety, compliance, and future assignment decisions. BOF keeps the status, evidence, owner, exception, and next action in the broader operating record.</p><p>When something is missing or overdue, BOF surfaces it for follow-up and keeps the issue visible until the responsible person resolves it.</p></section>
    <section className="bof-service-page__section"><h2>Operational outcome</h2><p>The fleet gets a maintained workforce record, clearer readiness decisions, and less administrative chasing spread across operating staff. BOF does not promise to eliminate every internal role; it takes responsibility for the back-office work that would otherwise make the fleet add staff sooner.</p><div className="bof-service-page__actions"><Link href="/dashboard" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-primary">SEE BOF IN ACTION</Link><Link href="/book-assessment?source=people-hr" className="bof-mkt-btn-enterprise bof-mkt-btn-enterprise-secondary">FLEET ASSESSMENT</Link></div></section>
  </div></main>;
}
